
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Toko: 'Toko',
  Pelanggan: 'Pelanggan',
  SesiPemesanan: 'SesiPemesanan',
  Meja: 'Meja',
  Item: 'Item',
  Transaksi: 'Transaksi',
  AntrianOrder: 'AntrianOrder'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const TokoScalarFieldEnum = {
  id_toko: 'id_toko',
  nama_toko: 'nama_toko',
  jenis_toko: 'jenis_toko'
} as const

export type TokoScalarFieldEnum = (typeof TokoScalarFieldEnum)[keyof typeof TokoScalarFieldEnum]


export const PelangganScalarFieldEnum = {
  id_pelanggan: 'id_pelanggan',
  nama_pembeli: 'nama_pembeli',
  password: 'password'
} as const

export type PelangganScalarFieldEnum = (typeof PelangganScalarFieldEnum)[keyof typeof PelangganScalarFieldEnum]


export const SesiPemesananScalarFieldEnum = {
  id_sesi: 'id_sesi',
  no_meja: 'no_meja',
  id_pelanggan: 'id_pelanggan',
  tanggal_pemesanan: 'tanggal_pemesanan',
  status_sesi: 'status_sesi'
} as const

export type SesiPemesananScalarFieldEnum = (typeof SesiPemesananScalarFieldEnum)[keyof typeof SesiPemesananScalarFieldEnum]


export const MejaScalarFieldEnum = {
  no_meja: 'no_meja',
  id_sesi: 'id_sesi',
  status_meja: 'status_meja'
} as const

export type MejaScalarFieldEnum = (typeof MejaScalarFieldEnum)[keyof typeof MejaScalarFieldEnum]


export const ItemScalarFieldEnum = {
  id_item: 'id_item',
  nama_item: 'nama_item',
  harga_item: 'harga_item',
  id_toko: 'id_toko'
} as const

export type ItemScalarFieldEnum = (typeof ItemScalarFieldEnum)[keyof typeof ItemScalarFieldEnum]


export const TransaksiScalarFieldEnum = {
  id_transaksi: 'id_transaksi',
  id_sesi: 'id_sesi',
  id_toko: 'id_toko',
  jenis_transaksi: 'jenis_transaksi',
  total_harga: 'total_harga',
  status_pesanan: 'status_pesanan',
  tanggal_transaksi: 'tanggal_transaksi'
} as const

export type TransaksiScalarFieldEnum = (typeof TransaksiScalarFieldEnum)[keyof typeof TransaksiScalarFieldEnum]


export const AntrianOrderScalarFieldEnum = {
  order_line: 'order_line',
  id_transaksi: 'id_transaksi',
  id_item: 'id_item',
  jumlah_item: 'jumlah_item',
  subtotal: 'subtotal'
} as const

export type AntrianOrderScalarFieldEnum = (typeof AntrianOrderScalarFieldEnum)[keyof typeof AntrianOrderScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

