
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.1.0
 * Query Engine version: ab635e6b9d606fa5c8fb8b1a7f909c3c3c1c98ba
 */
export const prismaVersion: PrismaVersion = {
  client: "7.1.0",
  engine: "ab635e6b9d606fa5c8fb8b1a7f909c3c3c1c98ba"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  Toko: 'Toko',
  Pelanggan: 'Pelanggan',
  SesiPemesanan: 'SesiPemesanan',
  Meja: 'Meja',
  Item: 'Item',
  Transaksi: 'Transaksi',
  AntrianOrder: 'AntrianOrder'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "toko" | "pelanggan" | "sesiPemesanan" | "meja" | "item" | "transaksi" | "antrianOrder"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    Toko: {
      payload: Prisma.$TokoPayload<ExtArgs>
      fields: Prisma.TokoFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TokoFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokoPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TokoFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokoPayload>
        }
        findFirst: {
          args: Prisma.TokoFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokoPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TokoFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokoPayload>
        }
        findMany: {
          args: Prisma.TokoFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokoPayload>[]
        }
        create: {
          args: Prisma.TokoCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokoPayload>
        }
        createMany: {
          args: Prisma.TokoCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TokoCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokoPayload>[]
        }
        delete: {
          args: Prisma.TokoDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokoPayload>
        }
        update: {
          args: Prisma.TokoUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokoPayload>
        }
        deleteMany: {
          args: Prisma.TokoDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TokoUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TokoUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokoPayload>[]
        }
        upsert: {
          args: Prisma.TokoUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokoPayload>
        }
        aggregate: {
          args: Prisma.TokoAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateToko>
        }
        groupBy: {
          args: Prisma.TokoGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TokoGroupByOutputType>[]
        }
        count: {
          args: Prisma.TokoCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TokoCountAggregateOutputType> | number
        }
      }
    }
    Pelanggan: {
      payload: Prisma.$PelangganPayload<ExtArgs>
      fields: Prisma.PelangganFieldRefs
      operations: {
        findUnique: {
          args: Prisma.PelangganFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PelangganPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.PelangganFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PelangganPayload>
        }
        findFirst: {
          args: Prisma.PelangganFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PelangganPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.PelangganFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PelangganPayload>
        }
        findMany: {
          args: Prisma.PelangganFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PelangganPayload>[]
        }
        create: {
          args: Prisma.PelangganCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PelangganPayload>
        }
        createMany: {
          args: Prisma.PelangganCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.PelangganCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PelangganPayload>[]
        }
        delete: {
          args: Prisma.PelangganDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PelangganPayload>
        }
        update: {
          args: Prisma.PelangganUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PelangganPayload>
        }
        deleteMany: {
          args: Prisma.PelangganDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.PelangganUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.PelangganUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PelangganPayload>[]
        }
        upsert: {
          args: Prisma.PelangganUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PelangganPayload>
        }
        aggregate: {
          args: Prisma.PelangganAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregatePelanggan>
        }
        groupBy: {
          args: Prisma.PelangganGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PelangganGroupByOutputType>[]
        }
        count: {
          args: Prisma.PelangganCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PelangganCountAggregateOutputType> | number
        }
      }
    }
    SesiPemesanan: {
      payload: Prisma.$SesiPemesananPayload<ExtArgs>
      fields: Prisma.SesiPemesananFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SesiPemesananFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SesiPemesananPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SesiPemesananFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SesiPemesananPayload>
        }
        findFirst: {
          args: Prisma.SesiPemesananFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SesiPemesananPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SesiPemesananFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SesiPemesananPayload>
        }
        findMany: {
          args: Prisma.SesiPemesananFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SesiPemesananPayload>[]
        }
        create: {
          args: Prisma.SesiPemesananCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SesiPemesananPayload>
        }
        createMany: {
          args: Prisma.SesiPemesananCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SesiPemesananCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SesiPemesananPayload>[]
        }
        delete: {
          args: Prisma.SesiPemesananDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SesiPemesananPayload>
        }
        update: {
          args: Prisma.SesiPemesananUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SesiPemesananPayload>
        }
        deleteMany: {
          args: Prisma.SesiPemesananDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SesiPemesananUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SesiPemesananUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SesiPemesananPayload>[]
        }
        upsert: {
          args: Prisma.SesiPemesananUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SesiPemesananPayload>
        }
        aggregate: {
          args: Prisma.SesiPemesananAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSesiPemesanan>
        }
        groupBy: {
          args: Prisma.SesiPemesananGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SesiPemesananGroupByOutputType>[]
        }
        count: {
          args: Prisma.SesiPemesananCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SesiPemesananCountAggregateOutputType> | number
        }
      }
    }
    Meja: {
      payload: Prisma.$MejaPayload<ExtArgs>
      fields: Prisma.MejaFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MejaFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MejaPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MejaFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MejaPayload>
        }
        findFirst: {
          args: Prisma.MejaFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MejaPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MejaFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MejaPayload>
        }
        findMany: {
          args: Prisma.MejaFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MejaPayload>[]
        }
        create: {
          args: Prisma.MejaCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MejaPayload>
        }
        createMany: {
          args: Prisma.MejaCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.MejaCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MejaPayload>[]
        }
        delete: {
          args: Prisma.MejaDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MejaPayload>
        }
        update: {
          args: Prisma.MejaUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MejaPayload>
        }
        deleteMany: {
          args: Prisma.MejaDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MejaUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.MejaUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MejaPayload>[]
        }
        upsert: {
          args: Prisma.MejaUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MejaPayload>
        }
        aggregate: {
          args: Prisma.MejaAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMeja>
        }
        groupBy: {
          args: Prisma.MejaGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MejaGroupByOutputType>[]
        }
        count: {
          args: Prisma.MejaCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MejaCountAggregateOutputType> | number
        }
      }
    }
    Item: {
      payload: Prisma.$ItemPayload<ExtArgs>
      fields: Prisma.ItemFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ItemFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ItemPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ItemFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ItemPayload>
        }
        findFirst: {
          args: Prisma.ItemFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ItemPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ItemFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ItemPayload>
        }
        findMany: {
          args: Prisma.ItemFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ItemPayload>[]
        }
        create: {
          args: Prisma.ItemCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ItemPayload>
        }
        createMany: {
          args: Prisma.ItemCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ItemCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ItemPayload>[]
        }
        delete: {
          args: Prisma.ItemDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ItemPayload>
        }
        update: {
          args: Prisma.ItemUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ItemPayload>
        }
        deleteMany: {
          args: Prisma.ItemDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ItemUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ItemUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ItemPayload>[]
        }
        upsert: {
          args: Prisma.ItemUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ItemPayload>
        }
        aggregate: {
          args: Prisma.ItemAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateItem>
        }
        groupBy: {
          args: Prisma.ItemGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ItemGroupByOutputType>[]
        }
        count: {
          args: Prisma.ItemCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ItemCountAggregateOutputType> | number
        }
      }
    }
    Transaksi: {
      payload: Prisma.$TransaksiPayload<ExtArgs>
      fields: Prisma.TransaksiFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TransaksiFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransaksiPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TransaksiFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransaksiPayload>
        }
        findFirst: {
          args: Prisma.TransaksiFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransaksiPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TransaksiFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransaksiPayload>
        }
        findMany: {
          args: Prisma.TransaksiFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransaksiPayload>[]
        }
        create: {
          args: Prisma.TransaksiCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransaksiPayload>
        }
        createMany: {
          args: Prisma.TransaksiCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TransaksiCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransaksiPayload>[]
        }
        delete: {
          args: Prisma.TransaksiDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransaksiPayload>
        }
        update: {
          args: Prisma.TransaksiUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransaksiPayload>
        }
        deleteMany: {
          args: Prisma.TransaksiDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TransaksiUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TransaksiUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransaksiPayload>[]
        }
        upsert: {
          args: Prisma.TransaksiUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransaksiPayload>
        }
        aggregate: {
          args: Prisma.TransaksiAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTransaksi>
        }
        groupBy: {
          args: Prisma.TransaksiGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TransaksiGroupByOutputType>[]
        }
        count: {
          args: Prisma.TransaksiCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TransaksiCountAggregateOutputType> | number
        }
      }
    }
    AntrianOrder: {
      payload: Prisma.$AntrianOrderPayload<ExtArgs>
      fields: Prisma.AntrianOrderFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AntrianOrderFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AntrianOrderPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AntrianOrderFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AntrianOrderPayload>
        }
        findFirst: {
          args: Prisma.AntrianOrderFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AntrianOrderPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AntrianOrderFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AntrianOrderPayload>
        }
        findMany: {
          args: Prisma.AntrianOrderFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AntrianOrderPayload>[]
        }
        create: {
          args: Prisma.AntrianOrderCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AntrianOrderPayload>
        }
        createMany: {
          args: Prisma.AntrianOrderCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AntrianOrderCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AntrianOrderPayload>[]
        }
        delete: {
          args: Prisma.AntrianOrderDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AntrianOrderPayload>
        }
        update: {
          args: Prisma.AntrianOrderUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AntrianOrderPayload>
        }
        deleteMany: {
          args: Prisma.AntrianOrderDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AntrianOrderUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AntrianOrderUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AntrianOrderPayload>[]
        }
        upsert: {
          args: Prisma.AntrianOrderUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AntrianOrderPayload>
        }
        aggregate: {
          args: Prisma.AntrianOrderAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAntrianOrder>
        }
        groupBy: {
          args: Prisma.AntrianOrderGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AntrianOrderGroupByOutputType>[]
        }
        count: {
          args: Prisma.AntrianOrderCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AntrianOrderCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const TokoScalarFieldEnum = {
  id_toko: 'id_toko',
  nama_toko: 'nama_toko',
  jenis_toko: 'jenis_toko'
} as const

export type TokoScalarFieldEnum = (typeof TokoScalarFieldEnum)[keyof typeof TokoScalarFieldEnum]


export const PelangganScalarFieldEnum = {
  id_pelanggan: 'id_pelanggan',
  nama_pembeli: 'nama_pembeli',
  password: 'password'
} as const

export type PelangganScalarFieldEnum = (typeof PelangganScalarFieldEnum)[keyof typeof PelangganScalarFieldEnum]


export const SesiPemesananScalarFieldEnum = {
  id_sesi: 'id_sesi',
  no_meja: 'no_meja',
  id_pelanggan: 'id_pelanggan',
  tanggal_pemesanan: 'tanggal_pemesanan',
  status_sesi: 'status_sesi'
} as const

export type SesiPemesananScalarFieldEnum = (typeof SesiPemesananScalarFieldEnum)[keyof typeof SesiPemesananScalarFieldEnum]


export const MejaScalarFieldEnum = {
  no_meja: 'no_meja',
  id_sesi: 'id_sesi',
  status_meja: 'status_meja'
} as const

export type MejaScalarFieldEnum = (typeof MejaScalarFieldEnum)[keyof typeof MejaScalarFieldEnum]


export const ItemScalarFieldEnum = {
  id_item: 'id_item',
  nama_item: 'nama_item',
  harga_item: 'harga_item',
  id_toko: 'id_toko'
} as const

export type ItemScalarFieldEnum = (typeof ItemScalarFieldEnum)[keyof typeof ItemScalarFieldEnum]


export const TransaksiScalarFieldEnum = {
  id_transaksi: 'id_transaksi',
  id_sesi: 'id_sesi',
  id_toko: 'id_toko',
  jenis_transaksi: 'jenis_transaksi',
  total_harga: 'total_harga',
  status_pesanan: 'status_pesanan',
  tanggal_transaksi: 'tanggal_transaksi'
} as const

export type TransaksiScalarFieldEnum = (typeof TransaksiScalarFieldEnum)[keyof typeof TransaksiScalarFieldEnum]


export const AntrianOrderScalarFieldEnum = {
  order_line: 'order_line',
  id_transaksi: 'id_transaksi',
  id_item: 'id_item',
  jumlah_item: 'jumlah_item',
  subtotal: 'subtotal'
} as const

export type AntrianOrderScalarFieldEnum = (typeof AntrianOrderScalarFieldEnum)[keyof typeof AntrianOrderScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'StatusSesi'
 */
export type EnumStatusSesiFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'StatusSesi'>
    


/**
 * Reference to a field of type 'StatusSesi[]'
 */
export type ListEnumStatusSesiFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'StatusSesi[]'>
    


/**
 * Reference to a field of type 'StatusMeja'
 */
export type EnumStatusMejaFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'StatusMeja'>
    


/**
 * Reference to a field of type 'StatusMeja[]'
 */
export type ListEnumStatusMejaFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'StatusMeja[]'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'JenisTransaksi'
 */
export type EnumJenisTransaksiFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'JenisTransaksi'>
    


/**
 * Reference to a field of type 'JenisTransaksi[]'
 */
export type ListEnumJenisTransaksiFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'JenisTransaksi[]'>
    


/**
 * Reference to a field of type 'Decimal'
 */
export type DecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal'>
    


/**
 * Reference to a field of type 'Decimal[]'
 */
export type ListDecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal[]'>
    


/**
 * Reference to a field of type 'StatusPesanan'
 */
export type EnumStatusPesananFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'StatusPesanan'>
    


/**
 * Reference to a field of type 'StatusPesanan[]'
 */
export type ListEnumStatusPesananFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'StatusPesanan[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  toko?: Prisma.TokoOmit
  pelanggan?: Prisma.PelangganOmit
  sesiPemesanan?: Prisma.SesiPemesananOmit
  meja?: Prisma.MejaOmit
  item?: Prisma.ItemOmit
  transaksi?: Prisma.TransaksiOmit
  antrianOrder?: Prisma.AntrianOrderOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

