
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AntrianOrder` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AntrianOrder
 * 
 */
export type AntrianOrderModel = runtime.Types.Result.DefaultSelection<Prisma.$AntrianOrderPayload>

export type AggregateAntrianOrder = {
  _count: AntrianOrderCountAggregateOutputType | null
  _avg: AntrianOrderAvgAggregateOutputType | null
  _sum: AntrianOrderSumAggregateOutputType | null
  _min: AntrianOrderMinAggregateOutputType | null
  _max: AntrianOrderMaxAggregateOutputType | null
}

export type AntrianOrderAvgAggregateOutputType = {
  jumlah_item: number | null
  subtotal: runtime.Decimal | null
}

export type AntrianOrderSumAggregateOutputType = {
  jumlah_item: number | null
  subtotal: runtime.Decimal | null
}

export type AntrianOrderMinAggregateOutputType = {
  order_line: string | null
  id_transaksi: string | null
  id_item: string | null
  jumlah_item: number | null
  subtotal: runtime.Decimal | null
}

export type AntrianOrderMaxAggregateOutputType = {
  order_line: string | null
  id_transaksi: string | null
  id_item: string | null
  jumlah_item: number | null
  subtotal: runtime.Decimal | null
}

export type AntrianOrderCountAggregateOutputType = {
  order_line: number
  id_transaksi: number
  id_item: number
  jumlah_item: number
  subtotal: number
  _all: number
}


export type AntrianOrderAvgAggregateInputType = {
  jumlah_item?: true
  subtotal?: true
}

export type AntrianOrderSumAggregateInputType = {
  jumlah_item?: true
  subtotal?: true
}

export type AntrianOrderMinAggregateInputType = {
  order_line?: true
  id_transaksi?: true
  id_item?: true
  jumlah_item?: true
  subtotal?: true
}

export type AntrianOrderMaxAggregateInputType = {
  order_line?: true
  id_transaksi?: true
  id_item?: true
  jumlah_item?: true
  subtotal?: true
}

export type AntrianOrderCountAggregateInputType = {
  order_line?: true
  id_transaksi?: true
  id_item?: true
  jumlah_item?: true
  subtotal?: true
  _all?: true
}

export type AntrianOrderAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AntrianOrder to aggregate.
   */
  where?: Prisma.AntrianOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AntrianOrders to fetch.
   */
  orderBy?: Prisma.AntrianOrderOrderByWithRelationInput | Prisma.AntrianOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AntrianOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AntrianOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AntrianOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AntrianOrders
  **/
  _count?: true | AntrianOrderCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AntrianOrderAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AntrianOrderSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AntrianOrderMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AntrianOrderMaxAggregateInputType
}

export type GetAntrianOrderAggregateType<T extends AntrianOrderAggregateArgs> = {
      [P in keyof T & keyof AggregateAntrianOrder]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAntrianOrder[P]>
    : Prisma.GetScalarType<T[P], AggregateAntrianOrder[P]>
}




export type AntrianOrderGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AntrianOrderWhereInput
  orderBy?: Prisma.AntrianOrderOrderByWithAggregationInput | Prisma.AntrianOrderOrderByWithAggregationInput[]
  by: Prisma.AntrianOrderScalarFieldEnum[] | Prisma.AntrianOrderScalarFieldEnum
  having?: Prisma.AntrianOrderScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AntrianOrderCountAggregateInputType | true
  _avg?: AntrianOrderAvgAggregateInputType
  _sum?: AntrianOrderSumAggregateInputType
  _min?: AntrianOrderMinAggregateInputType
  _max?: AntrianOrderMaxAggregateInputType
}

export type AntrianOrderGroupByOutputType = {
  order_line: string
  id_transaksi: string | null
  id_item: string | null
  jumlah_item: number | null
  subtotal: runtime.Decimal | null
  _count: AntrianOrderCountAggregateOutputType | null
  _avg: AntrianOrderAvgAggregateOutputType | null
  _sum: AntrianOrderSumAggregateOutputType | null
  _min: AntrianOrderMinAggregateOutputType | null
  _max: AntrianOrderMaxAggregateOutputType | null
}

type GetAntrianOrderGroupByPayload<T extends AntrianOrderGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AntrianOrderGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AntrianOrderGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AntrianOrderGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AntrianOrderGroupByOutputType[P]>
      }
    >
  >



export type AntrianOrderWhereInput = {
  AND?: Prisma.AntrianOrderWhereInput | Prisma.AntrianOrderWhereInput[]
  OR?: Prisma.AntrianOrderWhereInput[]
  NOT?: Prisma.AntrianOrderWhereInput | Prisma.AntrianOrderWhereInput[]
  order_line?: Prisma.StringFilter<"AntrianOrder"> | string
  id_transaksi?: Prisma.StringNullableFilter<"AntrianOrder"> | string | null
  id_item?: Prisma.StringNullableFilter<"AntrianOrder"> | string | null
  jumlah_item?: Prisma.IntNullableFilter<"AntrianOrder"> | number | null
  subtotal?: Prisma.DecimalNullableFilter<"AntrianOrder"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  transaksi?: Prisma.XOR<Prisma.TransaksiNullableScalarRelationFilter, Prisma.TransaksiWhereInput> | null
  item?: Prisma.XOR<Prisma.ItemNullableScalarRelationFilter, Prisma.ItemWhereInput> | null
}

export type AntrianOrderOrderByWithRelationInput = {
  order_line?: Prisma.SortOrder
  id_transaksi?: Prisma.SortOrderInput | Prisma.SortOrder
  id_item?: Prisma.SortOrderInput | Prisma.SortOrder
  jumlah_item?: Prisma.SortOrderInput | Prisma.SortOrder
  subtotal?: Prisma.SortOrderInput | Prisma.SortOrder
  transaksi?: Prisma.TransaksiOrderByWithRelationInput
  item?: Prisma.ItemOrderByWithRelationInput
}

export type AntrianOrderWhereUniqueInput = Prisma.AtLeast<{
  order_line?: string
  AND?: Prisma.AntrianOrderWhereInput | Prisma.AntrianOrderWhereInput[]
  OR?: Prisma.AntrianOrderWhereInput[]
  NOT?: Prisma.AntrianOrderWhereInput | Prisma.AntrianOrderWhereInput[]
  id_transaksi?: Prisma.StringNullableFilter<"AntrianOrder"> | string | null
  id_item?: Prisma.StringNullableFilter<"AntrianOrder"> | string | null
  jumlah_item?: Prisma.IntNullableFilter<"AntrianOrder"> | number | null
  subtotal?: Prisma.DecimalNullableFilter<"AntrianOrder"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  transaksi?: Prisma.XOR<Prisma.TransaksiNullableScalarRelationFilter, Prisma.TransaksiWhereInput> | null
  item?: Prisma.XOR<Prisma.ItemNullableScalarRelationFilter, Prisma.ItemWhereInput> | null
}, "order_line">

export type AntrianOrderOrderByWithAggregationInput = {
  order_line?: Prisma.SortOrder
  id_transaksi?: Prisma.SortOrderInput | Prisma.SortOrder
  id_item?: Prisma.SortOrderInput | Prisma.SortOrder
  jumlah_item?: Prisma.SortOrderInput | Prisma.SortOrder
  subtotal?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.AntrianOrderCountOrderByAggregateInput
  _avg?: Prisma.AntrianOrderAvgOrderByAggregateInput
  _max?: Prisma.AntrianOrderMaxOrderByAggregateInput
  _min?: Prisma.AntrianOrderMinOrderByAggregateInput
  _sum?: Prisma.AntrianOrderSumOrderByAggregateInput
}

export type AntrianOrderScalarWhereWithAggregatesInput = {
  AND?: Prisma.AntrianOrderScalarWhereWithAggregatesInput | Prisma.AntrianOrderScalarWhereWithAggregatesInput[]
  OR?: Prisma.AntrianOrderScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AntrianOrderScalarWhereWithAggregatesInput | Prisma.AntrianOrderScalarWhereWithAggregatesInput[]
  order_line?: Prisma.StringWithAggregatesFilter<"AntrianOrder"> | string
  id_transaksi?: Prisma.StringNullableWithAggregatesFilter<"AntrianOrder"> | string | null
  id_item?: Prisma.StringNullableWithAggregatesFilter<"AntrianOrder"> | string | null
  jumlah_item?: Prisma.IntNullableWithAggregatesFilter<"AntrianOrder"> | number | null
  subtotal?: Prisma.DecimalNullableWithAggregatesFilter<"AntrianOrder"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
}

export type AntrianOrderCreateInput = {
  order_line: string
  jumlah_item?: number | null
  subtotal?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  transaksi?: Prisma.TransaksiCreateNestedOneWithoutAntrianInput
  item?: Prisma.ItemCreateNestedOneWithoutAntrianInput
}

export type AntrianOrderUncheckedCreateInput = {
  order_line: string
  id_transaksi?: string | null
  id_item?: string | null
  jumlah_item?: number | null
  subtotal?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
}

export type AntrianOrderUpdateInput = {
  order_line?: Prisma.StringFieldUpdateOperationsInput | string
  jumlah_item?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  subtotal?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  transaksi?: Prisma.TransaksiUpdateOneWithoutAntrianNestedInput
  item?: Prisma.ItemUpdateOneWithoutAntrianNestedInput
}

export type AntrianOrderUncheckedUpdateInput = {
  order_line?: Prisma.StringFieldUpdateOperationsInput | string
  id_transaksi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  id_item?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jumlah_item?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  subtotal?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
}

export type AntrianOrderCreateManyInput = {
  order_line: string
  id_transaksi?: string | null
  id_item?: string | null
  jumlah_item?: number | null
  subtotal?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
}

export type AntrianOrderUpdateManyMutationInput = {
  order_line?: Prisma.StringFieldUpdateOperationsInput | string
  jumlah_item?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  subtotal?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
}

export type AntrianOrderUncheckedUpdateManyInput = {
  order_line?: Prisma.StringFieldUpdateOperationsInput | string
  id_transaksi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  id_item?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jumlah_item?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  subtotal?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
}

export type AntrianOrderListRelationFilter = {
  every?: Prisma.AntrianOrderWhereInput
  some?: Prisma.AntrianOrderWhereInput
  none?: Prisma.AntrianOrderWhereInput
}

export type AntrianOrderOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AntrianOrderCountOrderByAggregateInput = {
  order_line?: Prisma.SortOrder
  id_transaksi?: Prisma.SortOrder
  id_item?: Prisma.SortOrder
  jumlah_item?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
}

export type AntrianOrderAvgOrderByAggregateInput = {
  jumlah_item?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
}

export type AntrianOrderMaxOrderByAggregateInput = {
  order_line?: Prisma.SortOrder
  id_transaksi?: Prisma.SortOrder
  id_item?: Prisma.SortOrder
  jumlah_item?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
}

export type AntrianOrderMinOrderByAggregateInput = {
  order_line?: Prisma.SortOrder
  id_transaksi?: Prisma.SortOrder
  id_item?: Prisma.SortOrder
  jumlah_item?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
}

export type AntrianOrderSumOrderByAggregateInput = {
  jumlah_item?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
}

export type AntrianOrderCreateNestedManyWithoutItemInput = {
  create?: Prisma.XOR<Prisma.AntrianOrderCreateWithoutItemInput, Prisma.AntrianOrderUncheckedCreateWithoutItemInput> | Prisma.AntrianOrderCreateWithoutItemInput[] | Prisma.AntrianOrderUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.AntrianOrderCreateOrConnectWithoutItemInput | Prisma.AntrianOrderCreateOrConnectWithoutItemInput[]
  createMany?: Prisma.AntrianOrderCreateManyItemInputEnvelope
  connect?: Prisma.AntrianOrderWhereUniqueInput | Prisma.AntrianOrderWhereUniqueInput[]
}

export type AntrianOrderUncheckedCreateNestedManyWithoutItemInput = {
  create?: Prisma.XOR<Prisma.AntrianOrderCreateWithoutItemInput, Prisma.AntrianOrderUncheckedCreateWithoutItemInput> | Prisma.AntrianOrderCreateWithoutItemInput[] | Prisma.AntrianOrderUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.AntrianOrderCreateOrConnectWithoutItemInput | Prisma.AntrianOrderCreateOrConnectWithoutItemInput[]
  createMany?: Prisma.AntrianOrderCreateManyItemInputEnvelope
  connect?: Prisma.AntrianOrderWhereUniqueInput | Prisma.AntrianOrderWhereUniqueInput[]
}

export type AntrianOrderUpdateManyWithoutItemNestedInput = {
  create?: Prisma.XOR<Prisma.AntrianOrderCreateWithoutItemInput, Prisma.AntrianOrderUncheckedCreateWithoutItemInput> | Prisma.AntrianOrderCreateWithoutItemInput[] | Prisma.AntrianOrderUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.AntrianOrderCreateOrConnectWithoutItemInput | Prisma.AntrianOrderCreateOrConnectWithoutItemInput[]
  upsert?: Prisma.AntrianOrderUpsertWithWhereUniqueWithoutItemInput | Prisma.AntrianOrderUpsertWithWhereUniqueWithoutItemInput[]
  createMany?: Prisma.AntrianOrderCreateManyItemInputEnvelope
  set?: Prisma.AntrianOrderWhereUniqueInput | Prisma.AntrianOrderWhereUniqueInput[]
  disconnect?: Prisma.AntrianOrderWhereUniqueInput | Prisma.AntrianOrderWhereUniqueInput[]
  delete?: Prisma.AntrianOrderWhereUniqueInput | Prisma.AntrianOrderWhereUniqueInput[]
  connect?: Prisma.AntrianOrderWhereUniqueInput | Prisma.AntrianOrderWhereUniqueInput[]
  update?: Prisma.AntrianOrderUpdateWithWhereUniqueWithoutItemInput | Prisma.AntrianOrderUpdateWithWhereUniqueWithoutItemInput[]
  updateMany?: Prisma.AntrianOrderUpdateManyWithWhereWithoutItemInput | Prisma.AntrianOrderUpdateManyWithWhereWithoutItemInput[]
  deleteMany?: Prisma.AntrianOrderScalarWhereInput | Prisma.AntrianOrderScalarWhereInput[]
}

export type AntrianOrderUncheckedUpdateManyWithoutItemNestedInput = {
  create?: Prisma.XOR<Prisma.AntrianOrderCreateWithoutItemInput, Prisma.AntrianOrderUncheckedCreateWithoutItemInput> | Prisma.AntrianOrderCreateWithoutItemInput[] | Prisma.AntrianOrderUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.AntrianOrderCreateOrConnectWithoutItemInput | Prisma.AntrianOrderCreateOrConnectWithoutItemInput[]
  upsert?: Prisma.AntrianOrderUpsertWithWhereUniqueWithoutItemInput | Prisma.AntrianOrderUpsertWithWhereUniqueWithoutItemInput[]
  createMany?: Prisma.AntrianOrderCreateManyItemInputEnvelope
  set?: Prisma.AntrianOrderWhereUniqueInput | Prisma.AntrianOrderWhereUniqueInput[]
  disconnect?: Prisma.AntrianOrderWhereUniqueInput | Prisma.AntrianOrderWhereUniqueInput[]
  delete?: Prisma.AntrianOrderWhereUniqueInput | Prisma.AntrianOrderWhereUniqueInput[]
  connect?: Prisma.AntrianOrderWhereUniqueInput | Prisma.AntrianOrderWhereUniqueInput[]
  update?: Prisma.AntrianOrderUpdateWithWhereUniqueWithoutItemInput | Prisma.AntrianOrderUpdateWithWhereUniqueWithoutItemInput[]
  updateMany?: Prisma.AntrianOrderUpdateManyWithWhereWithoutItemInput | Prisma.AntrianOrderUpdateManyWithWhereWithoutItemInput[]
  deleteMany?: Prisma.AntrianOrderScalarWhereInput | Prisma.AntrianOrderScalarWhereInput[]
}

export type AntrianOrderCreateNestedManyWithoutTransaksiInput = {
  create?: Prisma.XOR<Prisma.AntrianOrderCreateWithoutTransaksiInput, Prisma.AntrianOrderUncheckedCreateWithoutTransaksiInput> | Prisma.AntrianOrderCreateWithoutTransaksiInput[] | Prisma.AntrianOrderUncheckedCreateWithoutTransaksiInput[]
  connectOrCreate?: Prisma.AntrianOrderCreateOrConnectWithoutTransaksiInput | Prisma.AntrianOrderCreateOrConnectWithoutTransaksiInput[]
  createMany?: Prisma.AntrianOrderCreateManyTransaksiInputEnvelope
  connect?: Prisma.AntrianOrderWhereUniqueInput | Prisma.AntrianOrderWhereUniqueInput[]
}

export type AntrianOrderUncheckedCreateNestedManyWithoutTransaksiInput = {
  create?: Prisma.XOR<Prisma.AntrianOrderCreateWithoutTransaksiInput, Prisma.AntrianOrderUncheckedCreateWithoutTransaksiInput> | Prisma.AntrianOrderCreateWithoutTransaksiInput[] | Prisma.AntrianOrderUncheckedCreateWithoutTransaksiInput[]
  connectOrCreate?: Prisma.AntrianOrderCreateOrConnectWithoutTransaksiInput | Prisma.AntrianOrderCreateOrConnectWithoutTransaksiInput[]
  createMany?: Prisma.AntrianOrderCreateManyTransaksiInputEnvelope
  connect?: Prisma.AntrianOrderWhereUniqueInput | Prisma.AntrianOrderWhereUniqueInput[]
}

export type AntrianOrderUpdateManyWithoutTransaksiNestedInput = {
  create?: Prisma.XOR<Prisma.AntrianOrderCreateWithoutTransaksiInput, Prisma.AntrianOrderUncheckedCreateWithoutTransaksiInput> | Prisma.AntrianOrderCreateWithoutTransaksiInput[] | Prisma.AntrianOrderUncheckedCreateWithoutTransaksiInput[]
  connectOrCreate?: Prisma.AntrianOrderCreateOrConnectWithoutTransaksiInput | Prisma.AntrianOrderCreateOrConnectWithoutTransaksiInput[]
  upsert?: Prisma.AntrianOrderUpsertWithWhereUniqueWithoutTransaksiInput | Prisma.AntrianOrderUpsertWithWhereUniqueWithoutTransaksiInput[]
  createMany?: Prisma.AntrianOrderCreateManyTransaksiInputEnvelope
  set?: Prisma.AntrianOrderWhereUniqueInput | Prisma.AntrianOrderWhereUniqueInput[]
  disconnect?: Prisma.AntrianOrderWhereUniqueInput | Prisma.AntrianOrderWhereUniqueInput[]
  delete?: Prisma.AntrianOrderWhereUniqueInput | Prisma.AntrianOrderWhereUniqueInput[]
  connect?: Prisma.AntrianOrderWhereUniqueInput | Prisma.AntrianOrderWhereUniqueInput[]
  update?: Prisma.AntrianOrderUpdateWithWhereUniqueWithoutTransaksiInput | Prisma.AntrianOrderUpdateWithWhereUniqueWithoutTransaksiInput[]
  updateMany?: Prisma.AntrianOrderUpdateManyWithWhereWithoutTransaksiInput | Prisma.AntrianOrderUpdateManyWithWhereWithoutTransaksiInput[]
  deleteMany?: Prisma.AntrianOrderScalarWhereInput | Prisma.AntrianOrderScalarWhereInput[]
}

export type AntrianOrderUncheckedUpdateManyWithoutTransaksiNestedInput = {
  create?: Prisma.XOR<Prisma.AntrianOrderCreateWithoutTransaksiInput, Prisma.AntrianOrderUncheckedCreateWithoutTransaksiInput> | Prisma.AntrianOrderCreateWithoutTransaksiInput[] | Prisma.AntrianOrderUncheckedCreateWithoutTransaksiInput[]
  connectOrCreate?: Prisma.AntrianOrderCreateOrConnectWithoutTransaksiInput | Prisma.AntrianOrderCreateOrConnectWithoutTransaksiInput[]
  upsert?: Prisma.AntrianOrderUpsertWithWhereUniqueWithoutTransaksiInput | Prisma.AntrianOrderUpsertWithWhereUniqueWithoutTransaksiInput[]
  createMany?: Prisma.AntrianOrderCreateManyTransaksiInputEnvelope
  set?: Prisma.AntrianOrderWhereUniqueInput | Prisma.AntrianOrderWhereUniqueInput[]
  disconnect?: Prisma.AntrianOrderWhereUniqueInput | Prisma.AntrianOrderWhereUniqueInput[]
  delete?: Prisma.AntrianOrderWhereUniqueInput | Prisma.AntrianOrderWhereUniqueInput[]
  connect?: Prisma.AntrianOrderWhereUniqueInput | Prisma.AntrianOrderWhereUniqueInput[]
  update?: Prisma.AntrianOrderUpdateWithWhereUniqueWithoutTransaksiInput | Prisma.AntrianOrderUpdateWithWhereUniqueWithoutTransaksiInput[]
  updateMany?: Prisma.AntrianOrderUpdateManyWithWhereWithoutTransaksiInput | Prisma.AntrianOrderUpdateManyWithWhereWithoutTransaksiInput[]
  deleteMany?: Prisma.AntrianOrderScalarWhereInput | Prisma.AntrianOrderScalarWhereInput[]
}

export type AntrianOrderCreateWithoutItemInput = {
  order_line: string
  jumlah_item?: number | null
  subtotal?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  transaksi?: Prisma.TransaksiCreateNestedOneWithoutAntrianInput
}

export type AntrianOrderUncheckedCreateWithoutItemInput = {
  order_line: string
  id_transaksi?: string | null
  jumlah_item?: number | null
  subtotal?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
}

export type AntrianOrderCreateOrConnectWithoutItemInput = {
  where: Prisma.AntrianOrderWhereUniqueInput
  create: Prisma.XOR<Prisma.AntrianOrderCreateWithoutItemInput, Prisma.AntrianOrderUncheckedCreateWithoutItemInput>
}

export type AntrianOrderCreateManyItemInputEnvelope = {
  data: Prisma.AntrianOrderCreateManyItemInput | Prisma.AntrianOrderCreateManyItemInput[]
  skipDuplicates?: boolean
}

export type AntrianOrderUpsertWithWhereUniqueWithoutItemInput = {
  where: Prisma.AntrianOrderWhereUniqueInput
  update: Prisma.XOR<Prisma.AntrianOrderUpdateWithoutItemInput, Prisma.AntrianOrderUncheckedUpdateWithoutItemInput>
  create: Prisma.XOR<Prisma.AntrianOrderCreateWithoutItemInput, Prisma.AntrianOrderUncheckedCreateWithoutItemInput>
}

export type AntrianOrderUpdateWithWhereUniqueWithoutItemInput = {
  where: Prisma.AntrianOrderWhereUniqueInput
  data: Prisma.XOR<Prisma.AntrianOrderUpdateWithoutItemInput, Prisma.AntrianOrderUncheckedUpdateWithoutItemInput>
}

export type AntrianOrderUpdateManyWithWhereWithoutItemInput = {
  where: Prisma.AntrianOrderScalarWhereInput
  data: Prisma.XOR<Prisma.AntrianOrderUpdateManyMutationInput, Prisma.AntrianOrderUncheckedUpdateManyWithoutItemInput>
}

export type AntrianOrderScalarWhereInput = {
  AND?: Prisma.AntrianOrderScalarWhereInput | Prisma.AntrianOrderScalarWhereInput[]
  OR?: Prisma.AntrianOrderScalarWhereInput[]
  NOT?: Prisma.AntrianOrderScalarWhereInput | Prisma.AntrianOrderScalarWhereInput[]
  order_line?: Prisma.StringFilter<"AntrianOrder"> | string
  id_transaksi?: Prisma.StringNullableFilter<"AntrianOrder"> | string | null
  id_item?: Prisma.StringNullableFilter<"AntrianOrder"> | string | null
  jumlah_item?: Prisma.IntNullableFilter<"AntrianOrder"> | number | null
  subtotal?: Prisma.DecimalNullableFilter<"AntrianOrder"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
}

export type AntrianOrderCreateWithoutTransaksiInput = {
  order_line: string
  jumlah_item?: number | null
  subtotal?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  item?: Prisma.ItemCreateNestedOneWithoutAntrianInput
}

export type AntrianOrderUncheckedCreateWithoutTransaksiInput = {
  order_line: string
  id_item?: string | null
  jumlah_item?: number | null
  subtotal?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
}

export type AntrianOrderCreateOrConnectWithoutTransaksiInput = {
  where: Prisma.AntrianOrderWhereUniqueInput
  create: Prisma.XOR<Prisma.AntrianOrderCreateWithoutTransaksiInput, Prisma.AntrianOrderUncheckedCreateWithoutTransaksiInput>
}

export type AntrianOrderCreateManyTransaksiInputEnvelope = {
  data: Prisma.AntrianOrderCreateManyTransaksiInput | Prisma.AntrianOrderCreateManyTransaksiInput[]
  skipDuplicates?: boolean
}

export type AntrianOrderUpsertWithWhereUniqueWithoutTransaksiInput = {
  where: Prisma.AntrianOrderWhereUniqueInput
  update: Prisma.XOR<Prisma.AntrianOrderUpdateWithoutTransaksiInput, Prisma.AntrianOrderUncheckedUpdateWithoutTransaksiInput>
  create: Prisma.XOR<Prisma.AntrianOrderCreateWithoutTransaksiInput, Prisma.AntrianOrderUncheckedCreateWithoutTransaksiInput>
}

export type AntrianOrderUpdateWithWhereUniqueWithoutTransaksiInput = {
  where: Prisma.AntrianOrderWhereUniqueInput
  data: Prisma.XOR<Prisma.AntrianOrderUpdateWithoutTransaksiInput, Prisma.AntrianOrderUncheckedUpdateWithoutTransaksiInput>
}

export type AntrianOrderUpdateManyWithWhereWithoutTransaksiInput = {
  where: Prisma.AntrianOrderScalarWhereInput
  data: Prisma.XOR<Prisma.AntrianOrderUpdateManyMutationInput, Prisma.AntrianOrderUncheckedUpdateManyWithoutTransaksiInput>
}

export type AntrianOrderCreateManyItemInput = {
  order_line: string
  id_transaksi?: string | null
  jumlah_item?: number | null
  subtotal?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
}

export type AntrianOrderUpdateWithoutItemInput = {
  order_line?: Prisma.StringFieldUpdateOperationsInput | string
  jumlah_item?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  subtotal?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  transaksi?: Prisma.TransaksiUpdateOneWithoutAntrianNestedInput
}

export type AntrianOrderUncheckedUpdateWithoutItemInput = {
  order_line?: Prisma.StringFieldUpdateOperationsInput | string
  id_transaksi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jumlah_item?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  subtotal?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
}

export type AntrianOrderUncheckedUpdateManyWithoutItemInput = {
  order_line?: Prisma.StringFieldUpdateOperationsInput | string
  id_transaksi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jumlah_item?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  subtotal?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
}

export type AntrianOrderCreateManyTransaksiInput = {
  order_line: string
  id_item?: string | null
  jumlah_item?: number | null
  subtotal?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
}

export type AntrianOrderUpdateWithoutTransaksiInput = {
  order_line?: Prisma.StringFieldUpdateOperationsInput | string
  jumlah_item?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  subtotal?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  item?: Prisma.ItemUpdateOneWithoutAntrianNestedInput
}

export type AntrianOrderUncheckedUpdateWithoutTransaksiInput = {
  order_line?: Prisma.StringFieldUpdateOperationsInput | string
  id_item?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jumlah_item?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  subtotal?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
}

export type AntrianOrderUncheckedUpdateManyWithoutTransaksiInput = {
  order_line?: Prisma.StringFieldUpdateOperationsInput | string
  id_item?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jumlah_item?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  subtotal?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
}



export type AntrianOrderSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  order_line?: boolean
  id_transaksi?: boolean
  id_item?: boolean
  jumlah_item?: boolean
  subtotal?: boolean
  transaksi?: boolean | Prisma.AntrianOrder$transaksiArgs<ExtArgs>
  item?: boolean | Prisma.AntrianOrder$itemArgs<ExtArgs>
}, ExtArgs["result"]["antrianOrder"]>

export type AntrianOrderSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  order_line?: boolean
  id_transaksi?: boolean
  id_item?: boolean
  jumlah_item?: boolean
  subtotal?: boolean
  transaksi?: boolean | Prisma.AntrianOrder$transaksiArgs<ExtArgs>
  item?: boolean | Prisma.AntrianOrder$itemArgs<ExtArgs>
}, ExtArgs["result"]["antrianOrder"]>

export type AntrianOrderSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  order_line?: boolean
  id_transaksi?: boolean
  id_item?: boolean
  jumlah_item?: boolean
  subtotal?: boolean
  transaksi?: boolean | Prisma.AntrianOrder$transaksiArgs<ExtArgs>
  item?: boolean | Prisma.AntrianOrder$itemArgs<ExtArgs>
}, ExtArgs["result"]["antrianOrder"]>

export type AntrianOrderSelectScalar = {
  order_line?: boolean
  id_transaksi?: boolean
  id_item?: boolean
  jumlah_item?: boolean
  subtotal?: boolean
}

export type AntrianOrderOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"order_line" | "id_transaksi" | "id_item" | "jumlah_item" | "subtotal", ExtArgs["result"]["antrianOrder"]>
export type AntrianOrderInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  transaksi?: boolean | Prisma.AntrianOrder$transaksiArgs<ExtArgs>
  item?: boolean | Prisma.AntrianOrder$itemArgs<ExtArgs>
}
export type AntrianOrderIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  transaksi?: boolean | Prisma.AntrianOrder$transaksiArgs<ExtArgs>
  item?: boolean | Prisma.AntrianOrder$itemArgs<ExtArgs>
}
export type AntrianOrderIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  transaksi?: boolean | Prisma.AntrianOrder$transaksiArgs<ExtArgs>
  item?: boolean | Prisma.AntrianOrder$itemArgs<ExtArgs>
}

export type $AntrianOrderPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AntrianOrder"
  objects: {
    transaksi: Prisma.$TransaksiPayload<ExtArgs> | null
    item: Prisma.$ItemPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    order_line: string
    id_transaksi: string | null
    id_item: string | null
    jumlah_item: number | null
    subtotal: runtime.Decimal | null
  }, ExtArgs["result"]["antrianOrder"]>
  composites: {}
}

export type AntrianOrderGetPayload<S extends boolean | null | undefined | AntrianOrderDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AntrianOrderPayload, S>

export type AntrianOrderCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AntrianOrderFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AntrianOrderCountAggregateInputType | true
  }

export interface AntrianOrderDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AntrianOrder'], meta: { name: 'AntrianOrder' } }
  /**
   * Find zero or one AntrianOrder that matches the filter.
   * @param {AntrianOrderFindUniqueArgs} args - Arguments to find a AntrianOrder
   * @example
   * // Get one AntrianOrder
   * const antrianOrder = await prisma.antrianOrder.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AntrianOrderFindUniqueArgs>(args: Prisma.SelectSubset<T, AntrianOrderFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AntrianOrderClient<runtime.Types.Result.GetResult<Prisma.$AntrianOrderPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AntrianOrder that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AntrianOrderFindUniqueOrThrowArgs} args - Arguments to find a AntrianOrder
   * @example
   * // Get one AntrianOrder
   * const antrianOrder = await prisma.antrianOrder.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AntrianOrderFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AntrianOrderFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AntrianOrderClient<runtime.Types.Result.GetResult<Prisma.$AntrianOrderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AntrianOrder that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AntrianOrderFindFirstArgs} args - Arguments to find a AntrianOrder
   * @example
   * // Get one AntrianOrder
   * const antrianOrder = await prisma.antrianOrder.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AntrianOrderFindFirstArgs>(args?: Prisma.SelectSubset<T, AntrianOrderFindFirstArgs<ExtArgs>>): Prisma.Prisma__AntrianOrderClient<runtime.Types.Result.GetResult<Prisma.$AntrianOrderPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AntrianOrder that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AntrianOrderFindFirstOrThrowArgs} args - Arguments to find a AntrianOrder
   * @example
   * // Get one AntrianOrder
   * const antrianOrder = await prisma.antrianOrder.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AntrianOrderFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AntrianOrderFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AntrianOrderClient<runtime.Types.Result.GetResult<Prisma.$AntrianOrderPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AntrianOrders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AntrianOrderFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AntrianOrders
   * const antrianOrders = await prisma.antrianOrder.findMany()
   * 
   * // Get first 10 AntrianOrders
   * const antrianOrders = await prisma.antrianOrder.findMany({ take: 10 })
   * 
   * // Only select the `order_line`
   * const antrianOrderWithOrder_lineOnly = await prisma.antrianOrder.findMany({ select: { order_line: true } })
   * 
   */
  findMany<T extends AntrianOrderFindManyArgs>(args?: Prisma.SelectSubset<T, AntrianOrderFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AntrianOrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AntrianOrder.
   * @param {AntrianOrderCreateArgs} args - Arguments to create a AntrianOrder.
   * @example
   * // Create one AntrianOrder
   * const AntrianOrder = await prisma.antrianOrder.create({
   *   data: {
   *     // ... data to create a AntrianOrder
   *   }
   * })
   * 
   */
  create<T extends AntrianOrderCreateArgs>(args: Prisma.SelectSubset<T, AntrianOrderCreateArgs<ExtArgs>>): Prisma.Prisma__AntrianOrderClient<runtime.Types.Result.GetResult<Prisma.$AntrianOrderPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AntrianOrders.
   * @param {AntrianOrderCreateManyArgs} args - Arguments to create many AntrianOrders.
   * @example
   * // Create many AntrianOrders
   * const antrianOrder = await prisma.antrianOrder.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AntrianOrderCreateManyArgs>(args?: Prisma.SelectSubset<T, AntrianOrderCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AntrianOrders and returns the data saved in the database.
   * @param {AntrianOrderCreateManyAndReturnArgs} args - Arguments to create many AntrianOrders.
   * @example
   * // Create many AntrianOrders
   * const antrianOrder = await prisma.antrianOrder.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AntrianOrders and only return the `order_line`
   * const antrianOrderWithOrder_lineOnly = await prisma.antrianOrder.createManyAndReturn({
   *   select: { order_line: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AntrianOrderCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AntrianOrderCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AntrianOrderPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AntrianOrder.
   * @param {AntrianOrderDeleteArgs} args - Arguments to delete one AntrianOrder.
   * @example
   * // Delete one AntrianOrder
   * const AntrianOrder = await prisma.antrianOrder.delete({
   *   where: {
   *     // ... filter to delete one AntrianOrder
   *   }
   * })
   * 
   */
  delete<T extends AntrianOrderDeleteArgs>(args: Prisma.SelectSubset<T, AntrianOrderDeleteArgs<ExtArgs>>): Prisma.Prisma__AntrianOrderClient<runtime.Types.Result.GetResult<Prisma.$AntrianOrderPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AntrianOrder.
   * @param {AntrianOrderUpdateArgs} args - Arguments to update one AntrianOrder.
   * @example
   * // Update one AntrianOrder
   * const antrianOrder = await prisma.antrianOrder.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AntrianOrderUpdateArgs>(args: Prisma.SelectSubset<T, AntrianOrderUpdateArgs<ExtArgs>>): Prisma.Prisma__AntrianOrderClient<runtime.Types.Result.GetResult<Prisma.$AntrianOrderPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AntrianOrders.
   * @param {AntrianOrderDeleteManyArgs} args - Arguments to filter AntrianOrders to delete.
   * @example
   * // Delete a few AntrianOrders
   * const { count } = await prisma.antrianOrder.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AntrianOrderDeleteManyArgs>(args?: Prisma.SelectSubset<T, AntrianOrderDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AntrianOrders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AntrianOrderUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AntrianOrders
   * const antrianOrder = await prisma.antrianOrder.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AntrianOrderUpdateManyArgs>(args: Prisma.SelectSubset<T, AntrianOrderUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AntrianOrders and returns the data updated in the database.
   * @param {AntrianOrderUpdateManyAndReturnArgs} args - Arguments to update many AntrianOrders.
   * @example
   * // Update many AntrianOrders
   * const antrianOrder = await prisma.antrianOrder.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AntrianOrders and only return the `order_line`
   * const antrianOrderWithOrder_lineOnly = await prisma.antrianOrder.updateManyAndReturn({
   *   select: { order_line: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AntrianOrderUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AntrianOrderUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AntrianOrderPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AntrianOrder.
   * @param {AntrianOrderUpsertArgs} args - Arguments to update or create a AntrianOrder.
   * @example
   * // Update or create a AntrianOrder
   * const antrianOrder = await prisma.antrianOrder.upsert({
   *   create: {
   *     // ... data to create a AntrianOrder
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AntrianOrder we want to update
   *   }
   * })
   */
  upsert<T extends AntrianOrderUpsertArgs>(args: Prisma.SelectSubset<T, AntrianOrderUpsertArgs<ExtArgs>>): Prisma.Prisma__AntrianOrderClient<runtime.Types.Result.GetResult<Prisma.$AntrianOrderPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AntrianOrders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AntrianOrderCountArgs} args - Arguments to filter AntrianOrders to count.
   * @example
   * // Count the number of AntrianOrders
   * const count = await prisma.antrianOrder.count({
   *   where: {
   *     // ... the filter for the AntrianOrders we want to count
   *   }
   * })
  **/
  count<T extends AntrianOrderCountArgs>(
    args?: Prisma.Subset<T, AntrianOrderCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AntrianOrderCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AntrianOrder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AntrianOrderAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AntrianOrderAggregateArgs>(args: Prisma.Subset<T, AntrianOrderAggregateArgs>): Prisma.PrismaPromise<GetAntrianOrderAggregateType<T>>

  /**
   * Group by AntrianOrder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AntrianOrderGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AntrianOrderGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AntrianOrderGroupByArgs['orderBy'] }
      : { orderBy?: AntrianOrderGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AntrianOrderGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAntrianOrderGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AntrianOrder model
 */
readonly fields: AntrianOrderFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AntrianOrder.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AntrianOrderClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  transaksi<T extends Prisma.AntrianOrder$transaksiArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AntrianOrder$transaksiArgs<ExtArgs>>): Prisma.Prisma__TransaksiClient<runtime.Types.Result.GetResult<Prisma.$TransaksiPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  item<T extends Prisma.AntrianOrder$itemArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AntrianOrder$itemArgs<ExtArgs>>): Prisma.Prisma__ItemClient<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AntrianOrder model
 */
export interface AntrianOrderFieldRefs {
  readonly order_line: Prisma.FieldRef<"AntrianOrder", 'String'>
  readonly id_transaksi: Prisma.FieldRef<"AntrianOrder", 'String'>
  readonly id_item: Prisma.FieldRef<"AntrianOrder", 'String'>
  readonly jumlah_item: Prisma.FieldRef<"AntrianOrder", 'Int'>
  readonly subtotal: Prisma.FieldRef<"AntrianOrder", 'Decimal'>
}
    

// Custom InputTypes
/**
 * AntrianOrder findUnique
 */
export type AntrianOrderFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AntrianOrder
   */
  select?: Prisma.AntrianOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AntrianOrder
   */
  omit?: Prisma.AntrianOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AntrianOrderInclude<ExtArgs> | null
  /**
   * Filter, which AntrianOrder to fetch.
   */
  where: Prisma.AntrianOrderWhereUniqueInput
}

/**
 * AntrianOrder findUniqueOrThrow
 */
export type AntrianOrderFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AntrianOrder
   */
  select?: Prisma.AntrianOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AntrianOrder
   */
  omit?: Prisma.AntrianOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AntrianOrderInclude<ExtArgs> | null
  /**
   * Filter, which AntrianOrder to fetch.
   */
  where: Prisma.AntrianOrderWhereUniqueInput
}

/**
 * AntrianOrder findFirst
 */
export type AntrianOrderFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AntrianOrder
   */
  select?: Prisma.AntrianOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AntrianOrder
   */
  omit?: Prisma.AntrianOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AntrianOrderInclude<ExtArgs> | null
  /**
   * Filter, which AntrianOrder to fetch.
   */
  where?: Prisma.AntrianOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AntrianOrders to fetch.
   */
  orderBy?: Prisma.AntrianOrderOrderByWithRelationInput | Prisma.AntrianOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AntrianOrders.
   */
  cursor?: Prisma.AntrianOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AntrianOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AntrianOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AntrianOrders.
   */
  distinct?: Prisma.AntrianOrderScalarFieldEnum | Prisma.AntrianOrderScalarFieldEnum[]
}

/**
 * AntrianOrder findFirstOrThrow
 */
export type AntrianOrderFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AntrianOrder
   */
  select?: Prisma.AntrianOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AntrianOrder
   */
  omit?: Prisma.AntrianOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AntrianOrderInclude<ExtArgs> | null
  /**
   * Filter, which AntrianOrder to fetch.
   */
  where?: Prisma.AntrianOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AntrianOrders to fetch.
   */
  orderBy?: Prisma.AntrianOrderOrderByWithRelationInput | Prisma.AntrianOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AntrianOrders.
   */
  cursor?: Prisma.AntrianOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AntrianOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AntrianOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AntrianOrders.
   */
  distinct?: Prisma.AntrianOrderScalarFieldEnum | Prisma.AntrianOrderScalarFieldEnum[]
}

/**
 * AntrianOrder findMany
 */
export type AntrianOrderFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AntrianOrder
   */
  select?: Prisma.AntrianOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AntrianOrder
   */
  omit?: Prisma.AntrianOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AntrianOrderInclude<ExtArgs> | null
  /**
   * Filter, which AntrianOrders to fetch.
   */
  where?: Prisma.AntrianOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AntrianOrders to fetch.
   */
  orderBy?: Prisma.AntrianOrderOrderByWithRelationInput | Prisma.AntrianOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AntrianOrders.
   */
  cursor?: Prisma.AntrianOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AntrianOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AntrianOrders.
   */
  skip?: number
  distinct?: Prisma.AntrianOrderScalarFieldEnum | Prisma.AntrianOrderScalarFieldEnum[]
}

/**
 * AntrianOrder create
 */
export type AntrianOrderCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AntrianOrder
   */
  select?: Prisma.AntrianOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AntrianOrder
   */
  omit?: Prisma.AntrianOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AntrianOrderInclude<ExtArgs> | null
  /**
   * The data needed to create a AntrianOrder.
   */
  data: Prisma.XOR<Prisma.AntrianOrderCreateInput, Prisma.AntrianOrderUncheckedCreateInput>
}

/**
 * AntrianOrder createMany
 */
export type AntrianOrderCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AntrianOrders.
   */
  data: Prisma.AntrianOrderCreateManyInput | Prisma.AntrianOrderCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AntrianOrder createManyAndReturn
 */
export type AntrianOrderCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AntrianOrder
   */
  select?: Prisma.AntrianOrderSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AntrianOrder
   */
  omit?: Prisma.AntrianOrderOmit<ExtArgs> | null
  /**
   * The data used to create many AntrianOrders.
   */
  data: Prisma.AntrianOrderCreateManyInput | Prisma.AntrianOrderCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AntrianOrderIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AntrianOrder update
 */
export type AntrianOrderUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AntrianOrder
   */
  select?: Prisma.AntrianOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AntrianOrder
   */
  omit?: Prisma.AntrianOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AntrianOrderInclude<ExtArgs> | null
  /**
   * The data needed to update a AntrianOrder.
   */
  data: Prisma.XOR<Prisma.AntrianOrderUpdateInput, Prisma.AntrianOrderUncheckedUpdateInput>
  /**
   * Choose, which AntrianOrder to update.
   */
  where: Prisma.AntrianOrderWhereUniqueInput
}

/**
 * AntrianOrder updateMany
 */
export type AntrianOrderUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AntrianOrders.
   */
  data: Prisma.XOR<Prisma.AntrianOrderUpdateManyMutationInput, Prisma.AntrianOrderUncheckedUpdateManyInput>
  /**
   * Filter which AntrianOrders to update
   */
  where?: Prisma.AntrianOrderWhereInput
  /**
   * Limit how many AntrianOrders to update.
   */
  limit?: number
}

/**
 * AntrianOrder updateManyAndReturn
 */
export type AntrianOrderUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AntrianOrder
   */
  select?: Prisma.AntrianOrderSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AntrianOrder
   */
  omit?: Prisma.AntrianOrderOmit<ExtArgs> | null
  /**
   * The data used to update AntrianOrders.
   */
  data: Prisma.XOR<Prisma.AntrianOrderUpdateManyMutationInput, Prisma.AntrianOrderUncheckedUpdateManyInput>
  /**
   * Filter which AntrianOrders to update
   */
  where?: Prisma.AntrianOrderWhereInput
  /**
   * Limit how many AntrianOrders to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AntrianOrderIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AntrianOrder upsert
 */
export type AntrianOrderUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AntrianOrder
   */
  select?: Prisma.AntrianOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AntrianOrder
   */
  omit?: Prisma.AntrianOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AntrianOrderInclude<ExtArgs> | null
  /**
   * The filter to search for the AntrianOrder to update in case it exists.
   */
  where: Prisma.AntrianOrderWhereUniqueInput
  /**
   * In case the AntrianOrder found by the `where` argument doesn't exist, create a new AntrianOrder with this data.
   */
  create: Prisma.XOR<Prisma.AntrianOrderCreateInput, Prisma.AntrianOrderUncheckedCreateInput>
  /**
   * In case the AntrianOrder was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AntrianOrderUpdateInput, Prisma.AntrianOrderUncheckedUpdateInput>
}

/**
 * AntrianOrder delete
 */
export type AntrianOrderDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AntrianOrder
   */
  select?: Prisma.AntrianOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AntrianOrder
   */
  omit?: Prisma.AntrianOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AntrianOrderInclude<ExtArgs> | null
  /**
   * Filter which AntrianOrder to delete.
   */
  where: Prisma.AntrianOrderWhereUniqueInput
}

/**
 * AntrianOrder deleteMany
 */
export type AntrianOrderDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AntrianOrders to delete
   */
  where?: Prisma.AntrianOrderWhereInput
  /**
   * Limit how many AntrianOrders to delete.
   */
  limit?: number
}

/**
 * AntrianOrder.transaksi
 */
export type AntrianOrder$transaksiArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaksi
   */
  select?: Prisma.TransaksiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaksi
   */
  omit?: Prisma.TransaksiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransaksiInclude<ExtArgs> | null
  where?: Prisma.TransaksiWhereInput
}

/**
 * AntrianOrder.item
 */
export type AntrianOrder$itemArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Item
   */
  select?: Prisma.ItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Item
   */
  omit?: Prisma.ItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemInclude<ExtArgs> | null
  where?: Prisma.ItemWhereInput
}

/**
 * AntrianOrder without action
 */
export type AntrianOrderDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AntrianOrder
   */
  select?: Prisma.AntrianOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AntrianOrder
   */
  omit?: Prisma.AntrianOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AntrianOrderInclude<ExtArgs> | null
}
