
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Meja` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Meja
 * 
 */
export type MejaModel = runtime.Types.Result.DefaultSelection<Prisma.$MejaPayload>

export type AggregateMeja = {
  _count: MejaCountAggregateOutputType | null
  _min: MejaMinAggregateOutputType | null
  _max: MejaMaxAggregateOutputType | null
}

export type MejaMinAggregateOutputType = {
  no_meja: string | null
  id_sesi: string | null
  status_meja: $Enums.StatusMeja | null
}

export type MejaMaxAggregateOutputType = {
  no_meja: string | null
  id_sesi: string | null
  status_meja: $Enums.StatusMeja | null
}

export type MejaCountAggregateOutputType = {
  no_meja: number
  id_sesi: number
  status_meja: number
  _all: number
}


export type MejaMinAggregateInputType = {
  no_meja?: true
  id_sesi?: true
  status_meja?: true
}

export type MejaMaxAggregateInputType = {
  no_meja?: true
  id_sesi?: true
  status_meja?: true
}

export type MejaCountAggregateInputType = {
  no_meja?: true
  id_sesi?: true
  status_meja?: true
  _all?: true
}

export type MejaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Meja to aggregate.
   */
  where?: Prisma.MejaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mejas to fetch.
   */
  orderBy?: Prisma.MejaOrderByWithRelationInput | Prisma.MejaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MejaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mejas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mejas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Mejas
  **/
  _count?: true | MejaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MejaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MejaMaxAggregateInputType
}

export type GetMejaAggregateType<T extends MejaAggregateArgs> = {
      [P in keyof T & keyof AggregateMeja]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMeja[P]>
    : Prisma.GetScalarType<T[P], AggregateMeja[P]>
}




export type MejaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MejaWhereInput
  orderBy?: Prisma.MejaOrderByWithAggregationInput | Prisma.MejaOrderByWithAggregationInput[]
  by: Prisma.MejaScalarFieldEnum[] | Prisma.MejaScalarFieldEnum
  having?: Prisma.MejaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MejaCountAggregateInputType | true
  _min?: MejaMinAggregateInputType
  _max?: MejaMaxAggregateInputType
}

export type MejaGroupByOutputType = {
  no_meja: string
  id_sesi: string
  status_meja: $Enums.StatusMeja | null
  _count: MejaCountAggregateOutputType | null
  _min: MejaMinAggregateOutputType | null
  _max: MejaMaxAggregateOutputType | null
}

type GetMejaGroupByPayload<T extends MejaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MejaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MejaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MejaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MejaGroupByOutputType[P]>
      }
    >
  >



export type MejaWhereInput = {
  AND?: Prisma.MejaWhereInput | Prisma.MejaWhereInput[]
  OR?: Prisma.MejaWhereInput[]
  NOT?: Prisma.MejaWhereInput | Prisma.MejaWhereInput[]
  no_meja?: Prisma.StringFilter<"Meja"> | string
  id_sesi?: Prisma.StringFilter<"Meja"> | string
  status_meja?: Prisma.EnumStatusMejaNullableFilter<"Meja"> | $Enums.StatusMeja | null
  sesi?: Prisma.XOR<Prisma.SesiPemesananScalarRelationFilter, Prisma.SesiPemesananWhereInput>
}

export type MejaOrderByWithRelationInput = {
  no_meja?: Prisma.SortOrder
  id_sesi?: Prisma.SortOrder
  status_meja?: Prisma.SortOrderInput | Prisma.SortOrder
  sesi?: Prisma.SesiPemesananOrderByWithRelationInput
}

export type MejaWhereUniqueInput = Prisma.AtLeast<{
  no_meja_id_sesi?: Prisma.MejaNo_mejaId_sesiCompoundUniqueInput
  AND?: Prisma.MejaWhereInput | Prisma.MejaWhereInput[]
  OR?: Prisma.MejaWhereInput[]
  NOT?: Prisma.MejaWhereInput | Prisma.MejaWhereInput[]
  no_meja?: Prisma.StringFilter<"Meja"> | string
  id_sesi?: Prisma.StringFilter<"Meja"> | string
  status_meja?: Prisma.EnumStatusMejaNullableFilter<"Meja"> | $Enums.StatusMeja | null
  sesi?: Prisma.XOR<Prisma.SesiPemesananScalarRelationFilter, Prisma.SesiPemesananWhereInput>
}, "no_meja_id_sesi">

export type MejaOrderByWithAggregationInput = {
  no_meja?: Prisma.SortOrder
  id_sesi?: Prisma.SortOrder
  status_meja?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.MejaCountOrderByAggregateInput
  _max?: Prisma.MejaMaxOrderByAggregateInput
  _min?: Prisma.MejaMinOrderByAggregateInput
}

export type MejaScalarWhereWithAggregatesInput = {
  AND?: Prisma.MejaScalarWhereWithAggregatesInput | Prisma.MejaScalarWhereWithAggregatesInput[]
  OR?: Prisma.MejaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MejaScalarWhereWithAggregatesInput | Prisma.MejaScalarWhereWithAggregatesInput[]
  no_meja?: Prisma.StringWithAggregatesFilter<"Meja"> | string
  id_sesi?: Prisma.StringWithAggregatesFilter<"Meja"> | string
  status_meja?: Prisma.EnumStatusMejaNullableWithAggregatesFilter<"Meja"> | $Enums.StatusMeja | null
}

export type MejaCreateInput = {
  no_meja: string
  status_meja?: $Enums.StatusMeja | null
  sesi: Prisma.SesiPemesananCreateNestedOneWithoutMejaInput
}

export type MejaUncheckedCreateInput = {
  no_meja: string
  id_sesi: string
  status_meja?: $Enums.StatusMeja | null
}

export type MejaUpdateInput = {
  no_meja?: Prisma.StringFieldUpdateOperationsInput | string
  status_meja?: Prisma.NullableEnumStatusMejaFieldUpdateOperationsInput | $Enums.StatusMeja | null
  sesi?: Prisma.SesiPemesananUpdateOneRequiredWithoutMejaNestedInput
}

export type MejaUncheckedUpdateInput = {
  no_meja?: Prisma.StringFieldUpdateOperationsInput | string
  id_sesi?: Prisma.StringFieldUpdateOperationsInput | string
  status_meja?: Prisma.NullableEnumStatusMejaFieldUpdateOperationsInput | $Enums.StatusMeja | null
}

export type MejaCreateManyInput = {
  no_meja: string
  id_sesi: string
  status_meja?: $Enums.StatusMeja | null
}

export type MejaUpdateManyMutationInput = {
  no_meja?: Prisma.StringFieldUpdateOperationsInput | string
  status_meja?: Prisma.NullableEnumStatusMejaFieldUpdateOperationsInput | $Enums.StatusMeja | null
}

export type MejaUncheckedUpdateManyInput = {
  no_meja?: Prisma.StringFieldUpdateOperationsInput | string
  id_sesi?: Prisma.StringFieldUpdateOperationsInput | string
  status_meja?: Prisma.NullableEnumStatusMejaFieldUpdateOperationsInput | $Enums.StatusMeja | null
}

export type MejaListRelationFilter = {
  every?: Prisma.MejaWhereInput
  some?: Prisma.MejaWhereInput
  none?: Prisma.MejaWhereInput
}

export type MejaOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MejaNo_mejaId_sesiCompoundUniqueInput = {
  no_meja: string
  id_sesi: string
}

export type MejaCountOrderByAggregateInput = {
  no_meja?: Prisma.SortOrder
  id_sesi?: Prisma.SortOrder
  status_meja?: Prisma.SortOrder
}

export type MejaMaxOrderByAggregateInput = {
  no_meja?: Prisma.SortOrder
  id_sesi?: Prisma.SortOrder
  status_meja?: Prisma.SortOrder
}

export type MejaMinOrderByAggregateInput = {
  no_meja?: Prisma.SortOrder
  id_sesi?: Prisma.SortOrder
  status_meja?: Prisma.SortOrder
}

export type MejaCreateNestedManyWithoutSesiInput = {
  create?: Prisma.XOR<Prisma.MejaCreateWithoutSesiInput, Prisma.MejaUncheckedCreateWithoutSesiInput> | Prisma.MejaCreateWithoutSesiInput[] | Prisma.MejaUncheckedCreateWithoutSesiInput[]
  connectOrCreate?: Prisma.MejaCreateOrConnectWithoutSesiInput | Prisma.MejaCreateOrConnectWithoutSesiInput[]
  createMany?: Prisma.MejaCreateManySesiInputEnvelope
  connect?: Prisma.MejaWhereUniqueInput | Prisma.MejaWhereUniqueInput[]
}

export type MejaUncheckedCreateNestedManyWithoutSesiInput = {
  create?: Prisma.XOR<Prisma.MejaCreateWithoutSesiInput, Prisma.MejaUncheckedCreateWithoutSesiInput> | Prisma.MejaCreateWithoutSesiInput[] | Prisma.MejaUncheckedCreateWithoutSesiInput[]
  connectOrCreate?: Prisma.MejaCreateOrConnectWithoutSesiInput | Prisma.MejaCreateOrConnectWithoutSesiInput[]
  createMany?: Prisma.MejaCreateManySesiInputEnvelope
  connect?: Prisma.MejaWhereUniqueInput | Prisma.MejaWhereUniqueInput[]
}

export type MejaUpdateManyWithoutSesiNestedInput = {
  create?: Prisma.XOR<Prisma.MejaCreateWithoutSesiInput, Prisma.MejaUncheckedCreateWithoutSesiInput> | Prisma.MejaCreateWithoutSesiInput[] | Prisma.MejaUncheckedCreateWithoutSesiInput[]
  connectOrCreate?: Prisma.MejaCreateOrConnectWithoutSesiInput | Prisma.MejaCreateOrConnectWithoutSesiInput[]
  upsert?: Prisma.MejaUpsertWithWhereUniqueWithoutSesiInput | Prisma.MejaUpsertWithWhereUniqueWithoutSesiInput[]
  createMany?: Prisma.MejaCreateManySesiInputEnvelope
  set?: Prisma.MejaWhereUniqueInput | Prisma.MejaWhereUniqueInput[]
  disconnect?: Prisma.MejaWhereUniqueInput | Prisma.MejaWhereUniqueInput[]
  delete?: Prisma.MejaWhereUniqueInput | Prisma.MejaWhereUniqueInput[]
  connect?: Prisma.MejaWhereUniqueInput | Prisma.MejaWhereUniqueInput[]
  update?: Prisma.MejaUpdateWithWhereUniqueWithoutSesiInput | Prisma.MejaUpdateWithWhereUniqueWithoutSesiInput[]
  updateMany?: Prisma.MejaUpdateManyWithWhereWithoutSesiInput | Prisma.MejaUpdateManyWithWhereWithoutSesiInput[]
  deleteMany?: Prisma.MejaScalarWhereInput | Prisma.MejaScalarWhereInput[]
}

export type MejaUncheckedUpdateManyWithoutSesiNestedInput = {
  create?: Prisma.XOR<Prisma.MejaCreateWithoutSesiInput, Prisma.MejaUncheckedCreateWithoutSesiInput> | Prisma.MejaCreateWithoutSesiInput[] | Prisma.MejaUncheckedCreateWithoutSesiInput[]
  connectOrCreate?: Prisma.MejaCreateOrConnectWithoutSesiInput | Prisma.MejaCreateOrConnectWithoutSesiInput[]
  upsert?: Prisma.MejaUpsertWithWhereUniqueWithoutSesiInput | Prisma.MejaUpsertWithWhereUniqueWithoutSesiInput[]
  createMany?: Prisma.MejaCreateManySesiInputEnvelope
  set?: Prisma.MejaWhereUniqueInput | Prisma.MejaWhereUniqueInput[]
  disconnect?: Prisma.MejaWhereUniqueInput | Prisma.MejaWhereUniqueInput[]
  delete?: Prisma.MejaWhereUniqueInput | Prisma.MejaWhereUniqueInput[]
  connect?: Prisma.MejaWhereUniqueInput | Prisma.MejaWhereUniqueInput[]
  update?: Prisma.MejaUpdateWithWhereUniqueWithoutSesiInput | Prisma.MejaUpdateWithWhereUniqueWithoutSesiInput[]
  updateMany?: Prisma.MejaUpdateManyWithWhereWithoutSesiInput | Prisma.MejaUpdateManyWithWhereWithoutSesiInput[]
  deleteMany?: Prisma.MejaScalarWhereInput | Prisma.MejaScalarWhereInput[]
}

export type NullableEnumStatusMejaFieldUpdateOperationsInput = {
  set?: $Enums.StatusMeja | null
}

export type MejaCreateWithoutSesiInput = {
  no_meja: string
  status_meja?: $Enums.StatusMeja | null
}

export type MejaUncheckedCreateWithoutSesiInput = {
  no_meja: string
  status_meja?: $Enums.StatusMeja | null
}

export type MejaCreateOrConnectWithoutSesiInput = {
  where: Prisma.MejaWhereUniqueInput
  create: Prisma.XOR<Prisma.MejaCreateWithoutSesiInput, Prisma.MejaUncheckedCreateWithoutSesiInput>
}

export type MejaCreateManySesiInputEnvelope = {
  data: Prisma.MejaCreateManySesiInput | Prisma.MejaCreateManySesiInput[]
  skipDuplicates?: boolean
}

export type MejaUpsertWithWhereUniqueWithoutSesiInput = {
  where: Prisma.MejaWhereUniqueInput
  update: Prisma.XOR<Prisma.MejaUpdateWithoutSesiInput, Prisma.MejaUncheckedUpdateWithoutSesiInput>
  create: Prisma.XOR<Prisma.MejaCreateWithoutSesiInput, Prisma.MejaUncheckedCreateWithoutSesiInput>
}

export type MejaUpdateWithWhereUniqueWithoutSesiInput = {
  where: Prisma.MejaWhereUniqueInput
  data: Prisma.XOR<Prisma.MejaUpdateWithoutSesiInput, Prisma.MejaUncheckedUpdateWithoutSesiInput>
}

export type MejaUpdateManyWithWhereWithoutSesiInput = {
  where: Prisma.MejaScalarWhereInput
  data: Prisma.XOR<Prisma.MejaUpdateManyMutationInput, Prisma.MejaUncheckedUpdateManyWithoutSesiInput>
}

export type MejaScalarWhereInput = {
  AND?: Prisma.MejaScalarWhereInput | Prisma.MejaScalarWhereInput[]
  OR?: Prisma.MejaScalarWhereInput[]
  NOT?: Prisma.MejaScalarWhereInput | Prisma.MejaScalarWhereInput[]
  no_meja?: Prisma.StringFilter<"Meja"> | string
  id_sesi?: Prisma.StringFilter<"Meja"> | string
  status_meja?: Prisma.EnumStatusMejaNullableFilter<"Meja"> | $Enums.StatusMeja | null
}

export type MejaCreateManySesiInput = {
  no_meja: string
  status_meja?: $Enums.StatusMeja | null
}

export type MejaUpdateWithoutSesiInput = {
  no_meja?: Prisma.StringFieldUpdateOperationsInput | string
  status_meja?: Prisma.NullableEnumStatusMejaFieldUpdateOperationsInput | $Enums.StatusMeja | null
}

export type MejaUncheckedUpdateWithoutSesiInput = {
  no_meja?: Prisma.StringFieldUpdateOperationsInput | string
  status_meja?: Prisma.NullableEnumStatusMejaFieldUpdateOperationsInput | $Enums.StatusMeja | null
}

export type MejaUncheckedUpdateManyWithoutSesiInput = {
  no_meja?: Prisma.StringFieldUpdateOperationsInput | string
  status_meja?: Prisma.NullableEnumStatusMejaFieldUpdateOperationsInput | $Enums.StatusMeja | null
}



export type MejaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  no_meja?: boolean
  id_sesi?: boolean
  status_meja?: boolean
  sesi?: boolean | Prisma.SesiPemesananDefaultArgs<ExtArgs>
}, ExtArgs["result"]["meja"]>

export type MejaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  no_meja?: boolean
  id_sesi?: boolean
  status_meja?: boolean
  sesi?: boolean | Prisma.SesiPemesananDefaultArgs<ExtArgs>
}, ExtArgs["result"]["meja"]>

export type MejaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  no_meja?: boolean
  id_sesi?: boolean
  status_meja?: boolean
  sesi?: boolean | Prisma.SesiPemesananDefaultArgs<ExtArgs>
}, ExtArgs["result"]["meja"]>

export type MejaSelectScalar = {
  no_meja?: boolean
  id_sesi?: boolean
  status_meja?: boolean
}

export type MejaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"no_meja" | "id_sesi" | "status_meja", ExtArgs["result"]["meja"]>
export type MejaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sesi?: boolean | Prisma.SesiPemesananDefaultArgs<ExtArgs>
}
export type MejaIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sesi?: boolean | Prisma.SesiPemesananDefaultArgs<ExtArgs>
}
export type MejaIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sesi?: boolean | Prisma.SesiPemesananDefaultArgs<ExtArgs>
}

export type $MejaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Meja"
  objects: {
    sesi: Prisma.$SesiPemesananPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    no_meja: string
    id_sesi: string
    status_meja: $Enums.StatusMeja | null
  }, ExtArgs["result"]["meja"]>
  composites: {}
}

export type MejaGetPayload<S extends boolean | null | undefined | MejaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MejaPayload, S>

export type MejaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MejaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MejaCountAggregateInputType | true
  }

export interface MejaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Meja'], meta: { name: 'Meja' } }
  /**
   * Find zero or one Meja that matches the filter.
   * @param {MejaFindUniqueArgs} args - Arguments to find a Meja
   * @example
   * // Get one Meja
   * const meja = await prisma.meja.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MejaFindUniqueArgs>(args: Prisma.SelectSubset<T, MejaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MejaClient<runtime.Types.Result.GetResult<Prisma.$MejaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Meja that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MejaFindUniqueOrThrowArgs} args - Arguments to find a Meja
   * @example
   * // Get one Meja
   * const meja = await prisma.meja.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MejaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MejaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MejaClient<runtime.Types.Result.GetResult<Prisma.$MejaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Meja that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MejaFindFirstArgs} args - Arguments to find a Meja
   * @example
   * // Get one Meja
   * const meja = await prisma.meja.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MejaFindFirstArgs>(args?: Prisma.SelectSubset<T, MejaFindFirstArgs<ExtArgs>>): Prisma.Prisma__MejaClient<runtime.Types.Result.GetResult<Prisma.$MejaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Meja that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MejaFindFirstOrThrowArgs} args - Arguments to find a Meja
   * @example
   * // Get one Meja
   * const meja = await prisma.meja.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MejaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MejaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MejaClient<runtime.Types.Result.GetResult<Prisma.$MejaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Mejas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MejaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Mejas
   * const mejas = await prisma.meja.findMany()
   * 
   * // Get first 10 Mejas
   * const mejas = await prisma.meja.findMany({ take: 10 })
   * 
   * // Only select the `no_meja`
   * const mejaWithNo_mejaOnly = await prisma.meja.findMany({ select: { no_meja: true } })
   * 
   */
  findMany<T extends MejaFindManyArgs>(args?: Prisma.SelectSubset<T, MejaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MejaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Meja.
   * @param {MejaCreateArgs} args - Arguments to create a Meja.
   * @example
   * // Create one Meja
   * const Meja = await prisma.meja.create({
   *   data: {
   *     // ... data to create a Meja
   *   }
   * })
   * 
   */
  create<T extends MejaCreateArgs>(args: Prisma.SelectSubset<T, MejaCreateArgs<ExtArgs>>): Prisma.Prisma__MejaClient<runtime.Types.Result.GetResult<Prisma.$MejaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Mejas.
   * @param {MejaCreateManyArgs} args - Arguments to create many Mejas.
   * @example
   * // Create many Mejas
   * const meja = await prisma.meja.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MejaCreateManyArgs>(args?: Prisma.SelectSubset<T, MejaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Mejas and returns the data saved in the database.
   * @param {MejaCreateManyAndReturnArgs} args - Arguments to create many Mejas.
   * @example
   * // Create many Mejas
   * const meja = await prisma.meja.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Mejas and only return the `no_meja`
   * const mejaWithNo_mejaOnly = await prisma.meja.createManyAndReturn({
   *   select: { no_meja: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MejaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MejaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MejaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Meja.
   * @param {MejaDeleteArgs} args - Arguments to delete one Meja.
   * @example
   * // Delete one Meja
   * const Meja = await prisma.meja.delete({
   *   where: {
   *     // ... filter to delete one Meja
   *   }
   * })
   * 
   */
  delete<T extends MejaDeleteArgs>(args: Prisma.SelectSubset<T, MejaDeleteArgs<ExtArgs>>): Prisma.Prisma__MejaClient<runtime.Types.Result.GetResult<Prisma.$MejaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Meja.
   * @param {MejaUpdateArgs} args - Arguments to update one Meja.
   * @example
   * // Update one Meja
   * const meja = await prisma.meja.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MejaUpdateArgs>(args: Prisma.SelectSubset<T, MejaUpdateArgs<ExtArgs>>): Prisma.Prisma__MejaClient<runtime.Types.Result.GetResult<Prisma.$MejaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Mejas.
   * @param {MejaDeleteManyArgs} args - Arguments to filter Mejas to delete.
   * @example
   * // Delete a few Mejas
   * const { count } = await prisma.meja.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MejaDeleteManyArgs>(args?: Prisma.SelectSubset<T, MejaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Mejas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MejaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Mejas
   * const meja = await prisma.meja.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MejaUpdateManyArgs>(args: Prisma.SelectSubset<T, MejaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Mejas and returns the data updated in the database.
   * @param {MejaUpdateManyAndReturnArgs} args - Arguments to update many Mejas.
   * @example
   * // Update many Mejas
   * const meja = await prisma.meja.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Mejas and only return the `no_meja`
   * const mejaWithNo_mejaOnly = await prisma.meja.updateManyAndReturn({
   *   select: { no_meja: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MejaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MejaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MejaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Meja.
   * @param {MejaUpsertArgs} args - Arguments to update or create a Meja.
   * @example
   * // Update or create a Meja
   * const meja = await prisma.meja.upsert({
   *   create: {
   *     // ... data to create a Meja
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Meja we want to update
   *   }
   * })
   */
  upsert<T extends MejaUpsertArgs>(args: Prisma.SelectSubset<T, MejaUpsertArgs<ExtArgs>>): Prisma.Prisma__MejaClient<runtime.Types.Result.GetResult<Prisma.$MejaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Mejas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MejaCountArgs} args - Arguments to filter Mejas to count.
   * @example
   * // Count the number of Mejas
   * const count = await prisma.meja.count({
   *   where: {
   *     // ... the filter for the Mejas we want to count
   *   }
   * })
  **/
  count<T extends MejaCountArgs>(
    args?: Prisma.Subset<T, MejaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MejaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Meja.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MejaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MejaAggregateArgs>(args: Prisma.Subset<T, MejaAggregateArgs>): Prisma.PrismaPromise<GetMejaAggregateType<T>>

  /**
   * Group by Meja.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MejaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MejaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MejaGroupByArgs['orderBy'] }
      : { orderBy?: MejaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MejaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMejaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Meja model
 */
readonly fields: MejaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Meja.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MejaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  sesi<T extends Prisma.SesiPemesananDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SesiPemesananDefaultArgs<ExtArgs>>): Prisma.Prisma__SesiPemesananClient<runtime.Types.Result.GetResult<Prisma.$SesiPemesananPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Meja model
 */
export interface MejaFieldRefs {
  readonly no_meja: Prisma.FieldRef<"Meja", 'String'>
  readonly id_sesi: Prisma.FieldRef<"Meja", 'String'>
  readonly status_meja: Prisma.FieldRef<"Meja", 'StatusMeja'>
}
    

// Custom InputTypes
/**
 * Meja findUnique
 */
export type MejaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Meja
   */
  select?: Prisma.MejaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Meja
   */
  omit?: Prisma.MejaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MejaInclude<ExtArgs> | null
  /**
   * Filter, which Meja to fetch.
   */
  where: Prisma.MejaWhereUniqueInput
}

/**
 * Meja findUniqueOrThrow
 */
export type MejaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Meja
   */
  select?: Prisma.MejaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Meja
   */
  omit?: Prisma.MejaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MejaInclude<ExtArgs> | null
  /**
   * Filter, which Meja to fetch.
   */
  where: Prisma.MejaWhereUniqueInput
}

/**
 * Meja findFirst
 */
export type MejaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Meja
   */
  select?: Prisma.MejaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Meja
   */
  omit?: Prisma.MejaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MejaInclude<ExtArgs> | null
  /**
   * Filter, which Meja to fetch.
   */
  where?: Prisma.MejaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mejas to fetch.
   */
  orderBy?: Prisma.MejaOrderByWithRelationInput | Prisma.MejaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Mejas.
   */
  cursor?: Prisma.MejaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mejas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mejas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Mejas.
   */
  distinct?: Prisma.MejaScalarFieldEnum | Prisma.MejaScalarFieldEnum[]
}

/**
 * Meja findFirstOrThrow
 */
export type MejaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Meja
   */
  select?: Prisma.MejaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Meja
   */
  omit?: Prisma.MejaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MejaInclude<ExtArgs> | null
  /**
   * Filter, which Meja to fetch.
   */
  where?: Prisma.MejaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mejas to fetch.
   */
  orderBy?: Prisma.MejaOrderByWithRelationInput | Prisma.MejaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Mejas.
   */
  cursor?: Prisma.MejaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mejas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mejas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Mejas.
   */
  distinct?: Prisma.MejaScalarFieldEnum | Prisma.MejaScalarFieldEnum[]
}

/**
 * Meja findMany
 */
export type MejaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Meja
   */
  select?: Prisma.MejaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Meja
   */
  omit?: Prisma.MejaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MejaInclude<ExtArgs> | null
  /**
   * Filter, which Mejas to fetch.
   */
  where?: Prisma.MejaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Mejas to fetch.
   */
  orderBy?: Prisma.MejaOrderByWithRelationInput | Prisma.MejaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Mejas.
   */
  cursor?: Prisma.MejaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Mejas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Mejas.
   */
  skip?: number
  distinct?: Prisma.MejaScalarFieldEnum | Prisma.MejaScalarFieldEnum[]
}

/**
 * Meja create
 */
export type MejaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Meja
   */
  select?: Prisma.MejaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Meja
   */
  omit?: Prisma.MejaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MejaInclude<ExtArgs> | null
  /**
   * The data needed to create a Meja.
   */
  data: Prisma.XOR<Prisma.MejaCreateInput, Prisma.MejaUncheckedCreateInput>
}

/**
 * Meja createMany
 */
export type MejaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Mejas.
   */
  data: Prisma.MejaCreateManyInput | Prisma.MejaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Meja createManyAndReturn
 */
export type MejaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Meja
   */
  select?: Prisma.MejaSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Meja
   */
  omit?: Prisma.MejaOmit<ExtArgs> | null
  /**
   * The data used to create many Mejas.
   */
  data: Prisma.MejaCreateManyInput | Prisma.MejaCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MejaIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Meja update
 */
export type MejaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Meja
   */
  select?: Prisma.MejaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Meja
   */
  omit?: Prisma.MejaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MejaInclude<ExtArgs> | null
  /**
   * The data needed to update a Meja.
   */
  data: Prisma.XOR<Prisma.MejaUpdateInput, Prisma.MejaUncheckedUpdateInput>
  /**
   * Choose, which Meja to update.
   */
  where: Prisma.MejaWhereUniqueInput
}

/**
 * Meja updateMany
 */
export type MejaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Mejas.
   */
  data: Prisma.XOR<Prisma.MejaUpdateManyMutationInput, Prisma.MejaUncheckedUpdateManyInput>
  /**
   * Filter which Mejas to update
   */
  where?: Prisma.MejaWhereInput
  /**
   * Limit how many Mejas to update.
   */
  limit?: number
}

/**
 * Meja updateManyAndReturn
 */
export type MejaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Meja
   */
  select?: Prisma.MejaSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Meja
   */
  omit?: Prisma.MejaOmit<ExtArgs> | null
  /**
   * The data used to update Mejas.
   */
  data: Prisma.XOR<Prisma.MejaUpdateManyMutationInput, Prisma.MejaUncheckedUpdateManyInput>
  /**
   * Filter which Mejas to update
   */
  where?: Prisma.MejaWhereInput
  /**
   * Limit how many Mejas to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MejaIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Meja upsert
 */
export type MejaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Meja
   */
  select?: Prisma.MejaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Meja
   */
  omit?: Prisma.MejaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MejaInclude<ExtArgs> | null
  /**
   * The filter to search for the Meja to update in case it exists.
   */
  where: Prisma.MejaWhereUniqueInput
  /**
   * In case the Meja found by the `where` argument doesn't exist, create a new Meja with this data.
   */
  create: Prisma.XOR<Prisma.MejaCreateInput, Prisma.MejaUncheckedCreateInput>
  /**
   * In case the Meja was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MejaUpdateInput, Prisma.MejaUncheckedUpdateInput>
}

/**
 * Meja delete
 */
export type MejaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Meja
   */
  select?: Prisma.MejaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Meja
   */
  omit?: Prisma.MejaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MejaInclude<ExtArgs> | null
  /**
   * Filter which Meja to delete.
   */
  where: Prisma.MejaWhereUniqueInput
}

/**
 * Meja deleteMany
 */
export type MejaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Mejas to delete
   */
  where?: Prisma.MejaWhereInput
  /**
   * Limit how many Mejas to delete.
   */
  limit?: number
}

/**
 * Meja without action
 */
export type MejaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Meja
   */
  select?: Prisma.MejaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Meja
   */
  omit?: Prisma.MejaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MejaInclude<ExtArgs> | null
}
