
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Pelanggan` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Pelanggan
 * 
 */
export type PelangganModel = runtime.Types.Result.DefaultSelection<Prisma.$PelangganPayload>

export type AggregatePelanggan = {
  _count: PelangganCountAggregateOutputType | null
  _min: PelangganMinAggregateOutputType | null
  _max: PelangganMaxAggregateOutputType | null
}

export type PelangganMinAggregateOutputType = {
  id_pelanggan: string | null
  nama_pembeli: string | null
  password: string | null
}

export type PelangganMaxAggregateOutputType = {
  id_pelanggan: string | null
  nama_pembeli: string | null
  password: string | null
}

export type PelangganCountAggregateOutputType = {
  id_pelanggan: number
  nama_pembeli: number
  password: number
  _all: number
}


export type PelangganMinAggregateInputType = {
  id_pelanggan?: true
  nama_pembeli?: true
  password?: true
}

export type PelangganMaxAggregateInputType = {
  id_pelanggan?: true
  nama_pembeli?: true
  password?: true
}

export type PelangganCountAggregateInputType = {
  id_pelanggan?: true
  nama_pembeli?: true
  password?: true
  _all?: true
}

export type PelangganAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Pelanggan to aggregate.
   */
  where?: Prisma.PelangganWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pelanggans to fetch.
   */
  orderBy?: Prisma.PelangganOrderByWithRelationInput | Prisma.PelangganOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PelangganWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pelanggans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pelanggans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Pelanggans
  **/
  _count?: true | PelangganCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PelangganMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PelangganMaxAggregateInputType
}

export type GetPelangganAggregateType<T extends PelangganAggregateArgs> = {
      [P in keyof T & keyof AggregatePelanggan]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePelanggan[P]>
    : Prisma.GetScalarType<T[P], AggregatePelanggan[P]>
}




export type PelangganGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PelangganWhereInput
  orderBy?: Prisma.PelangganOrderByWithAggregationInput | Prisma.PelangganOrderByWithAggregationInput[]
  by: Prisma.PelangganScalarFieldEnum[] | Prisma.PelangganScalarFieldEnum
  having?: Prisma.PelangganScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PelangganCountAggregateInputType | true
  _min?: PelangganMinAggregateInputType
  _max?: PelangganMaxAggregateInputType
}

export type PelangganGroupByOutputType = {
  id_pelanggan: string
  nama_pembeli: string | null
  password: string | null
  _count: PelangganCountAggregateOutputType | null
  _min: PelangganMinAggregateOutputType | null
  _max: PelangganMaxAggregateOutputType | null
}

type GetPelangganGroupByPayload<T extends PelangganGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PelangganGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PelangganGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PelangganGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PelangganGroupByOutputType[P]>
      }
    >
  >



export type PelangganWhereInput = {
  AND?: Prisma.PelangganWhereInput | Prisma.PelangganWhereInput[]
  OR?: Prisma.PelangganWhereInput[]
  NOT?: Prisma.PelangganWhereInput | Prisma.PelangganWhereInput[]
  id_pelanggan?: Prisma.StringFilter<"Pelanggan"> | string
  nama_pembeli?: Prisma.StringNullableFilter<"Pelanggan"> | string | null
  password?: Prisma.StringNullableFilter<"Pelanggan"> | string | null
  sesi_pemesanan?: Prisma.SesiPemesananListRelationFilter
}

export type PelangganOrderByWithRelationInput = {
  id_pelanggan?: Prisma.SortOrder
  nama_pembeli?: Prisma.SortOrderInput | Prisma.SortOrder
  password?: Prisma.SortOrderInput | Prisma.SortOrder
  sesi_pemesanan?: Prisma.SesiPemesananOrderByRelationAggregateInput
}

export type PelangganWhereUniqueInput = Prisma.AtLeast<{
  id_pelanggan?: string
  AND?: Prisma.PelangganWhereInput | Prisma.PelangganWhereInput[]
  OR?: Prisma.PelangganWhereInput[]
  NOT?: Prisma.PelangganWhereInput | Prisma.PelangganWhereInput[]
  nama_pembeli?: Prisma.StringNullableFilter<"Pelanggan"> | string | null
  password?: Prisma.StringNullableFilter<"Pelanggan"> | string | null
  sesi_pemesanan?: Prisma.SesiPemesananListRelationFilter
}, "id_pelanggan">

export type PelangganOrderByWithAggregationInput = {
  id_pelanggan?: Prisma.SortOrder
  nama_pembeli?: Prisma.SortOrderInput | Prisma.SortOrder
  password?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.PelangganCountOrderByAggregateInput
  _max?: Prisma.PelangganMaxOrderByAggregateInput
  _min?: Prisma.PelangganMinOrderByAggregateInput
}

export type PelangganScalarWhereWithAggregatesInput = {
  AND?: Prisma.PelangganScalarWhereWithAggregatesInput | Prisma.PelangganScalarWhereWithAggregatesInput[]
  OR?: Prisma.PelangganScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PelangganScalarWhereWithAggregatesInput | Prisma.PelangganScalarWhereWithAggregatesInput[]
  id_pelanggan?: Prisma.StringWithAggregatesFilter<"Pelanggan"> | string
  nama_pembeli?: Prisma.StringNullableWithAggregatesFilter<"Pelanggan"> | string | null
  password?: Prisma.StringNullableWithAggregatesFilter<"Pelanggan"> | string | null
}

export type PelangganCreateInput = {
  id_pelanggan: string
  nama_pembeli?: string | null
  password?: string | null
  sesi_pemesanan?: Prisma.SesiPemesananCreateNestedManyWithoutPelangganInput
}

export type PelangganUncheckedCreateInput = {
  id_pelanggan: string
  nama_pembeli?: string | null
  password?: string | null
  sesi_pemesanan?: Prisma.SesiPemesananUncheckedCreateNestedManyWithoutPelangganInput
}

export type PelangganUpdateInput = {
  id_pelanggan?: Prisma.StringFieldUpdateOperationsInput | string
  nama_pembeli?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sesi_pemesanan?: Prisma.SesiPemesananUpdateManyWithoutPelangganNestedInput
}

export type PelangganUncheckedUpdateInput = {
  id_pelanggan?: Prisma.StringFieldUpdateOperationsInput | string
  nama_pembeli?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sesi_pemesanan?: Prisma.SesiPemesananUncheckedUpdateManyWithoutPelangganNestedInput
}

export type PelangganCreateManyInput = {
  id_pelanggan: string
  nama_pembeli?: string | null
  password?: string | null
}

export type PelangganUpdateManyMutationInput = {
  id_pelanggan?: Prisma.StringFieldUpdateOperationsInput | string
  nama_pembeli?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PelangganUncheckedUpdateManyInput = {
  id_pelanggan?: Prisma.StringFieldUpdateOperationsInput | string
  nama_pembeli?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PelangganCountOrderByAggregateInput = {
  id_pelanggan?: Prisma.SortOrder
  nama_pembeli?: Prisma.SortOrder
  password?: Prisma.SortOrder
}

export type PelangganMaxOrderByAggregateInput = {
  id_pelanggan?: Prisma.SortOrder
  nama_pembeli?: Prisma.SortOrder
  password?: Prisma.SortOrder
}

export type PelangganMinOrderByAggregateInput = {
  id_pelanggan?: Prisma.SortOrder
  nama_pembeli?: Prisma.SortOrder
  password?: Prisma.SortOrder
}

export type PelangganNullableScalarRelationFilter = {
  is?: Prisma.PelangganWhereInput | null
  isNot?: Prisma.PelangganWhereInput | null
}

export type PelangganCreateNestedOneWithoutSesi_pemesananInput = {
  create?: Prisma.XOR<Prisma.PelangganCreateWithoutSesi_pemesananInput, Prisma.PelangganUncheckedCreateWithoutSesi_pemesananInput>
  connectOrCreate?: Prisma.PelangganCreateOrConnectWithoutSesi_pemesananInput
  connect?: Prisma.PelangganWhereUniqueInput
}

export type PelangganUpdateOneWithoutSesi_pemesananNestedInput = {
  create?: Prisma.XOR<Prisma.PelangganCreateWithoutSesi_pemesananInput, Prisma.PelangganUncheckedCreateWithoutSesi_pemesananInput>
  connectOrCreate?: Prisma.PelangganCreateOrConnectWithoutSesi_pemesananInput
  upsert?: Prisma.PelangganUpsertWithoutSesi_pemesananInput
  disconnect?: Prisma.PelangganWhereInput | boolean
  delete?: Prisma.PelangganWhereInput | boolean
  connect?: Prisma.PelangganWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PelangganUpdateToOneWithWhereWithoutSesi_pemesananInput, Prisma.PelangganUpdateWithoutSesi_pemesananInput>, Prisma.PelangganUncheckedUpdateWithoutSesi_pemesananInput>
}

export type PelangganCreateWithoutSesi_pemesananInput = {
  id_pelanggan: string
  nama_pembeli?: string | null
  password?: string | null
}

export type PelangganUncheckedCreateWithoutSesi_pemesananInput = {
  id_pelanggan: string
  nama_pembeli?: string | null
  password?: string | null
}

export type PelangganCreateOrConnectWithoutSesi_pemesananInput = {
  where: Prisma.PelangganWhereUniqueInput
  create: Prisma.XOR<Prisma.PelangganCreateWithoutSesi_pemesananInput, Prisma.PelangganUncheckedCreateWithoutSesi_pemesananInput>
}

export type PelangganUpsertWithoutSesi_pemesananInput = {
  update: Prisma.XOR<Prisma.PelangganUpdateWithoutSesi_pemesananInput, Prisma.PelangganUncheckedUpdateWithoutSesi_pemesananInput>
  create: Prisma.XOR<Prisma.PelangganCreateWithoutSesi_pemesananInput, Prisma.PelangganUncheckedCreateWithoutSesi_pemesananInput>
  where?: Prisma.PelangganWhereInput
}

export type PelangganUpdateToOneWithWhereWithoutSesi_pemesananInput = {
  where?: Prisma.PelangganWhereInput
  data: Prisma.XOR<Prisma.PelangganUpdateWithoutSesi_pemesananInput, Prisma.PelangganUncheckedUpdateWithoutSesi_pemesananInput>
}

export type PelangganUpdateWithoutSesi_pemesananInput = {
  id_pelanggan?: Prisma.StringFieldUpdateOperationsInput | string
  nama_pembeli?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PelangganUncheckedUpdateWithoutSesi_pemesananInput = {
  id_pelanggan?: Prisma.StringFieldUpdateOperationsInput | string
  nama_pembeli?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type PelangganCountOutputType
 */

export type PelangganCountOutputType = {
  sesi_pemesanan: number
}

export type PelangganCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sesi_pemesanan?: boolean | PelangganCountOutputTypeCountSesi_pemesananArgs
}

/**
 * PelangganCountOutputType without action
 */
export type PelangganCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PelangganCountOutputType
   */
  select?: Prisma.PelangganCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PelangganCountOutputType without action
 */
export type PelangganCountOutputTypeCountSesi_pemesananArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SesiPemesananWhereInput
}


export type PelangganSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id_pelanggan?: boolean
  nama_pembeli?: boolean
  password?: boolean
  sesi_pemesanan?: boolean | Prisma.Pelanggan$sesi_pemesananArgs<ExtArgs>
  _count?: boolean | Prisma.PelangganCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pelanggan"]>

export type PelangganSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id_pelanggan?: boolean
  nama_pembeli?: boolean
  password?: boolean
}, ExtArgs["result"]["pelanggan"]>

export type PelangganSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id_pelanggan?: boolean
  nama_pembeli?: boolean
  password?: boolean
}, ExtArgs["result"]["pelanggan"]>

export type PelangganSelectScalar = {
  id_pelanggan?: boolean
  nama_pembeli?: boolean
  password?: boolean
}

export type PelangganOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id_pelanggan" | "nama_pembeli" | "password", ExtArgs["result"]["pelanggan"]>
export type PelangganInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sesi_pemesanan?: boolean | Prisma.Pelanggan$sesi_pemesananArgs<ExtArgs>
  _count?: boolean | Prisma.PelangganCountOutputTypeDefaultArgs<ExtArgs>
}
export type PelangganIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type PelangganIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $PelangganPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Pelanggan"
  objects: {
    sesi_pemesanan: Prisma.$SesiPemesananPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id_pelanggan: string
    nama_pembeli: string | null
    password: string | null
  }, ExtArgs["result"]["pelanggan"]>
  composites: {}
}

export type PelangganGetPayload<S extends boolean | null | undefined | PelangganDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PelangganPayload, S>

export type PelangganCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PelangganFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PelangganCountAggregateInputType | true
  }

export interface PelangganDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Pelanggan'], meta: { name: 'Pelanggan' } }
  /**
   * Find zero or one Pelanggan that matches the filter.
   * @param {PelangganFindUniqueArgs} args - Arguments to find a Pelanggan
   * @example
   * // Get one Pelanggan
   * const pelanggan = await prisma.pelanggan.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PelangganFindUniqueArgs>(args: Prisma.SelectSubset<T, PelangganFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PelangganClient<runtime.Types.Result.GetResult<Prisma.$PelangganPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Pelanggan that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PelangganFindUniqueOrThrowArgs} args - Arguments to find a Pelanggan
   * @example
   * // Get one Pelanggan
   * const pelanggan = await prisma.pelanggan.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PelangganFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PelangganFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PelangganClient<runtime.Types.Result.GetResult<Prisma.$PelangganPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Pelanggan that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PelangganFindFirstArgs} args - Arguments to find a Pelanggan
   * @example
   * // Get one Pelanggan
   * const pelanggan = await prisma.pelanggan.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PelangganFindFirstArgs>(args?: Prisma.SelectSubset<T, PelangganFindFirstArgs<ExtArgs>>): Prisma.Prisma__PelangganClient<runtime.Types.Result.GetResult<Prisma.$PelangganPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Pelanggan that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PelangganFindFirstOrThrowArgs} args - Arguments to find a Pelanggan
   * @example
   * // Get one Pelanggan
   * const pelanggan = await prisma.pelanggan.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PelangganFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PelangganFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PelangganClient<runtime.Types.Result.GetResult<Prisma.$PelangganPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Pelanggans that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PelangganFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Pelanggans
   * const pelanggans = await prisma.pelanggan.findMany()
   * 
   * // Get first 10 Pelanggans
   * const pelanggans = await prisma.pelanggan.findMany({ take: 10 })
   * 
   * // Only select the `id_pelanggan`
   * const pelangganWithId_pelangganOnly = await prisma.pelanggan.findMany({ select: { id_pelanggan: true } })
   * 
   */
  findMany<T extends PelangganFindManyArgs>(args?: Prisma.SelectSubset<T, PelangganFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PelangganPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Pelanggan.
   * @param {PelangganCreateArgs} args - Arguments to create a Pelanggan.
   * @example
   * // Create one Pelanggan
   * const Pelanggan = await prisma.pelanggan.create({
   *   data: {
   *     // ... data to create a Pelanggan
   *   }
   * })
   * 
   */
  create<T extends PelangganCreateArgs>(args: Prisma.SelectSubset<T, PelangganCreateArgs<ExtArgs>>): Prisma.Prisma__PelangganClient<runtime.Types.Result.GetResult<Prisma.$PelangganPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Pelanggans.
   * @param {PelangganCreateManyArgs} args - Arguments to create many Pelanggans.
   * @example
   * // Create many Pelanggans
   * const pelanggan = await prisma.pelanggan.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PelangganCreateManyArgs>(args?: Prisma.SelectSubset<T, PelangganCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Pelanggans and returns the data saved in the database.
   * @param {PelangganCreateManyAndReturnArgs} args - Arguments to create many Pelanggans.
   * @example
   * // Create many Pelanggans
   * const pelanggan = await prisma.pelanggan.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Pelanggans and only return the `id_pelanggan`
   * const pelangganWithId_pelangganOnly = await prisma.pelanggan.createManyAndReturn({
   *   select: { id_pelanggan: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PelangganCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PelangganCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PelangganPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Pelanggan.
   * @param {PelangganDeleteArgs} args - Arguments to delete one Pelanggan.
   * @example
   * // Delete one Pelanggan
   * const Pelanggan = await prisma.pelanggan.delete({
   *   where: {
   *     // ... filter to delete one Pelanggan
   *   }
   * })
   * 
   */
  delete<T extends PelangganDeleteArgs>(args: Prisma.SelectSubset<T, PelangganDeleteArgs<ExtArgs>>): Prisma.Prisma__PelangganClient<runtime.Types.Result.GetResult<Prisma.$PelangganPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Pelanggan.
   * @param {PelangganUpdateArgs} args - Arguments to update one Pelanggan.
   * @example
   * // Update one Pelanggan
   * const pelanggan = await prisma.pelanggan.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PelangganUpdateArgs>(args: Prisma.SelectSubset<T, PelangganUpdateArgs<ExtArgs>>): Prisma.Prisma__PelangganClient<runtime.Types.Result.GetResult<Prisma.$PelangganPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Pelanggans.
   * @param {PelangganDeleteManyArgs} args - Arguments to filter Pelanggans to delete.
   * @example
   * // Delete a few Pelanggans
   * const { count } = await prisma.pelanggan.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PelangganDeleteManyArgs>(args?: Prisma.SelectSubset<T, PelangganDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Pelanggans.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PelangganUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Pelanggans
   * const pelanggan = await prisma.pelanggan.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PelangganUpdateManyArgs>(args: Prisma.SelectSubset<T, PelangganUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Pelanggans and returns the data updated in the database.
   * @param {PelangganUpdateManyAndReturnArgs} args - Arguments to update many Pelanggans.
   * @example
   * // Update many Pelanggans
   * const pelanggan = await prisma.pelanggan.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Pelanggans and only return the `id_pelanggan`
   * const pelangganWithId_pelangganOnly = await prisma.pelanggan.updateManyAndReturn({
   *   select: { id_pelanggan: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PelangganUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PelangganUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PelangganPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Pelanggan.
   * @param {PelangganUpsertArgs} args - Arguments to update or create a Pelanggan.
   * @example
   * // Update or create a Pelanggan
   * const pelanggan = await prisma.pelanggan.upsert({
   *   create: {
   *     // ... data to create a Pelanggan
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Pelanggan we want to update
   *   }
   * })
   */
  upsert<T extends PelangganUpsertArgs>(args: Prisma.SelectSubset<T, PelangganUpsertArgs<ExtArgs>>): Prisma.Prisma__PelangganClient<runtime.Types.Result.GetResult<Prisma.$PelangganPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Pelanggans.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PelangganCountArgs} args - Arguments to filter Pelanggans to count.
   * @example
   * // Count the number of Pelanggans
   * const count = await prisma.pelanggan.count({
   *   where: {
   *     // ... the filter for the Pelanggans we want to count
   *   }
   * })
  **/
  count<T extends PelangganCountArgs>(
    args?: Prisma.Subset<T, PelangganCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PelangganCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Pelanggan.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PelangganAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PelangganAggregateArgs>(args: Prisma.Subset<T, PelangganAggregateArgs>): Prisma.PrismaPromise<GetPelangganAggregateType<T>>

  /**
   * Group by Pelanggan.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PelangganGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PelangganGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PelangganGroupByArgs['orderBy'] }
      : { orderBy?: PelangganGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PelangganGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPelangganGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Pelanggan model
 */
readonly fields: PelangganFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Pelanggan.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PelangganClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  sesi_pemesanan<T extends Prisma.Pelanggan$sesi_pemesananArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Pelanggan$sesi_pemesananArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SesiPemesananPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Pelanggan model
 */
export interface PelangganFieldRefs {
  readonly id_pelanggan: Prisma.FieldRef<"Pelanggan", 'String'>
  readonly nama_pembeli: Prisma.FieldRef<"Pelanggan", 'String'>
  readonly password: Prisma.FieldRef<"Pelanggan", 'String'>
}
    

// Custom InputTypes
/**
 * Pelanggan findUnique
 */
export type PelangganFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pelanggan
   */
  select?: Prisma.PelangganSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pelanggan
   */
  omit?: Prisma.PelangganOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PelangganInclude<ExtArgs> | null
  /**
   * Filter, which Pelanggan to fetch.
   */
  where: Prisma.PelangganWhereUniqueInput
}

/**
 * Pelanggan findUniqueOrThrow
 */
export type PelangganFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pelanggan
   */
  select?: Prisma.PelangganSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pelanggan
   */
  omit?: Prisma.PelangganOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PelangganInclude<ExtArgs> | null
  /**
   * Filter, which Pelanggan to fetch.
   */
  where: Prisma.PelangganWhereUniqueInput
}

/**
 * Pelanggan findFirst
 */
export type PelangganFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pelanggan
   */
  select?: Prisma.PelangganSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pelanggan
   */
  omit?: Prisma.PelangganOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PelangganInclude<ExtArgs> | null
  /**
   * Filter, which Pelanggan to fetch.
   */
  where?: Prisma.PelangganWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pelanggans to fetch.
   */
  orderBy?: Prisma.PelangganOrderByWithRelationInput | Prisma.PelangganOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Pelanggans.
   */
  cursor?: Prisma.PelangganWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pelanggans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pelanggans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Pelanggans.
   */
  distinct?: Prisma.PelangganScalarFieldEnum | Prisma.PelangganScalarFieldEnum[]
}

/**
 * Pelanggan findFirstOrThrow
 */
export type PelangganFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pelanggan
   */
  select?: Prisma.PelangganSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pelanggan
   */
  omit?: Prisma.PelangganOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PelangganInclude<ExtArgs> | null
  /**
   * Filter, which Pelanggan to fetch.
   */
  where?: Prisma.PelangganWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pelanggans to fetch.
   */
  orderBy?: Prisma.PelangganOrderByWithRelationInput | Prisma.PelangganOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Pelanggans.
   */
  cursor?: Prisma.PelangganWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pelanggans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pelanggans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Pelanggans.
   */
  distinct?: Prisma.PelangganScalarFieldEnum | Prisma.PelangganScalarFieldEnum[]
}

/**
 * Pelanggan findMany
 */
export type PelangganFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pelanggan
   */
  select?: Prisma.PelangganSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pelanggan
   */
  omit?: Prisma.PelangganOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PelangganInclude<ExtArgs> | null
  /**
   * Filter, which Pelanggans to fetch.
   */
  where?: Prisma.PelangganWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pelanggans to fetch.
   */
  orderBy?: Prisma.PelangganOrderByWithRelationInput | Prisma.PelangganOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Pelanggans.
   */
  cursor?: Prisma.PelangganWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pelanggans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pelanggans.
   */
  skip?: number
  distinct?: Prisma.PelangganScalarFieldEnum | Prisma.PelangganScalarFieldEnum[]
}

/**
 * Pelanggan create
 */
export type PelangganCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pelanggan
   */
  select?: Prisma.PelangganSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pelanggan
   */
  omit?: Prisma.PelangganOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PelangganInclude<ExtArgs> | null
  /**
   * The data needed to create a Pelanggan.
   */
  data: Prisma.XOR<Prisma.PelangganCreateInput, Prisma.PelangganUncheckedCreateInput>
}

/**
 * Pelanggan createMany
 */
export type PelangganCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Pelanggans.
   */
  data: Prisma.PelangganCreateManyInput | Prisma.PelangganCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Pelanggan createManyAndReturn
 */
export type PelangganCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pelanggan
   */
  select?: Prisma.PelangganSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Pelanggan
   */
  omit?: Prisma.PelangganOmit<ExtArgs> | null
  /**
   * The data used to create many Pelanggans.
   */
  data: Prisma.PelangganCreateManyInput | Prisma.PelangganCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Pelanggan update
 */
export type PelangganUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pelanggan
   */
  select?: Prisma.PelangganSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pelanggan
   */
  omit?: Prisma.PelangganOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PelangganInclude<ExtArgs> | null
  /**
   * The data needed to update a Pelanggan.
   */
  data: Prisma.XOR<Prisma.PelangganUpdateInput, Prisma.PelangganUncheckedUpdateInput>
  /**
   * Choose, which Pelanggan to update.
   */
  where: Prisma.PelangganWhereUniqueInput
}

/**
 * Pelanggan updateMany
 */
export type PelangganUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Pelanggans.
   */
  data: Prisma.XOR<Prisma.PelangganUpdateManyMutationInput, Prisma.PelangganUncheckedUpdateManyInput>
  /**
   * Filter which Pelanggans to update
   */
  where?: Prisma.PelangganWhereInput
  /**
   * Limit how many Pelanggans to update.
   */
  limit?: number
}

/**
 * Pelanggan updateManyAndReturn
 */
export type PelangganUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pelanggan
   */
  select?: Prisma.PelangganSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Pelanggan
   */
  omit?: Prisma.PelangganOmit<ExtArgs> | null
  /**
   * The data used to update Pelanggans.
   */
  data: Prisma.XOR<Prisma.PelangganUpdateManyMutationInput, Prisma.PelangganUncheckedUpdateManyInput>
  /**
   * Filter which Pelanggans to update
   */
  where?: Prisma.PelangganWhereInput
  /**
   * Limit how many Pelanggans to update.
   */
  limit?: number
}

/**
 * Pelanggan upsert
 */
export type PelangganUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pelanggan
   */
  select?: Prisma.PelangganSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pelanggan
   */
  omit?: Prisma.PelangganOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PelangganInclude<ExtArgs> | null
  /**
   * The filter to search for the Pelanggan to update in case it exists.
   */
  where: Prisma.PelangganWhereUniqueInput
  /**
   * In case the Pelanggan found by the `where` argument doesn't exist, create a new Pelanggan with this data.
   */
  create: Prisma.XOR<Prisma.PelangganCreateInput, Prisma.PelangganUncheckedCreateInput>
  /**
   * In case the Pelanggan was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PelangganUpdateInput, Prisma.PelangganUncheckedUpdateInput>
}

/**
 * Pelanggan delete
 */
export type PelangganDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pelanggan
   */
  select?: Prisma.PelangganSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pelanggan
   */
  omit?: Prisma.PelangganOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PelangganInclude<ExtArgs> | null
  /**
   * Filter which Pelanggan to delete.
   */
  where: Prisma.PelangganWhereUniqueInput
}

/**
 * Pelanggan deleteMany
 */
export type PelangganDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Pelanggans to delete
   */
  where?: Prisma.PelangganWhereInput
  /**
   * Limit how many Pelanggans to delete.
   */
  limit?: number
}

/**
 * Pelanggan.sesi_pemesanan
 */
export type Pelanggan$sesi_pemesananArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesiPemesanan
   */
  select?: Prisma.SesiPemesananSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SesiPemesanan
   */
  omit?: Prisma.SesiPemesananOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SesiPemesananInclude<ExtArgs> | null
  where?: Prisma.SesiPemesananWhereInput
  orderBy?: Prisma.SesiPemesananOrderByWithRelationInput | Prisma.SesiPemesananOrderByWithRelationInput[]
  cursor?: Prisma.SesiPemesananWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SesiPemesananScalarFieldEnum | Prisma.SesiPemesananScalarFieldEnum[]
}

/**
 * Pelanggan without action
 */
export type PelangganDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pelanggan
   */
  select?: Prisma.PelangganSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pelanggan
   */
  omit?: Prisma.PelangganOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PelangganInclude<ExtArgs> | null
}
