
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SesiPemesanan` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SesiPemesanan
 * 
 */
export type SesiPemesananModel = runtime.Types.Result.DefaultSelection<Prisma.$SesiPemesananPayload>

export type AggregateSesiPemesanan = {
  _count: SesiPemesananCountAggregateOutputType | null
  _min: SesiPemesananMinAggregateOutputType | null
  _max: SesiPemesananMaxAggregateOutputType | null
}

export type SesiPemesananMinAggregateOutputType = {
  id_sesi: string | null
  no_meja: string | null
  id_pelanggan: string | null
  tanggal_pemesanan: Date | null
  status_sesi: $Enums.StatusSesi | null
}

export type SesiPemesananMaxAggregateOutputType = {
  id_sesi: string | null
  no_meja: string | null
  id_pelanggan: string | null
  tanggal_pemesanan: Date | null
  status_sesi: $Enums.StatusSesi | null
}

export type SesiPemesananCountAggregateOutputType = {
  id_sesi: number
  no_meja: number
  id_pelanggan: number
  tanggal_pemesanan: number
  status_sesi: number
  _all: number
}


export type SesiPemesananMinAggregateInputType = {
  id_sesi?: true
  no_meja?: true
  id_pelanggan?: true
  tanggal_pemesanan?: true
  status_sesi?: true
}

export type SesiPemesananMaxAggregateInputType = {
  id_sesi?: true
  no_meja?: true
  id_pelanggan?: true
  tanggal_pemesanan?: true
  status_sesi?: true
}

export type SesiPemesananCountAggregateInputType = {
  id_sesi?: true
  no_meja?: true
  id_pelanggan?: true
  tanggal_pemesanan?: true
  status_sesi?: true
  _all?: true
}

export type SesiPemesananAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SesiPemesanan to aggregate.
   */
  where?: Prisma.SesiPemesananWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SesiPemesanans to fetch.
   */
  orderBy?: Prisma.SesiPemesananOrderByWithRelationInput | Prisma.SesiPemesananOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SesiPemesananWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SesiPemesanans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SesiPemesanans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SesiPemesanans
  **/
  _count?: true | SesiPemesananCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SesiPemesananMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SesiPemesananMaxAggregateInputType
}

export type GetSesiPemesananAggregateType<T extends SesiPemesananAggregateArgs> = {
      [P in keyof T & keyof AggregateSesiPemesanan]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSesiPemesanan[P]>
    : Prisma.GetScalarType<T[P], AggregateSesiPemesanan[P]>
}




export type SesiPemesananGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SesiPemesananWhereInput
  orderBy?: Prisma.SesiPemesananOrderByWithAggregationInput | Prisma.SesiPemesananOrderByWithAggregationInput[]
  by: Prisma.SesiPemesananScalarFieldEnum[] | Prisma.SesiPemesananScalarFieldEnum
  having?: Prisma.SesiPemesananScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SesiPemesananCountAggregateInputType | true
  _min?: SesiPemesananMinAggregateInputType
  _max?: SesiPemesananMaxAggregateInputType
}

export type SesiPemesananGroupByOutputType = {
  id_sesi: string
  no_meja: string | null
  id_pelanggan: string | null
  tanggal_pemesanan: Date | null
  status_sesi: $Enums.StatusSesi | null
  _count: SesiPemesananCountAggregateOutputType | null
  _min: SesiPemesananMinAggregateOutputType | null
  _max: SesiPemesananMaxAggregateOutputType | null
}

type GetSesiPemesananGroupByPayload<T extends SesiPemesananGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SesiPemesananGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SesiPemesananGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SesiPemesananGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SesiPemesananGroupByOutputType[P]>
      }
    >
  >



export type SesiPemesananWhereInput = {
  AND?: Prisma.SesiPemesananWhereInput | Prisma.SesiPemesananWhereInput[]
  OR?: Prisma.SesiPemesananWhereInput[]
  NOT?: Prisma.SesiPemesananWhereInput | Prisma.SesiPemesananWhereInput[]
  id_sesi?: Prisma.StringFilter<"SesiPemesanan"> | string
  no_meja?: Prisma.StringNullableFilter<"SesiPemesanan"> | string | null
  id_pelanggan?: Prisma.StringNullableFilter<"SesiPemesanan"> | string | null
  tanggal_pemesanan?: Prisma.DateTimeNullableFilter<"SesiPemesanan"> | Date | string | null
  status_sesi?: Prisma.EnumStatusSesiNullableFilter<"SesiPemesanan"> | $Enums.StatusSesi | null
  pelanggan?: Prisma.XOR<Prisma.PelangganNullableScalarRelationFilter, Prisma.PelangganWhereInput> | null
  meja?: Prisma.MejaListRelationFilter
  transaksi?: Prisma.TransaksiListRelationFilter
}

export type SesiPemesananOrderByWithRelationInput = {
  id_sesi?: Prisma.SortOrder
  no_meja?: Prisma.SortOrderInput | Prisma.SortOrder
  id_pelanggan?: Prisma.SortOrderInput | Prisma.SortOrder
  tanggal_pemesanan?: Prisma.SortOrderInput | Prisma.SortOrder
  status_sesi?: Prisma.SortOrderInput | Prisma.SortOrder
  pelanggan?: Prisma.PelangganOrderByWithRelationInput
  meja?: Prisma.MejaOrderByRelationAggregateInput
  transaksi?: Prisma.TransaksiOrderByRelationAggregateInput
}

export type SesiPemesananWhereUniqueInput = Prisma.AtLeast<{
  id_sesi?: string
  AND?: Prisma.SesiPemesananWhereInput | Prisma.SesiPemesananWhereInput[]
  OR?: Prisma.SesiPemesananWhereInput[]
  NOT?: Prisma.SesiPemesananWhereInput | Prisma.SesiPemesananWhereInput[]
  no_meja?: Prisma.StringNullableFilter<"SesiPemesanan"> | string | null
  id_pelanggan?: Prisma.StringNullableFilter<"SesiPemesanan"> | string | null
  tanggal_pemesanan?: Prisma.DateTimeNullableFilter<"SesiPemesanan"> | Date | string | null
  status_sesi?: Prisma.EnumStatusSesiNullableFilter<"SesiPemesanan"> | $Enums.StatusSesi | null
  pelanggan?: Prisma.XOR<Prisma.PelangganNullableScalarRelationFilter, Prisma.PelangganWhereInput> | null
  meja?: Prisma.MejaListRelationFilter
  transaksi?: Prisma.TransaksiListRelationFilter
}, "id_sesi">

export type SesiPemesananOrderByWithAggregationInput = {
  id_sesi?: Prisma.SortOrder
  no_meja?: Prisma.SortOrderInput | Prisma.SortOrder
  id_pelanggan?: Prisma.SortOrderInput | Prisma.SortOrder
  tanggal_pemesanan?: Prisma.SortOrderInput | Prisma.SortOrder
  status_sesi?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.SesiPemesananCountOrderByAggregateInput
  _max?: Prisma.SesiPemesananMaxOrderByAggregateInput
  _min?: Prisma.SesiPemesananMinOrderByAggregateInput
}

export type SesiPemesananScalarWhereWithAggregatesInput = {
  AND?: Prisma.SesiPemesananScalarWhereWithAggregatesInput | Prisma.SesiPemesananScalarWhereWithAggregatesInput[]
  OR?: Prisma.SesiPemesananScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SesiPemesananScalarWhereWithAggregatesInput | Prisma.SesiPemesananScalarWhereWithAggregatesInput[]
  id_sesi?: Prisma.StringWithAggregatesFilter<"SesiPemesanan"> | string
  no_meja?: Prisma.StringNullableWithAggregatesFilter<"SesiPemesanan"> | string | null
  id_pelanggan?: Prisma.StringNullableWithAggregatesFilter<"SesiPemesanan"> | string | null
  tanggal_pemesanan?: Prisma.DateTimeNullableWithAggregatesFilter<"SesiPemesanan"> | Date | string | null
  status_sesi?: Prisma.EnumStatusSesiNullableWithAggregatesFilter<"SesiPemesanan"> | $Enums.StatusSesi | null
}

export type SesiPemesananCreateInput = {
  id_sesi: string
  no_meja?: string | null
  tanggal_pemesanan?: Date | string | null
  status_sesi?: $Enums.StatusSesi | null
  pelanggan?: Prisma.PelangganCreateNestedOneWithoutSesi_pemesananInput
  meja?: Prisma.MejaCreateNestedManyWithoutSesiInput
  transaksi?: Prisma.TransaksiCreateNestedManyWithoutSesiInput
}

export type SesiPemesananUncheckedCreateInput = {
  id_sesi: string
  no_meja?: string | null
  id_pelanggan?: string | null
  tanggal_pemesanan?: Date | string | null
  status_sesi?: $Enums.StatusSesi | null
  meja?: Prisma.MejaUncheckedCreateNestedManyWithoutSesiInput
  transaksi?: Prisma.TransaksiUncheckedCreateNestedManyWithoutSesiInput
}

export type SesiPemesananUpdateInput = {
  id_sesi?: Prisma.StringFieldUpdateOperationsInput | string
  no_meja?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tanggal_pemesanan?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status_sesi?: Prisma.NullableEnumStatusSesiFieldUpdateOperationsInput | $Enums.StatusSesi | null
  pelanggan?: Prisma.PelangganUpdateOneWithoutSesi_pemesananNestedInput
  meja?: Prisma.MejaUpdateManyWithoutSesiNestedInput
  transaksi?: Prisma.TransaksiUpdateManyWithoutSesiNestedInput
}

export type SesiPemesananUncheckedUpdateInput = {
  id_sesi?: Prisma.StringFieldUpdateOperationsInput | string
  no_meja?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  id_pelanggan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tanggal_pemesanan?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status_sesi?: Prisma.NullableEnumStatusSesiFieldUpdateOperationsInput | $Enums.StatusSesi | null
  meja?: Prisma.MejaUncheckedUpdateManyWithoutSesiNestedInput
  transaksi?: Prisma.TransaksiUncheckedUpdateManyWithoutSesiNestedInput
}

export type SesiPemesananCreateManyInput = {
  id_sesi: string
  no_meja?: string | null
  id_pelanggan?: string | null
  tanggal_pemesanan?: Date | string | null
  status_sesi?: $Enums.StatusSesi | null
}

export type SesiPemesananUpdateManyMutationInput = {
  id_sesi?: Prisma.StringFieldUpdateOperationsInput | string
  no_meja?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tanggal_pemesanan?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status_sesi?: Prisma.NullableEnumStatusSesiFieldUpdateOperationsInput | $Enums.StatusSesi | null
}

export type SesiPemesananUncheckedUpdateManyInput = {
  id_sesi?: Prisma.StringFieldUpdateOperationsInput | string
  no_meja?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  id_pelanggan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tanggal_pemesanan?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status_sesi?: Prisma.NullableEnumStatusSesiFieldUpdateOperationsInput | $Enums.StatusSesi | null
}

export type SesiPemesananListRelationFilter = {
  every?: Prisma.SesiPemesananWhereInput
  some?: Prisma.SesiPemesananWhereInput
  none?: Prisma.SesiPemesananWhereInput
}

export type SesiPemesananOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SesiPemesananCountOrderByAggregateInput = {
  id_sesi?: Prisma.SortOrder
  no_meja?: Prisma.SortOrder
  id_pelanggan?: Prisma.SortOrder
  tanggal_pemesanan?: Prisma.SortOrder
  status_sesi?: Prisma.SortOrder
}

export type SesiPemesananMaxOrderByAggregateInput = {
  id_sesi?: Prisma.SortOrder
  no_meja?: Prisma.SortOrder
  id_pelanggan?: Prisma.SortOrder
  tanggal_pemesanan?: Prisma.SortOrder
  status_sesi?: Prisma.SortOrder
}

export type SesiPemesananMinOrderByAggregateInput = {
  id_sesi?: Prisma.SortOrder
  no_meja?: Prisma.SortOrder
  id_pelanggan?: Prisma.SortOrder
  tanggal_pemesanan?: Prisma.SortOrder
  status_sesi?: Prisma.SortOrder
}

export type SesiPemesananScalarRelationFilter = {
  is?: Prisma.SesiPemesananWhereInput
  isNot?: Prisma.SesiPemesananWhereInput
}

export type SesiPemesananNullableScalarRelationFilter = {
  is?: Prisma.SesiPemesananWhereInput | null
  isNot?: Prisma.SesiPemesananWhereInput | null
}

export type SesiPemesananCreateNestedManyWithoutPelangganInput = {
  create?: Prisma.XOR<Prisma.SesiPemesananCreateWithoutPelangganInput, Prisma.SesiPemesananUncheckedCreateWithoutPelangganInput> | Prisma.SesiPemesananCreateWithoutPelangganInput[] | Prisma.SesiPemesananUncheckedCreateWithoutPelangganInput[]
  connectOrCreate?: Prisma.SesiPemesananCreateOrConnectWithoutPelangganInput | Prisma.SesiPemesananCreateOrConnectWithoutPelangganInput[]
  createMany?: Prisma.SesiPemesananCreateManyPelangganInputEnvelope
  connect?: Prisma.SesiPemesananWhereUniqueInput | Prisma.SesiPemesananWhereUniqueInput[]
}

export type SesiPemesananUncheckedCreateNestedManyWithoutPelangganInput = {
  create?: Prisma.XOR<Prisma.SesiPemesananCreateWithoutPelangganInput, Prisma.SesiPemesananUncheckedCreateWithoutPelangganInput> | Prisma.SesiPemesananCreateWithoutPelangganInput[] | Prisma.SesiPemesananUncheckedCreateWithoutPelangganInput[]
  connectOrCreate?: Prisma.SesiPemesananCreateOrConnectWithoutPelangganInput | Prisma.SesiPemesananCreateOrConnectWithoutPelangganInput[]
  createMany?: Prisma.SesiPemesananCreateManyPelangganInputEnvelope
  connect?: Prisma.SesiPemesananWhereUniqueInput | Prisma.SesiPemesananWhereUniqueInput[]
}

export type SesiPemesananUpdateManyWithoutPelangganNestedInput = {
  create?: Prisma.XOR<Prisma.SesiPemesananCreateWithoutPelangganInput, Prisma.SesiPemesananUncheckedCreateWithoutPelangganInput> | Prisma.SesiPemesananCreateWithoutPelangganInput[] | Prisma.SesiPemesananUncheckedCreateWithoutPelangganInput[]
  connectOrCreate?: Prisma.SesiPemesananCreateOrConnectWithoutPelangganInput | Prisma.SesiPemesananCreateOrConnectWithoutPelangganInput[]
  upsert?: Prisma.SesiPemesananUpsertWithWhereUniqueWithoutPelangganInput | Prisma.SesiPemesananUpsertWithWhereUniqueWithoutPelangganInput[]
  createMany?: Prisma.SesiPemesananCreateManyPelangganInputEnvelope
  set?: Prisma.SesiPemesananWhereUniqueInput | Prisma.SesiPemesananWhereUniqueInput[]
  disconnect?: Prisma.SesiPemesananWhereUniqueInput | Prisma.SesiPemesananWhereUniqueInput[]
  delete?: Prisma.SesiPemesananWhereUniqueInput | Prisma.SesiPemesananWhereUniqueInput[]
  connect?: Prisma.SesiPemesananWhereUniqueInput | Prisma.SesiPemesananWhereUniqueInput[]
  update?: Prisma.SesiPemesananUpdateWithWhereUniqueWithoutPelangganInput | Prisma.SesiPemesananUpdateWithWhereUniqueWithoutPelangganInput[]
  updateMany?: Prisma.SesiPemesananUpdateManyWithWhereWithoutPelangganInput | Prisma.SesiPemesananUpdateManyWithWhereWithoutPelangganInput[]
  deleteMany?: Prisma.SesiPemesananScalarWhereInput | Prisma.SesiPemesananScalarWhereInput[]
}

export type SesiPemesananUncheckedUpdateManyWithoutPelangganNestedInput = {
  create?: Prisma.XOR<Prisma.SesiPemesananCreateWithoutPelangganInput, Prisma.SesiPemesananUncheckedCreateWithoutPelangganInput> | Prisma.SesiPemesananCreateWithoutPelangganInput[] | Prisma.SesiPemesananUncheckedCreateWithoutPelangganInput[]
  connectOrCreate?: Prisma.SesiPemesananCreateOrConnectWithoutPelangganInput | Prisma.SesiPemesananCreateOrConnectWithoutPelangganInput[]
  upsert?: Prisma.SesiPemesananUpsertWithWhereUniqueWithoutPelangganInput | Prisma.SesiPemesananUpsertWithWhereUniqueWithoutPelangganInput[]
  createMany?: Prisma.SesiPemesananCreateManyPelangganInputEnvelope
  set?: Prisma.SesiPemesananWhereUniqueInput | Prisma.SesiPemesananWhereUniqueInput[]
  disconnect?: Prisma.SesiPemesananWhereUniqueInput | Prisma.SesiPemesananWhereUniqueInput[]
  delete?: Prisma.SesiPemesananWhereUniqueInput | Prisma.SesiPemesananWhereUniqueInput[]
  connect?: Prisma.SesiPemesananWhereUniqueInput | Prisma.SesiPemesananWhereUniqueInput[]
  update?: Prisma.SesiPemesananUpdateWithWhereUniqueWithoutPelangganInput | Prisma.SesiPemesananUpdateWithWhereUniqueWithoutPelangganInput[]
  updateMany?: Prisma.SesiPemesananUpdateManyWithWhereWithoutPelangganInput | Prisma.SesiPemesananUpdateManyWithWhereWithoutPelangganInput[]
  deleteMany?: Prisma.SesiPemesananScalarWhereInput | Prisma.SesiPemesananScalarWhereInput[]
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type NullableEnumStatusSesiFieldUpdateOperationsInput = {
  set?: $Enums.StatusSesi | null
}

export type SesiPemesananCreateNestedOneWithoutMejaInput = {
  create?: Prisma.XOR<Prisma.SesiPemesananCreateWithoutMejaInput, Prisma.SesiPemesananUncheckedCreateWithoutMejaInput>
  connectOrCreate?: Prisma.SesiPemesananCreateOrConnectWithoutMejaInput
  connect?: Prisma.SesiPemesananWhereUniqueInput
}

export type SesiPemesananUpdateOneRequiredWithoutMejaNestedInput = {
  create?: Prisma.XOR<Prisma.SesiPemesananCreateWithoutMejaInput, Prisma.SesiPemesananUncheckedCreateWithoutMejaInput>
  connectOrCreate?: Prisma.SesiPemesananCreateOrConnectWithoutMejaInput
  upsert?: Prisma.SesiPemesananUpsertWithoutMejaInput
  connect?: Prisma.SesiPemesananWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SesiPemesananUpdateToOneWithWhereWithoutMejaInput, Prisma.SesiPemesananUpdateWithoutMejaInput>, Prisma.SesiPemesananUncheckedUpdateWithoutMejaInput>
}

export type SesiPemesananCreateNestedOneWithoutTransaksiInput = {
  create?: Prisma.XOR<Prisma.SesiPemesananCreateWithoutTransaksiInput, Prisma.SesiPemesananUncheckedCreateWithoutTransaksiInput>
  connectOrCreate?: Prisma.SesiPemesananCreateOrConnectWithoutTransaksiInput
  connect?: Prisma.SesiPemesananWhereUniqueInput
}

export type SesiPemesananUpdateOneWithoutTransaksiNestedInput = {
  create?: Prisma.XOR<Prisma.SesiPemesananCreateWithoutTransaksiInput, Prisma.SesiPemesananUncheckedCreateWithoutTransaksiInput>
  connectOrCreate?: Prisma.SesiPemesananCreateOrConnectWithoutTransaksiInput
  upsert?: Prisma.SesiPemesananUpsertWithoutTransaksiInput
  disconnect?: Prisma.SesiPemesananWhereInput | boolean
  delete?: Prisma.SesiPemesananWhereInput | boolean
  connect?: Prisma.SesiPemesananWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SesiPemesananUpdateToOneWithWhereWithoutTransaksiInput, Prisma.SesiPemesananUpdateWithoutTransaksiInput>, Prisma.SesiPemesananUncheckedUpdateWithoutTransaksiInput>
}

export type SesiPemesananCreateWithoutPelangganInput = {
  id_sesi: string
  no_meja?: string | null
  tanggal_pemesanan?: Date | string | null
  status_sesi?: $Enums.StatusSesi | null
  meja?: Prisma.MejaCreateNestedManyWithoutSesiInput
  transaksi?: Prisma.TransaksiCreateNestedManyWithoutSesiInput
}

export type SesiPemesananUncheckedCreateWithoutPelangganInput = {
  id_sesi: string
  no_meja?: string | null
  tanggal_pemesanan?: Date | string | null
  status_sesi?: $Enums.StatusSesi | null
  meja?: Prisma.MejaUncheckedCreateNestedManyWithoutSesiInput
  transaksi?: Prisma.TransaksiUncheckedCreateNestedManyWithoutSesiInput
}

export type SesiPemesananCreateOrConnectWithoutPelangganInput = {
  where: Prisma.SesiPemesananWhereUniqueInput
  create: Prisma.XOR<Prisma.SesiPemesananCreateWithoutPelangganInput, Prisma.SesiPemesananUncheckedCreateWithoutPelangganInput>
}

export type SesiPemesananCreateManyPelangganInputEnvelope = {
  data: Prisma.SesiPemesananCreateManyPelangganInput | Prisma.SesiPemesananCreateManyPelangganInput[]
  skipDuplicates?: boolean
}

export type SesiPemesananUpsertWithWhereUniqueWithoutPelangganInput = {
  where: Prisma.SesiPemesananWhereUniqueInput
  update: Prisma.XOR<Prisma.SesiPemesananUpdateWithoutPelangganInput, Prisma.SesiPemesananUncheckedUpdateWithoutPelangganInput>
  create: Prisma.XOR<Prisma.SesiPemesananCreateWithoutPelangganInput, Prisma.SesiPemesananUncheckedCreateWithoutPelangganInput>
}

export type SesiPemesananUpdateWithWhereUniqueWithoutPelangganInput = {
  where: Prisma.SesiPemesananWhereUniqueInput
  data: Prisma.XOR<Prisma.SesiPemesananUpdateWithoutPelangganInput, Prisma.SesiPemesananUncheckedUpdateWithoutPelangganInput>
}

export type SesiPemesananUpdateManyWithWhereWithoutPelangganInput = {
  where: Prisma.SesiPemesananScalarWhereInput
  data: Prisma.XOR<Prisma.SesiPemesananUpdateManyMutationInput, Prisma.SesiPemesananUncheckedUpdateManyWithoutPelangganInput>
}

export type SesiPemesananScalarWhereInput = {
  AND?: Prisma.SesiPemesananScalarWhereInput | Prisma.SesiPemesananScalarWhereInput[]
  OR?: Prisma.SesiPemesananScalarWhereInput[]
  NOT?: Prisma.SesiPemesananScalarWhereInput | Prisma.SesiPemesananScalarWhereInput[]
  id_sesi?: Prisma.StringFilter<"SesiPemesanan"> | string
  no_meja?: Prisma.StringNullableFilter<"SesiPemesanan"> | string | null
  id_pelanggan?: Prisma.StringNullableFilter<"SesiPemesanan"> | string | null
  tanggal_pemesanan?: Prisma.DateTimeNullableFilter<"SesiPemesanan"> | Date | string | null
  status_sesi?: Prisma.EnumStatusSesiNullableFilter<"SesiPemesanan"> | $Enums.StatusSesi | null
}

export type SesiPemesananCreateWithoutMejaInput = {
  id_sesi: string
  no_meja?: string | null
  tanggal_pemesanan?: Date | string | null
  status_sesi?: $Enums.StatusSesi | null
  pelanggan?: Prisma.PelangganCreateNestedOneWithoutSesi_pemesananInput
  transaksi?: Prisma.TransaksiCreateNestedManyWithoutSesiInput
}

export type SesiPemesananUncheckedCreateWithoutMejaInput = {
  id_sesi: string
  no_meja?: string | null
  id_pelanggan?: string | null
  tanggal_pemesanan?: Date | string | null
  status_sesi?: $Enums.StatusSesi | null
  transaksi?: Prisma.TransaksiUncheckedCreateNestedManyWithoutSesiInput
}

export type SesiPemesananCreateOrConnectWithoutMejaInput = {
  where: Prisma.SesiPemesananWhereUniqueInput
  create: Prisma.XOR<Prisma.SesiPemesananCreateWithoutMejaInput, Prisma.SesiPemesananUncheckedCreateWithoutMejaInput>
}

export type SesiPemesananUpsertWithoutMejaInput = {
  update: Prisma.XOR<Prisma.SesiPemesananUpdateWithoutMejaInput, Prisma.SesiPemesananUncheckedUpdateWithoutMejaInput>
  create: Prisma.XOR<Prisma.SesiPemesananCreateWithoutMejaInput, Prisma.SesiPemesananUncheckedCreateWithoutMejaInput>
  where?: Prisma.SesiPemesananWhereInput
}

export type SesiPemesananUpdateToOneWithWhereWithoutMejaInput = {
  where?: Prisma.SesiPemesananWhereInput
  data: Prisma.XOR<Prisma.SesiPemesananUpdateWithoutMejaInput, Prisma.SesiPemesananUncheckedUpdateWithoutMejaInput>
}

export type SesiPemesananUpdateWithoutMejaInput = {
  id_sesi?: Prisma.StringFieldUpdateOperationsInput | string
  no_meja?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tanggal_pemesanan?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status_sesi?: Prisma.NullableEnumStatusSesiFieldUpdateOperationsInput | $Enums.StatusSesi | null
  pelanggan?: Prisma.PelangganUpdateOneWithoutSesi_pemesananNestedInput
  transaksi?: Prisma.TransaksiUpdateManyWithoutSesiNestedInput
}

export type SesiPemesananUncheckedUpdateWithoutMejaInput = {
  id_sesi?: Prisma.StringFieldUpdateOperationsInput | string
  no_meja?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  id_pelanggan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tanggal_pemesanan?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status_sesi?: Prisma.NullableEnumStatusSesiFieldUpdateOperationsInput | $Enums.StatusSesi | null
  transaksi?: Prisma.TransaksiUncheckedUpdateManyWithoutSesiNestedInput
}

export type SesiPemesananCreateWithoutTransaksiInput = {
  id_sesi: string
  no_meja?: string | null
  tanggal_pemesanan?: Date | string | null
  status_sesi?: $Enums.StatusSesi | null
  pelanggan?: Prisma.PelangganCreateNestedOneWithoutSesi_pemesananInput
  meja?: Prisma.MejaCreateNestedManyWithoutSesiInput
}

export type SesiPemesananUncheckedCreateWithoutTransaksiInput = {
  id_sesi: string
  no_meja?: string | null
  id_pelanggan?: string | null
  tanggal_pemesanan?: Date | string | null
  status_sesi?: $Enums.StatusSesi | null
  meja?: Prisma.MejaUncheckedCreateNestedManyWithoutSesiInput
}

export type SesiPemesananCreateOrConnectWithoutTransaksiInput = {
  where: Prisma.SesiPemesananWhereUniqueInput
  create: Prisma.XOR<Prisma.SesiPemesananCreateWithoutTransaksiInput, Prisma.SesiPemesananUncheckedCreateWithoutTransaksiInput>
}

export type SesiPemesananUpsertWithoutTransaksiInput = {
  update: Prisma.XOR<Prisma.SesiPemesananUpdateWithoutTransaksiInput, Prisma.SesiPemesananUncheckedUpdateWithoutTransaksiInput>
  create: Prisma.XOR<Prisma.SesiPemesananCreateWithoutTransaksiInput, Prisma.SesiPemesananUncheckedCreateWithoutTransaksiInput>
  where?: Prisma.SesiPemesananWhereInput
}

export type SesiPemesananUpdateToOneWithWhereWithoutTransaksiInput = {
  where?: Prisma.SesiPemesananWhereInput
  data: Prisma.XOR<Prisma.SesiPemesananUpdateWithoutTransaksiInput, Prisma.SesiPemesananUncheckedUpdateWithoutTransaksiInput>
}

export type SesiPemesananUpdateWithoutTransaksiInput = {
  id_sesi?: Prisma.StringFieldUpdateOperationsInput | string
  no_meja?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tanggal_pemesanan?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status_sesi?: Prisma.NullableEnumStatusSesiFieldUpdateOperationsInput | $Enums.StatusSesi | null
  pelanggan?: Prisma.PelangganUpdateOneWithoutSesi_pemesananNestedInput
  meja?: Prisma.MejaUpdateManyWithoutSesiNestedInput
}

export type SesiPemesananUncheckedUpdateWithoutTransaksiInput = {
  id_sesi?: Prisma.StringFieldUpdateOperationsInput | string
  no_meja?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  id_pelanggan?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tanggal_pemesanan?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status_sesi?: Prisma.NullableEnumStatusSesiFieldUpdateOperationsInput | $Enums.StatusSesi | null
  meja?: Prisma.MejaUncheckedUpdateManyWithoutSesiNestedInput
}

export type SesiPemesananCreateManyPelangganInput = {
  id_sesi: string
  no_meja?: string | null
  tanggal_pemesanan?: Date | string | null
  status_sesi?: $Enums.StatusSesi | null
}

export type SesiPemesananUpdateWithoutPelangganInput = {
  id_sesi?: Prisma.StringFieldUpdateOperationsInput | string
  no_meja?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tanggal_pemesanan?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status_sesi?: Prisma.NullableEnumStatusSesiFieldUpdateOperationsInput | $Enums.StatusSesi | null
  meja?: Prisma.MejaUpdateManyWithoutSesiNestedInput
  transaksi?: Prisma.TransaksiUpdateManyWithoutSesiNestedInput
}

export type SesiPemesananUncheckedUpdateWithoutPelangganInput = {
  id_sesi?: Prisma.StringFieldUpdateOperationsInput | string
  no_meja?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tanggal_pemesanan?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status_sesi?: Prisma.NullableEnumStatusSesiFieldUpdateOperationsInput | $Enums.StatusSesi | null
  meja?: Prisma.MejaUncheckedUpdateManyWithoutSesiNestedInput
  transaksi?: Prisma.TransaksiUncheckedUpdateManyWithoutSesiNestedInput
}

export type SesiPemesananUncheckedUpdateManyWithoutPelangganInput = {
  id_sesi?: Prisma.StringFieldUpdateOperationsInput | string
  no_meja?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tanggal_pemesanan?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status_sesi?: Prisma.NullableEnumStatusSesiFieldUpdateOperationsInput | $Enums.StatusSesi | null
}


/**
 * Count Type SesiPemesananCountOutputType
 */

export type SesiPemesananCountOutputType = {
  meja: number
  transaksi: number
}

export type SesiPemesananCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  meja?: boolean | SesiPemesananCountOutputTypeCountMejaArgs
  transaksi?: boolean | SesiPemesananCountOutputTypeCountTransaksiArgs
}

/**
 * SesiPemesananCountOutputType without action
 */
export type SesiPemesananCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesiPemesananCountOutputType
   */
  select?: Prisma.SesiPemesananCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SesiPemesananCountOutputType without action
 */
export type SesiPemesananCountOutputTypeCountMejaArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MejaWhereInput
}

/**
 * SesiPemesananCountOutputType without action
 */
export type SesiPemesananCountOutputTypeCountTransaksiArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TransaksiWhereInput
}


export type SesiPemesananSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id_sesi?: boolean
  no_meja?: boolean
  id_pelanggan?: boolean
  tanggal_pemesanan?: boolean
  status_sesi?: boolean
  pelanggan?: boolean | Prisma.SesiPemesanan$pelangganArgs<ExtArgs>
  meja?: boolean | Prisma.SesiPemesanan$mejaArgs<ExtArgs>
  transaksi?: boolean | Prisma.SesiPemesanan$transaksiArgs<ExtArgs>
  _count?: boolean | Prisma.SesiPemesananCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sesiPemesanan"]>

export type SesiPemesananSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id_sesi?: boolean
  no_meja?: boolean
  id_pelanggan?: boolean
  tanggal_pemesanan?: boolean
  status_sesi?: boolean
  pelanggan?: boolean | Prisma.SesiPemesanan$pelangganArgs<ExtArgs>
}, ExtArgs["result"]["sesiPemesanan"]>

export type SesiPemesananSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id_sesi?: boolean
  no_meja?: boolean
  id_pelanggan?: boolean
  tanggal_pemesanan?: boolean
  status_sesi?: boolean
  pelanggan?: boolean | Prisma.SesiPemesanan$pelangganArgs<ExtArgs>
}, ExtArgs["result"]["sesiPemesanan"]>

export type SesiPemesananSelectScalar = {
  id_sesi?: boolean
  no_meja?: boolean
  id_pelanggan?: boolean
  tanggal_pemesanan?: boolean
  status_sesi?: boolean
}

export type SesiPemesananOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id_sesi" | "no_meja" | "id_pelanggan" | "tanggal_pemesanan" | "status_sesi", ExtArgs["result"]["sesiPemesanan"]>
export type SesiPemesananInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pelanggan?: boolean | Prisma.SesiPemesanan$pelangganArgs<ExtArgs>
  meja?: boolean | Prisma.SesiPemesanan$mejaArgs<ExtArgs>
  transaksi?: boolean | Prisma.SesiPemesanan$transaksiArgs<ExtArgs>
  _count?: boolean | Prisma.SesiPemesananCountOutputTypeDefaultArgs<ExtArgs>
}
export type SesiPemesananIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pelanggan?: boolean | Prisma.SesiPemesanan$pelangganArgs<ExtArgs>
}
export type SesiPemesananIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pelanggan?: boolean | Prisma.SesiPemesanan$pelangganArgs<ExtArgs>
}

export type $SesiPemesananPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SesiPemesanan"
  objects: {
    pelanggan: Prisma.$PelangganPayload<ExtArgs> | null
    meja: Prisma.$MejaPayload<ExtArgs>[]
    transaksi: Prisma.$TransaksiPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id_sesi: string
    no_meja: string | null
    id_pelanggan: string | null
    tanggal_pemesanan: Date | null
    status_sesi: $Enums.StatusSesi | null
  }, ExtArgs["result"]["sesiPemesanan"]>
  composites: {}
}

export type SesiPemesananGetPayload<S extends boolean | null | undefined | SesiPemesananDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SesiPemesananPayload, S>

export type SesiPemesananCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SesiPemesananFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SesiPemesananCountAggregateInputType | true
  }

export interface SesiPemesananDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SesiPemesanan'], meta: { name: 'SesiPemesanan' } }
  /**
   * Find zero or one SesiPemesanan that matches the filter.
   * @param {SesiPemesananFindUniqueArgs} args - Arguments to find a SesiPemesanan
   * @example
   * // Get one SesiPemesanan
   * const sesiPemesanan = await prisma.sesiPemesanan.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SesiPemesananFindUniqueArgs>(args: Prisma.SelectSubset<T, SesiPemesananFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SesiPemesananClient<runtime.Types.Result.GetResult<Prisma.$SesiPemesananPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SesiPemesanan that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SesiPemesananFindUniqueOrThrowArgs} args - Arguments to find a SesiPemesanan
   * @example
   * // Get one SesiPemesanan
   * const sesiPemesanan = await prisma.sesiPemesanan.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SesiPemesananFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SesiPemesananFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SesiPemesananClient<runtime.Types.Result.GetResult<Prisma.$SesiPemesananPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SesiPemesanan that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SesiPemesananFindFirstArgs} args - Arguments to find a SesiPemesanan
   * @example
   * // Get one SesiPemesanan
   * const sesiPemesanan = await prisma.sesiPemesanan.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SesiPemesananFindFirstArgs>(args?: Prisma.SelectSubset<T, SesiPemesananFindFirstArgs<ExtArgs>>): Prisma.Prisma__SesiPemesananClient<runtime.Types.Result.GetResult<Prisma.$SesiPemesananPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SesiPemesanan that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SesiPemesananFindFirstOrThrowArgs} args - Arguments to find a SesiPemesanan
   * @example
   * // Get one SesiPemesanan
   * const sesiPemesanan = await prisma.sesiPemesanan.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SesiPemesananFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SesiPemesananFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SesiPemesananClient<runtime.Types.Result.GetResult<Prisma.$SesiPemesananPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SesiPemesanans that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SesiPemesananFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SesiPemesanans
   * const sesiPemesanans = await prisma.sesiPemesanan.findMany()
   * 
   * // Get first 10 SesiPemesanans
   * const sesiPemesanans = await prisma.sesiPemesanan.findMany({ take: 10 })
   * 
   * // Only select the `id_sesi`
   * const sesiPemesananWithId_sesiOnly = await prisma.sesiPemesanan.findMany({ select: { id_sesi: true } })
   * 
   */
  findMany<T extends SesiPemesananFindManyArgs>(args?: Prisma.SelectSubset<T, SesiPemesananFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SesiPemesananPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SesiPemesanan.
   * @param {SesiPemesananCreateArgs} args - Arguments to create a SesiPemesanan.
   * @example
   * // Create one SesiPemesanan
   * const SesiPemesanan = await prisma.sesiPemesanan.create({
   *   data: {
   *     // ... data to create a SesiPemesanan
   *   }
   * })
   * 
   */
  create<T extends SesiPemesananCreateArgs>(args: Prisma.SelectSubset<T, SesiPemesananCreateArgs<ExtArgs>>): Prisma.Prisma__SesiPemesananClient<runtime.Types.Result.GetResult<Prisma.$SesiPemesananPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SesiPemesanans.
   * @param {SesiPemesananCreateManyArgs} args - Arguments to create many SesiPemesanans.
   * @example
   * // Create many SesiPemesanans
   * const sesiPemesanan = await prisma.sesiPemesanan.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SesiPemesananCreateManyArgs>(args?: Prisma.SelectSubset<T, SesiPemesananCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SesiPemesanans and returns the data saved in the database.
   * @param {SesiPemesananCreateManyAndReturnArgs} args - Arguments to create many SesiPemesanans.
   * @example
   * // Create many SesiPemesanans
   * const sesiPemesanan = await prisma.sesiPemesanan.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SesiPemesanans and only return the `id_sesi`
   * const sesiPemesananWithId_sesiOnly = await prisma.sesiPemesanan.createManyAndReturn({
   *   select: { id_sesi: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SesiPemesananCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SesiPemesananCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SesiPemesananPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SesiPemesanan.
   * @param {SesiPemesananDeleteArgs} args - Arguments to delete one SesiPemesanan.
   * @example
   * // Delete one SesiPemesanan
   * const SesiPemesanan = await prisma.sesiPemesanan.delete({
   *   where: {
   *     // ... filter to delete one SesiPemesanan
   *   }
   * })
   * 
   */
  delete<T extends SesiPemesananDeleteArgs>(args: Prisma.SelectSubset<T, SesiPemesananDeleteArgs<ExtArgs>>): Prisma.Prisma__SesiPemesananClient<runtime.Types.Result.GetResult<Prisma.$SesiPemesananPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SesiPemesanan.
   * @param {SesiPemesananUpdateArgs} args - Arguments to update one SesiPemesanan.
   * @example
   * // Update one SesiPemesanan
   * const sesiPemesanan = await prisma.sesiPemesanan.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SesiPemesananUpdateArgs>(args: Prisma.SelectSubset<T, SesiPemesananUpdateArgs<ExtArgs>>): Prisma.Prisma__SesiPemesananClient<runtime.Types.Result.GetResult<Prisma.$SesiPemesananPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SesiPemesanans.
   * @param {SesiPemesananDeleteManyArgs} args - Arguments to filter SesiPemesanans to delete.
   * @example
   * // Delete a few SesiPemesanans
   * const { count } = await prisma.sesiPemesanan.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SesiPemesananDeleteManyArgs>(args?: Prisma.SelectSubset<T, SesiPemesananDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SesiPemesanans.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SesiPemesananUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SesiPemesanans
   * const sesiPemesanan = await prisma.sesiPemesanan.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SesiPemesananUpdateManyArgs>(args: Prisma.SelectSubset<T, SesiPemesananUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SesiPemesanans and returns the data updated in the database.
   * @param {SesiPemesananUpdateManyAndReturnArgs} args - Arguments to update many SesiPemesanans.
   * @example
   * // Update many SesiPemesanans
   * const sesiPemesanan = await prisma.sesiPemesanan.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SesiPemesanans and only return the `id_sesi`
   * const sesiPemesananWithId_sesiOnly = await prisma.sesiPemesanan.updateManyAndReturn({
   *   select: { id_sesi: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SesiPemesananUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SesiPemesananUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SesiPemesananPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SesiPemesanan.
   * @param {SesiPemesananUpsertArgs} args - Arguments to update or create a SesiPemesanan.
   * @example
   * // Update or create a SesiPemesanan
   * const sesiPemesanan = await prisma.sesiPemesanan.upsert({
   *   create: {
   *     // ... data to create a SesiPemesanan
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SesiPemesanan we want to update
   *   }
   * })
   */
  upsert<T extends SesiPemesananUpsertArgs>(args: Prisma.SelectSubset<T, SesiPemesananUpsertArgs<ExtArgs>>): Prisma.Prisma__SesiPemesananClient<runtime.Types.Result.GetResult<Prisma.$SesiPemesananPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SesiPemesanans.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SesiPemesananCountArgs} args - Arguments to filter SesiPemesanans to count.
   * @example
   * // Count the number of SesiPemesanans
   * const count = await prisma.sesiPemesanan.count({
   *   where: {
   *     // ... the filter for the SesiPemesanans we want to count
   *   }
   * })
  **/
  count<T extends SesiPemesananCountArgs>(
    args?: Prisma.Subset<T, SesiPemesananCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SesiPemesananCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SesiPemesanan.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SesiPemesananAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SesiPemesananAggregateArgs>(args: Prisma.Subset<T, SesiPemesananAggregateArgs>): Prisma.PrismaPromise<GetSesiPemesananAggregateType<T>>

  /**
   * Group by SesiPemesanan.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SesiPemesananGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SesiPemesananGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SesiPemesananGroupByArgs['orderBy'] }
      : { orderBy?: SesiPemesananGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SesiPemesananGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSesiPemesananGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SesiPemesanan model
 */
readonly fields: SesiPemesananFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SesiPemesanan.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SesiPemesananClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  pelanggan<T extends Prisma.SesiPemesanan$pelangganArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SesiPemesanan$pelangganArgs<ExtArgs>>): Prisma.Prisma__PelangganClient<runtime.Types.Result.GetResult<Prisma.$PelangganPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  meja<T extends Prisma.SesiPemesanan$mejaArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SesiPemesanan$mejaArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MejaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  transaksi<T extends Prisma.SesiPemesanan$transaksiArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SesiPemesanan$transaksiArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransaksiPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SesiPemesanan model
 */
export interface SesiPemesananFieldRefs {
  readonly id_sesi: Prisma.FieldRef<"SesiPemesanan", 'String'>
  readonly no_meja: Prisma.FieldRef<"SesiPemesanan", 'String'>
  readonly id_pelanggan: Prisma.FieldRef<"SesiPemesanan", 'String'>
  readonly tanggal_pemesanan: Prisma.FieldRef<"SesiPemesanan", 'DateTime'>
  readonly status_sesi: Prisma.FieldRef<"SesiPemesanan", 'StatusSesi'>
}
    

// Custom InputTypes
/**
 * SesiPemesanan findUnique
 */
export type SesiPemesananFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesiPemesanan
   */
  select?: Prisma.SesiPemesananSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SesiPemesanan
   */
  omit?: Prisma.SesiPemesananOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SesiPemesananInclude<ExtArgs> | null
  /**
   * Filter, which SesiPemesanan to fetch.
   */
  where: Prisma.SesiPemesananWhereUniqueInput
}

/**
 * SesiPemesanan findUniqueOrThrow
 */
export type SesiPemesananFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesiPemesanan
   */
  select?: Prisma.SesiPemesananSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SesiPemesanan
   */
  omit?: Prisma.SesiPemesananOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SesiPemesananInclude<ExtArgs> | null
  /**
   * Filter, which SesiPemesanan to fetch.
   */
  where: Prisma.SesiPemesananWhereUniqueInput
}

/**
 * SesiPemesanan findFirst
 */
export type SesiPemesananFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesiPemesanan
   */
  select?: Prisma.SesiPemesananSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SesiPemesanan
   */
  omit?: Prisma.SesiPemesananOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SesiPemesananInclude<ExtArgs> | null
  /**
   * Filter, which SesiPemesanan to fetch.
   */
  where?: Prisma.SesiPemesananWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SesiPemesanans to fetch.
   */
  orderBy?: Prisma.SesiPemesananOrderByWithRelationInput | Prisma.SesiPemesananOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SesiPemesanans.
   */
  cursor?: Prisma.SesiPemesananWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SesiPemesanans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SesiPemesanans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SesiPemesanans.
   */
  distinct?: Prisma.SesiPemesananScalarFieldEnum | Prisma.SesiPemesananScalarFieldEnum[]
}

/**
 * SesiPemesanan findFirstOrThrow
 */
export type SesiPemesananFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesiPemesanan
   */
  select?: Prisma.SesiPemesananSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SesiPemesanan
   */
  omit?: Prisma.SesiPemesananOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SesiPemesananInclude<ExtArgs> | null
  /**
   * Filter, which SesiPemesanan to fetch.
   */
  where?: Prisma.SesiPemesananWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SesiPemesanans to fetch.
   */
  orderBy?: Prisma.SesiPemesananOrderByWithRelationInput | Prisma.SesiPemesananOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SesiPemesanans.
   */
  cursor?: Prisma.SesiPemesananWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SesiPemesanans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SesiPemesanans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SesiPemesanans.
   */
  distinct?: Prisma.SesiPemesananScalarFieldEnum | Prisma.SesiPemesananScalarFieldEnum[]
}

/**
 * SesiPemesanan findMany
 */
export type SesiPemesananFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesiPemesanan
   */
  select?: Prisma.SesiPemesananSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SesiPemesanan
   */
  omit?: Prisma.SesiPemesananOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SesiPemesananInclude<ExtArgs> | null
  /**
   * Filter, which SesiPemesanans to fetch.
   */
  where?: Prisma.SesiPemesananWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SesiPemesanans to fetch.
   */
  orderBy?: Prisma.SesiPemesananOrderByWithRelationInput | Prisma.SesiPemesananOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SesiPemesanans.
   */
  cursor?: Prisma.SesiPemesananWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SesiPemesanans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SesiPemesanans.
   */
  skip?: number
  distinct?: Prisma.SesiPemesananScalarFieldEnum | Prisma.SesiPemesananScalarFieldEnum[]
}

/**
 * SesiPemesanan create
 */
export type SesiPemesananCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesiPemesanan
   */
  select?: Prisma.SesiPemesananSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SesiPemesanan
   */
  omit?: Prisma.SesiPemesananOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SesiPemesananInclude<ExtArgs> | null
  /**
   * The data needed to create a SesiPemesanan.
   */
  data: Prisma.XOR<Prisma.SesiPemesananCreateInput, Prisma.SesiPemesananUncheckedCreateInput>
}

/**
 * SesiPemesanan createMany
 */
export type SesiPemesananCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SesiPemesanans.
   */
  data: Prisma.SesiPemesananCreateManyInput | Prisma.SesiPemesananCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SesiPemesanan createManyAndReturn
 */
export type SesiPemesananCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesiPemesanan
   */
  select?: Prisma.SesiPemesananSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SesiPemesanan
   */
  omit?: Prisma.SesiPemesananOmit<ExtArgs> | null
  /**
   * The data used to create many SesiPemesanans.
   */
  data: Prisma.SesiPemesananCreateManyInput | Prisma.SesiPemesananCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SesiPemesananIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SesiPemesanan update
 */
export type SesiPemesananUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesiPemesanan
   */
  select?: Prisma.SesiPemesananSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SesiPemesanan
   */
  omit?: Prisma.SesiPemesananOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SesiPemesananInclude<ExtArgs> | null
  /**
   * The data needed to update a SesiPemesanan.
   */
  data: Prisma.XOR<Prisma.SesiPemesananUpdateInput, Prisma.SesiPemesananUncheckedUpdateInput>
  /**
   * Choose, which SesiPemesanan to update.
   */
  where: Prisma.SesiPemesananWhereUniqueInput
}

/**
 * SesiPemesanan updateMany
 */
export type SesiPemesananUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SesiPemesanans.
   */
  data: Prisma.XOR<Prisma.SesiPemesananUpdateManyMutationInput, Prisma.SesiPemesananUncheckedUpdateManyInput>
  /**
   * Filter which SesiPemesanans to update
   */
  where?: Prisma.SesiPemesananWhereInput
  /**
   * Limit how many SesiPemesanans to update.
   */
  limit?: number
}

/**
 * SesiPemesanan updateManyAndReturn
 */
export type SesiPemesananUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesiPemesanan
   */
  select?: Prisma.SesiPemesananSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SesiPemesanan
   */
  omit?: Prisma.SesiPemesananOmit<ExtArgs> | null
  /**
   * The data used to update SesiPemesanans.
   */
  data: Prisma.XOR<Prisma.SesiPemesananUpdateManyMutationInput, Prisma.SesiPemesananUncheckedUpdateManyInput>
  /**
   * Filter which SesiPemesanans to update
   */
  where?: Prisma.SesiPemesananWhereInput
  /**
   * Limit how many SesiPemesanans to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SesiPemesananIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SesiPemesanan upsert
 */
export type SesiPemesananUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesiPemesanan
   */
  select?: Prisma.SesiPemesananSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SesiPemesanan
   */
  omit?: Prisma.SesiPemesananOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SesiPemesananInclude<ExtArgs> | null
  /**
   * The filter to search for the SesiPemesanan to update in case it exists.
   */
  where: Prisma.SesiPemesananWhereUniqueInput
  /**
   * In case the SesiPemesanan found by the `where` argument doesn't exist, create a new SesiPemesanan with this data.
   */
  create: Prisma.XOR<Prisma.SesiPemesananCreateInput, Prisma.SesiPemesananUncheckedCreateInput>
  /**
   * In case the SesiPemesanan was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SesiPemesananUpdateInput, Prisma.SesiPemesananUncheckedUpdateInput>
}

/**
 * SesiPemesanan delete
 */
export type SesiPemesananDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesiPemesanan
   */
  select?: Prisma.SesiPemesananSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SesiPemesanan
   */
  omit?: Prisma.SesiPemesananOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SesiPemesananInclude<ExtArgs> | null
  /**
   * Filter which SesiPemesanan to delete.
   */
  where: Prisma.SesiPemesananWhereUniqueInput
}

/**
 * SesiPemesanan deleteMany
 */
export type SesiPemesananDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SesiPemesanans to delete
   */
  where?: Prisma.SesiPemesananWhereInput
  /**
   * Limit how many SesiPemesanans to delete.
   */
  limit?: number
}

/**
 * SesiPemesanan.pelanggan
 */
export type SesiPemesanan$pelangganArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pelanggan
   */
  select?: Prisma.PelangganSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pelanggan
   */
  omit?: Prisma.PelangganOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PelangganInclude<ExtArgs> | null
  where?: Prisma.PelangganWhereInput
}

/**
 * SesiPemesanan.meja
 */
export type SesiPemesanan$mejaArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Meja
   */
  select?: Prisma.MejaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Meja
   */
  omit?: Prisma.MejaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MejaInclude<ExtArgs> | null
  where?: Prisma.MejaWhereInput
  orderBy?: Prisma.MejaOrderByWithRelationInput | Prisma.MejaOrderByWithRelationInput[]
  cursor?: Prisma.MejaWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MejaScalarFieldEnum | Prisma.MejaScalarFieldEnum[]
}

/**
 * SesiPemesanan.transaksi
 */
export type SesiPemesanan$transaksiArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaksi
   */
  select?: Prisma.TransaksiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaksi
   */
  omit?: Prisma.TransaksiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransaksiInclude<ExtArgs> | null
  where?: Prisma.TransaksiWhereInput
  orderBy?: Prisma.TransaksiOrderByWithRelationInput | Prisma.TransaksiOrderByWithRelationInput[]
  cursor?: Prisma.TransaksiWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TransaksiScalarFieldEnum | Prisma.TransaksiScalarFieldEnum[]
}

/**
 * SesiPemesanan without action
 */
export type SesiPemesananDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesiPemesanan
   */
  select?: Prisma.SesiPemesananSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SesiPemesanan
   */
  omit?: Prisma.SesiPemesananOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SesiPemesananInclude<ExtArgs> | null
}
