
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Toko` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Toko
 * 
 */
export type TokoModel = runtime.Types.Result.DefaultSelection<Prisma.$TokoPayload>

export type AggregateToko = {
  _count: TokoCountAggregateOutputType | null
  _min: TokoMinAggregateOutputType | null
  _max: TokoMaxAggregateOutputType | null
}

export type TokoMinAggregateOutputType = {
  id_toko: string | null
  nama_toko: string | null
  jenis_toko: string | null
}

export type TokoMaxAggregateOutputType = {
  id_toko: string | null
  nama_toko: string | null
  jenis_toko: string | null
}

export type TokoCountAggregateOutputType = {
  id_toko: number
  nama_toko: number
  jenis_toko: number
  _all: number
}


export type TokoMinAggregateInputType = {
  id_toko?: true
  nama_toko?: true
  jenis_toko?: true
}

export type TokoMaxAggregateInputType = {
  id_toko?: true
  nama_toko?: true
  jenis_toko?: true
}

export type TokoCountAggregateInputType = {
  id_toko?: true
  nama_toko?: true
  jenis_toko?: true
  _all?: true
}

export type TokoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Toko to aggregate.
   */
  where?: Prisma.TokoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tokos to fetch.
   */
  orderBy?: Prisma.TokoOrderByWithRelationInput | Prisma.TokoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TokoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tokos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tokos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Tokos
  **/
  _count?: true | TokoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TokoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TokoMaxAggregateInputType
}

export type GetTokoAggregateType<T extends TokoAggregateArgs> = {
      [P in keyof T & keyof AggregateToko]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateToko[P]>
    : Prisma.GetScalarType<T[P], AggregateToko[P]>
}




export type TokoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TokoWhereInput
  orderBy?: Prisma.TokoOrderByWithAggregationInput | Prisma.TokoOrderByWithAggregationInput[]
  by: Prisma.TokoScalarFieldEnum[] | Prisma.TokoScalarFieldEnum
  having?: Prisma.TokoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TokoCountAggregateInputType | true
  _min?: TokoMinAggregateInputType
  _max?: TokoMaxAggregateInputType
}

export type TokoGroupByOutputType = {
  id_toko: string
  nama_toko: string | null
  jenis_toko: string | null
  _count: TokoCountAggregateOutputType | null
  _min: TokoMinAggregateOutputType | null
  _max: TokoMaxAggregateOutputType | null
}

type GetTokoGroupByPayload<T extends TokoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TokoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TokoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TokoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TokoGroupByOutputType[P]>
      }
    >
  >



export type TokoWhereInput = {
  AND?: Prisma.TokoWhereInput | Prisma.TokoWhereInput[]
  OR?: Prisma.TokoWhereInput[]
  NOT?: Prisma.TokoWhereInput | Prisma.TokoWhereInput[]
  id_toko?: Prisma.StringFilter<"Toko"> | string
  nama_toko?: Prisma.StringNullableFilter<"Toko"> | string | null
  jenis_toko?: Prisma.StringNullableFilter<"Toko"> | string | null
  items?: Prisma.ItemListRelationFilter
  transaksi?: Prisma.TransaksiListRelationFilter
}

export type TokoOrderByWithRelationInput = {
  id_toko?: Prisma.SortOrder
  nama_toko?: Prisma.SortOrderInput | Prisma.SortOrder
  jenis_toko?: Prisma.SortOrderInput | Prisma.SortOrder
  items?: Prisma.ItemOrderByRelationAggregateInput
  transaksi?: Prisma.TransaksiOrderByRelationAggregateInput
}

export type TokoWhereUniqueInput = Prisma.AtLeast<{
  id_toko?: string
  AND?: Prisma.TokoWhereInput | Prisma.TokoWhereInput[]
  OR?: Prisma.TokoWhereInput[]
  NOT?: Prisma.TokoWhereInput | Prisma.TokoWhereInput[]
  nama_toko?: Prisma.StringNullableFilter<"Toko"> | string | null
  jenis_toko?: Prisma.StringNullableFilter<"Toko"> | string | null
  items?: Prisma.ItemListRelationFilter
  transaksi?: Prisma.TransaksiListRelationFilter
}, "id_toko">

export type TokoOrderByWithAggregationInput = {
  id_toko?: Prisma.SortOrder
  nama_toko?: Prisma.SortOrderInput | Prisma.SortOrder
  jenis_toko?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.TokoCountOrderByAggregateInput
  _max?: Prisma.TokoMaxOrderByAggregateInput
  _min?: Prisma.TokoMinOrderByAggregateInput
}

export type TokoScalarWhereWithAggregatesInput = {
  AND?: Prisma.TokoScalarWhereWithAggregatesInput | Prisma.TokoScalarWhereWithAggregatesInput[]
  OR?: Prisma.TokoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TokoScalarWhereWithAggregatesInput | Prisma.TokoScalarWhereWithAggregatesInput[]
  id_toko?: Prisma.StringWithAggregatesFilter<"Toko"> | string
  nama_toko?: Prisma.StringNullableWithAggregatesFilter<"Toko"> | string | null
  jenis_toko?: Prisma.StringNullableWithAggregatesFilter<"Toko"> | string | null
}

export type TokoCreateInput = {
  id_toko: string
  nama_toko?: string | null
  jenis_toko?: string | null
  items?: Prisma.ItemCreateNestedManyWithoutTokoInput
  transaksi?: Prisma.TransaksiCreateNestedManyWithoutTokoInput
}

export type TokoUncheckedCreateInput = {
  id_toko: string
  nama_toko?: string | null
  jenis_toko?: string | null
  items?: Prisma.ItemUncheckedCreateNestedManyWithoutTokoInput
  transaksi?: Prisma.TransaksiUncheckedCreateNestedManyWithoutTokoInput
}

export type TokoUpdateInput = {
  id_toko?: Prisma.StringFieldUpdateOperationsInput | string
  nama_toko?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jenis_toko?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  items?: Prisma.ItemUpdateManyWithoutTokoNestedInput
  transaksi?: Prisma.TransaksiUpdateManyWithoutTokoNestedInput
}

export type TokoUncheckedUpdateInput = {
  id_toko?: Prisma.StringFieldUpdateOperationsInput | string
  nama_toko?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jenis_toko?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  items?: Prisma.ItemUncheckedUpdateManyWithoutTokoNestedInput
  transaksi?: Prisma.TransaksiUncheckedUpdateManyWithoutTokoNestedInput
}

export type TokoCreateManyInput = {
  id_toko: string
  nama_toko?: string | null
  jenis_toko?: string | null
}

export type TokoUpdateManyMutationInput = {
  id_toko?: Prisma.StringFieldUpdateOperationsInput | string
  nama_toko?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jenis_toko?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TokoUncheckedUpdateManyInput = {
  id_toko?: Prisma.StringFieldUpdateOperationsInput | string
  nama_toko?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jenis_toko?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TokoCountOrderByAggregateInput = {
  id_toko?: Prisma.SortOrder
  nama_toko?: Prisma.SortOrder
  jenis_toko?: Prisma.SortOrder
}

export type TokoMaxOrderByAggregateInput = {
  id_toko?: Prisma.SortOrder
  nama_toko?: Prisma.SortOrder
  jenis_toko?: Prisma.SortOrder
}

export type TokoMinOrderByAggregateInput = {
  id_toko?: Prisma.SortOrder
  nama_toko?: Prisma.SortOrder
  jenis_toko?: Prisma.SortOrder
}

export type TokoNullableScalarRelationFilter = {
  is?: Prisma.TokoWhereInput | null
  isNot?: Prisma.TokoWhereInput | null
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type TokoCreateNestedOneWithoutItemsInput = {
  create?: Prisma.XOR<Prisma.TokoCreateWithoutItemsInput, Prisma.TokoUncheckedCreateWithoutItemsInput>
  connectOrCreate?: Prisma.TokoCreateOrConnectWithoutItemsInput
  connect?: Prisma.TokoWhereUniqueInput
}

export type TokoUpdateOneWithoutItemsNestedInput = {
  create?: Prisma.XOR<Prisma.TokoCreateWithoutItemsInput, Prisma.TokoUncheckedCreateWithoutItemsInput>
  connectOrCreate?: Prisma.TokoCreateOrConnectWithoutItemsInput
  upsert?: Prisma.TokoUpsertWithoutItemsInput
  disconnect?: Prisma.TokoWhereInput | boolean
  delete?: Prisma.TokoWhereInput | boolean
  connect?: Prisma.TokoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TokoUpdateToOneWithWhereWithoutItemsInput, Prisma.TokoUpdateWithoutItemsInput>, Prisma.TokoUncheckedUpdateWithoutItemsInput>
}

export type TokoCreateNestedOneWithoutTransaksiInput = {
  create?: Prisma.XOR<Prisma.TokoCreateWithoutTransaksiInput, Prisma.TokoUncheckedCreateWithoutTransaksiInput>
  connectOrCreate?: Prisma.TokoCreateOrConnectWithoutTransaksiInput
  connect?: Prisma.TokoWhereUniqueInput
}

export type TokoUpdateOneWithoutTransaksiNestedInput = {
  create?: Prisma.XOR<Prisma.TokoCreateWithoutTransaksiInput, Prisma.TokoUncheckedCreateWithoutTransaksiInput>
  connectOrCreate?: Prisma.TokoCreateOrConnectWithoutTransaksiInput
  upsert?: Prisma.TokoUpsertWithoutTransaksiInput
  disconnect?: Prisma.TokoWhereInput | boolean
  delete?: Prisma.TokoWhereInput | boolean
  connect?: Prisma.TokoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TokoUpdateToOneWithWhereWithoutTransaksiInput, Prisma.TokoUpdateWithoutTransaksiInput>, Prisma.TokoUncheckedUpdateWithoutTransaksiInput>
}

export type TokoCreateWithoutItemsInput = {
  id_toko: string
  nama_toko?: string | null
  jenis_toko?: string | null
  transaksi?: Prisma.TransaksiCreateNestedManyWithoutTokoInput
}

export type TokoUncheckedCreateWithoutItemsInput = {
  id_toko: string
  nama_toko?: string | null
  jenis_toko?: string | null
  transaksi?: Prisma.TransaksiUncheckedCreateNestedManyWithoutTokoInput
}

export type TokoCreateOrConnectWithoutItemsInput = {
  where: Prisma.TokoWhereUniqueInput
  create: Prisma.XOR<Prisma.TokoCreateWithoutItemsInput, Prisma.TokoUncheckedCreateWithoutItemsInput>
}

export type TokoUpsertWithoutItemsInput = {
  update: Prisma.XOR<Prisma.TokoUpdateWithoutItemsInput, Prisma.TokoUncheckedUpdateWithoutItemsInput>
  create: Prisma.XOR<Prisma.TokoCreateWithoutItemsInput, Prisma.TokoUncheckedCreateWithoutItemsInput>
  where?: Prisma.TokoWhereInput
}

export type TokoUpdateToOneWithWhereWithoutItemsInput = {
  where?: Prisma.TokoWhereInput
  data: Prisma.XOR<Prisma.TokoUpdateWithoutItemsInput, Prisma.TokoUncheckedUpdateWithoutItemsInput>
}

export type TokoUpdateWithoutItemsInput = {
  id_toko?: Prisma.StringFieldUpdateOperationsInput | string
  nama_toko?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jenis_toko?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transaksi?: Prisma.TransaksiUpdateManyWithoutTokoNestedInput
}

export type TokoUncheckedUpdateWithoutItemsInput = {
  id_toko?: Prisma.StringFieldUpdateOperationsInput | string
  nama_toko?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jenis_toko?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transaksi?: Prisma.TransaksiUncheckedUpdateManyWithoutTokoNestedInput
}

export type TokoCreateWithoutTransaksiInput = {
  id_toko: string
  nama_toko?: string | null
  jenis_toko?: string | null
  items?: Prisma.ItemCreateNestedManyWithoutTokoInput
}

export type TokoUncheckedCreateWithoutTransaksiInput = {
  id_toko: string
  nama_toko?: string | null
  jenis_toko?: string | null
  items?: Prisma.ItemUncheckedCreateNestedManyWithoutTokoInput
}

export type TokoCreateOrConnectWithoutTransaksiInput = {
  where: Prisma.TokoWhereUniqueInput
  create: Prisma.XOR<Prisma.TokoCreateWithoutTransaksiInput, Prisma.TokoUncheckedCreateWithoutTransaksiInput>
}

export type TokoUpsertWithoutTransaksiInput = {
  update: Prisma.XOR<Prisma.TokoUpdateWithoutTransaksiInput, Prisma.TokoUncheckedUpdateWithoutTransaksiInput>
  create: Prisma.XOR<Prisma.TokoCreateWithoutTransaksiInput, Prisma.TokoUncheckedCreateWithoutTransaksiInput>
  where?: Prisma.TokoWhereInput
}

export type TokoUpdateToOneWithWhereWithoutTransaksiInput = {
  where?: Prisma.TokoWhereInput
  data: Prisma.XOR<Prisma.TokoUpdateWithoutTransaksiInput, Prisma.TokoUncheckedUpdateWithoutTransaksiInput>
}

export type TokoUpdateWithoutTransaksiInput = {
  id_toko?: Prisma.StringFieldUpdateOperationsInput | string
  nama_toko?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jenis_toko?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  items?: Prisma.ItemUpdateManyWithoutTokoNestedInput
}

export type TokoUncheckedUpdateWithoutTransaksiInput = {
  id_toko?: Prisma.StringFieldUpdateOperationsInput | string
  nama_toko?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jenis_toko?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  items?: Prisma.ItemUncheckedUpdateManyWithoutTokoNestedInput
}


/**
 * Count Type TokoCountOutputType
 */

export type TokoCountOutputType = {
  items: number
  transaksi: number
}

export type TokoCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  items?: boolean | TokoCountOutputTypeCountItemsArgs
  transaksi?: boolean | TokoCountOutputTypeCountTransaksiArgs
}

/**
 * TokoCountOutputType without action
 */
export type TokoCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TokoCountOutputType
   */
  select?: Prisma.TokoCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TokoCountOutputType without action
 */
export type TokoCountOutputTypeCountItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ItemWhereInput
}

/**
 * TokoCountOutputType without action
 */
export type TokoCountOutputTypeCountTransaksiArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TransaksiWhereInput
}


export type TokoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id_toko?: boolean
  nama_toko?: boolean
  jenis_toko?: boolean
  items?: boolean | Prisma.Toko$itemsArgs<ExtArgs>
  transaksi?: boolean | Prisma.Toko$transaksiArgs<ExtArgs>
  _count?: boolean | Prisma.TokoCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["toko"]>

export type TokoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id_toko?: boolean
  nama_toko?: boolean
  jenis_toko?: boolean
}, ExtArgs["result"]["toko"]>

export type TokoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id_toko?: boolean
  nama_toko?: boolean
  jenis_toko?: boolean
}, ExtArgs["result"]["toko"]>

export type TokoSelectScalar = {
  id_toko?: boolean
  nama_toko?: boolean
  jenis_toko?: boolean
}

export type TokoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id_toko" | "nama_toko" | "jenis_toko", ExtArgs["result"]["toko"]>
export type TokoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  items?: boolean | Prisma.Toko$itemsArgs<ExtArgs>
  transaksi?: boolean | Prisma.Toko$transaksiArgs<ExtArgs>
  _count?: boolean | Prisma.TokoCountOutputTypeDefaultArgs<ExtArgs>
}
export type TokoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type TokoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $TokoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Toko"
  objects: {
    items: Prisma.$ItemPayload<ExtArgs>[]
    transaksi: Prisma.$TransaksiPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id_toko: string
    nama_toko: string | null
    jenis_toko: string | null
  }, ExtArgs["result"]["toko"]>
  composites: {}
}

export type TokoGetPayload<S extends boolean | null | undefined | TokoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TokoPayload, S>

export type TokoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TokoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TokoCountAggregateInputType | true
  }

export interface TokoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Toko'], meta: { name: 'Toko' } }
  /**
   * Find zero or one Toko that matches the filter.
   * @param {TokoFindUniqueArgs} args - Arguments to find a Toko
   * @example
   * // Get one Toko
   * const toko = await prisma.toko.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TokoFindUniqueArgs>(args: Prisma.SelectSubset<T, TokoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TokoClient<runtime.Types.Result.GetResult<Prisma.$TokoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Toko that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TokoFindUniqueOrThrowArgs} args - Arguments to find a Toko
   * @example
   * // Get one Toko
   * const toko = await prisma.toko.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TokoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TokoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TokoClient<runtime.Types.Result.GetResult<Prisma.$TokoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Toko that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokoFindFirstArgs} args - Arguments to find a Toko
   * @example
   * // Get one Toko
   * const toko = await prisma.toko.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TokoFindFirstArgs>(args?: Prisma.SelectSubset<T, TokoFindFirstArgs<ExtArgs>>): Prisma.Prisma__TokoClient<runtime.Types.Result.GetResult<Prisma.$TokoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Toko that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokoFindFirstOrThrowArgs} args - Arguments to find a Toko
   * @example
   * // Get one Toko
   * const toko = await prisma.toko.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TokoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TokoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TokoClient<runtime.Types.Result.GetResult<Prisma.$TokoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tokos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tokos
   * const tokos = await prisma.toko.findMany()
   * 
   * // Get first 10 Tokos
   * const tokos = await prisma.toko.findMany({ take: 10 })
   * 
   * // Only select the `id_toko`
   * const tokoWithId_tokoOnly = await prisma.toko.findMany({ select: { id_toko: true } })
   * 
   */
  findMany<T extends TokoFindManyArgs>(args?: Prisma.SelectSubset<T, TokoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TokoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Toko.
   * @param {TokoCreateArgs} args - Arguments to create a Toko.
   * @example
   * // Create one Toko
   * const Toko = await prisma.toko.create({
   *   data: {
   *     // ... data to create a Toko
   *   }
   * })
   * 
   */
  create<T extends TokoCreateArgs>(args: Prisma.SelectSubset<T, TokoCreateArgs<ExtArgs>>): Prisma.Prisma__TokoClient<runtime.Types.Result.GetResult<Prisma.$TokoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tokos.
   * @param {TokoCreateManyArgs} args - Arguments to create many Tokos.
   * @example
   * // Create many Tokos
   * const toko = await prisma.toko.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TokoCreateManyArgs>(args?: Prisma.SelectSubset<T, TokoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Tokos and returns the data saved in the database.
   * @param {TokoCreateManyAndReturnArgs} args - Arguments to create many Tokos.
   * @example
   * // Create many Tokos
   * const toko = await prisma.toko.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Tokos and only return the `id_toko`
   * const tokoWithId_tokoOnly = await prisma.toko.createManyAndReturn({
   *   select: { id_toko: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TokoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TokoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TokoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Toko.
   * @param {TokoDeleteArgs} args - Arguments to delete one Toko.
   * @example
   * // Delete one Toko
   * const Toko = await prisma.toko.delete({
   *   where: {
   *     // ... filter to delete one Toko
   *   }
   * })
   * 
   */
  delete<T extends TokoDeleteArgs>(args: Prisma.SelectSubset<T, TokoDeleteArgs<ExtArgs>>): Prisma.Prisma__TokoClient<runtime.Types.Result.GetResult<Prisma.$TokoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Toko.
   * @param {TokoUpdateArgs} args - Arguments to update one Toko.
   * @example
   * // Update one Toko
   * const toko = await prisma.toko.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TokoUpdateArgs>(args: Prisma.SelectSubset<T, TokoUpdateArgs<ExtArgs>>): Prisma.Prisma__TokoClient<runtime.Types.Result.GetResult<Prisma.$TokoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tokos.
   * @param {TokoDeleteManyArgs} args - Arguments to filter Tokos to delete.
   * @example
   * // Delete a few Tokos
   * const { count } = await prisma.toko.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TokoDeleteManyArgs>(args?: Prisma.SelectSubset<T, TokoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tokos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tokos
   * const toko = await prisma.toko.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TokoUpdateManyArgs>(args: Prisma.SelectSubset<T, TokoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tokos and returns the data updated in the database.
   * @param {TokoUpdateManyAndReturnArgs} args - Arguments to update many Tokos.
   * @example
   * // Update many Tokos
   * const toko = await prisma.toko.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Tokos and only return the `id_toko`
   * const tokoWithId_tokoOnly = await prisma.toko.updateManyAndReturn({
   *   select: { id_toko: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TokoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TokoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TokoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Toko.
   * @param {TokoUpsertArgs} args - Arguments to update or create a Toko.
   * @example
   * // Update or create a Toko
   * const toko = await prisma.toko.upsert({
   *   create: {
   *     // ... data to create a Toko
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Toko we want to update
   *   }
   * })
   */
  upsert<T extends TokoUpsertArgs>(args: Prisma.SelectSubset<T, TokoUpsertArgs<ExtArgs>>): Prisma.Prisma__TokoClient<runtime.Types.Result.GetResult<Prisma.$TokoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tokos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokoCountArgs} args - Arguments to filter Tokos to count.
   * @example
   * // Count the number of Tokos
   * const count = await prisma.toko.count({
   *   where: {
   *     // ... the filter for the Tokos we want to count
   *   }
   * })
  **/
  count<T extends TokoCountArgs>(
    args?: Prisma.Subset<T, TokoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TokoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Toko.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TokoAggregateArgs>(args: Prisma.Subset<T, TokoAggregateArgs>): Prisma.PrismaPromise<GetTokoAggregateType<T>>

  /**
   * Group by Toko.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TokoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TokoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TokoGroupByArgs['orderBy'] }
      : { orderBy?: TokoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TokoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTokoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Toko model
 */
readonly fields: TokoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Toko.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TokoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  items<T extends Prisma.Toko$itemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Toko$itemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  transaksi<T extends Prisma.Toko$transaksiArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Toko$transaksiArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransaksiPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Toko model
 */
export interface TokoFieldRefs {
  readonly id_toko: Prisma.FieldRef<"Toko", 'String'>
  readonly nama_toko: Prisma.FieldRef<"Toko", 'String'>
  readonly jenis_toko: Prisma.FieldRef<"Toko", 'String'>
}
    

// Custom InputTypes
/**
 * Toko findUnique
 */
export type TokoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Toko
   */
  select?: Prisma.TokoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Toko
   */
  omit?: Prisma.TokoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokoInclude<ExtArgs> | null
  /**
   * Filter, which Toko to fetch.
   */
  where: Prisma.TokoWhereUniqueInput
}

/**
 * Toko findUniqueOrThrow
 */
export type TokoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Toko
   */
  select?: Prisma.TokoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Toko
   */
  omit?: Prisma.TokoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokoInclude<ExtArgs> | null
  /**
   * Filter, which Toko to fetch.
   */
  where: Prisma.TokoWhereUniqueInput
}

/**
 * Toko findFirst
 */
export type TokoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Toko
   */
  select?: Prisma.TokoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Toko
   */
  omit?: Prisma.TokoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokoInclude<ExtArgs> | null
  /**
   * Filter, which Toko to fetch.
   */
  where?: Prisma.TokoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tokos to fetch.
   */
  orderBy?: Prisma.TokoOrderByWithRelationInput | Prisma.TokoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tokos.
   */
  cursor?: Prisma.TokoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tokos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tokos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tokos.
   */
  distinct?: Prisma.TokoScalarFieldEnum | Prisma.TokoScalarFieldEnum[]
}

/**
 * Toko findFirstOrThrow
 */
export type TokoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Toko
   */
  select?: Prisma.TokoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Toko
   */
  omit?: Prisma.TokoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokoInclude<ExtArgs> | null
  /**
   * Filter, which Toko to fetch.
   */
  where?: Prisma.TokoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tokos to fetch.
   */
  orderBy?: Prisma.TokoOrderByWithRelationInput | Prisma.TokoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tokos.
   */
  cursor?: Prisma.TokoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tokos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tokos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tokos.
   */
  distinct?: Prisma.TokoScalarFieldEnum | Prisma.TokoScalarFieldEnum[]
}

/**
 * Toko findMany
 */
export type TokoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Toko
   */
  select?: Prisma.TokoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Toko
   */
  omit?: Prisma.TokoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokoInclude<ExtArgs> | null
  /**
   * Filter, which Tokos to fetch.
   */
  where?: Prisma.TokoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tokos to fetch.
   */
  orderBy?: Prisma.TokoOrderByWithRelationInput | Prisma.TokoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Tokos.
   */
  cursor?: Prisma.TokoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tokos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tokos.
   */
  skip?: number
  distinct?: Prisma.TokoScalarFieldEnum | Prisma.TokoScalarFieldEnum[]
}

/**
 * Toko create
 */
export type TokoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Toko
   */
  select?: Prisma.TokoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Toko
   */
  omit?: Prisma.TokoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokoInclude<ExtArgs> | null
  /**
   * The data needed to create a Toko.
   */
  data: Prisma.XOR<Prisma.TokoCreateInput, Prisma.TokoUncheckedCreateInput>
}

/**
 * Toko createMany
 */
export type TokoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Tokos.
   */
  data: Prisma.TokoCreateManyInput | Prisma.TokoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Toko createManyAndReturn
 */
export type TokoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Toko
   */
  select?: Prisma.TokoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Toko
   */
  omit?: Prisma.TokoOmit<ExtArgs> | null
  /**
   * The data used to create many Tokos.
   */
  data: Prisma.TokoCreateManyInput | Prisma.TokoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Toko update
 */
export type TokoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Toko
   */
  select?: Prisma.TokoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Toko
   */
  omit?: Prisma.TokoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokoInclude<ExtArgs> | null
  /**
   * The data needed to update a Toko.
   */
  data: Prisma.XOR<Prisma.TokoUpdateInput, Prisma.TokoUncheckedUpdateInput>
  /**
   * Choose, which Toko to update.
   */
  where: Prisma.TokoWhereUniqueInput
}

/**
 * Toko updateMany
 */
export type TokoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Tokos.
   */
  data: Prisma.XOR<Prisma.TokoUpdateManyMutationInput, Prisma.TokoUncheckedUpdateManyInput>
  /**
   * Filter which Tokos to update
   */
  where?: Prisma.TokoWhereInput
  /**
   * Limit how many Tokos to update.
   */
  limit?: number
}

/**
 * Toko updateManyAndReturn
 */
export type TokoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Toko
   */
  select?: Prisma.TokoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Toko
   */
  omit?: Prisma.TokoOmit<ExtArgs> | null
  /**
   * The data used to update Tokos.
   */
  data: Prisma.XOR<Prisma.TokoUpdateManyMutationInput, Prisma.TokoUncheckedUpdateManyInput>
  /**
   * Filter which Tokos to update
   */
  where?: Prisma.TokoWhereInput
  /**
   * Limit how many Tokos to update.
   */
  limit?: number
}

/**
 * Toko upsert
 */
export type TokoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Toko
   */
  select?: Prisma.TokoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Toko
   */
  omit?: Prisma.TokoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokoInclude<ExtArgs> | null
  /**
   * The filter to search for the Toko to update in case it exists.
   */
  where: Prisma.TokoWhereUniqueInput
  /**
   * In case the Toko found by the `where` argument doesn't exist, create a new Toko with this data.
   */
  create: Prisma.XOR<Prisma.TokoCreateInput, Prisma.TokoUncheckedCreateInput>
  /**
   * In case the Toko was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TokoUpdateInput, Prisma.TokoUncheckedUpdateInput>
}

/**
 * Toko delete
 */
export type TokoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Toko
   */
  select?: Prisma.TokoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Toko
   */
  omit?: Prisma.TokoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokoInclude<ExtArgs> | null
  /**
   * Filter which Toko to delete.
   */
  where: Prisma.TokoWhereUniqueInput
}

/**
 * Toko deleteMany
 */
export type TokoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tokos to delete
   */
  where?: Prisma.TokoWhereInput
  /**
   * Limit how many Tokos to delete.
   */
  limit?: number
}

/**
 * Toko.items
 */
export type Toko$itemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Item
   */
  select?: Prisma.ItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Item
   */
  omit?: Prisma.ItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemInclude<ExtArgs> | null
  where?: Prisma.ItemWhereInput
  orderBy?: Prisma.ItemOrderByWithRelationInput | Prisma.ItemOrderByWithRelationInput[]
  cursor?: Prisma.ItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ItemScalarFieldEnum | Prisma.ItemScalarFieldEnum[]
}

/**
 * Toko.transaksi
 */
export type Toko$transaksiArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaksi
   */
  select?: Prisma.TransaksiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaksi
   */
  omit?: Prisma.TransaksiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransaksiInclude<ExtArgs> | null
  where?: Prisma.TransaksiWhereInput
  orderBy?: Prisma.TransaksiOrderByWithRelationInput | Prisma.TransaksiOrderByWithRelationInput[]
  cursor?: Prisma.TransaksiWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TransaksiScalarFieldEnum | Prisma.TransaksiScalarFieldEnum[]
}

/**
 * Toko without action
 */
export type TokoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Toko
   */
  select?: Prisma.TokoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Toko
   */
  omit?: Prisma.TokoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokoInclude<ExtArgs> | null
}
