
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Transaksi` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Transaksi
 * 
 */
export type TransaksiModel = runtime.Types.Result.DefaultSelection<Prisma.$TransaksiPayload>

export type AggregateTransaksi = {
  _count: TransaksiCountAggregateOutputType | null
  _avg: TransaksiAvgAggregateOutputType | null
  _sum: TransaksiSumAggregateOutputType | null
  _min: TransaksiMinAggregateOutputType | null
  _max: TransaksiMaxAggregateOutputType | null
}

export type TransaksiAvgAggregateOutputType = {
  total_harga: runtime.Decimal | null
}

export type TransaksiSumAggregateOutputType = {
  total_harga: runtime.Decimal | null
}

export type TransaksiMinAggregateOutputType = {
  id_transaksi: string | null
  id_sesi: string | null
  id_toko: string | null
  jenis_transaksi: $Enums.JenisTransaksi | null
  total_harga: runtime.Decimal | null
  status_pesanan: $Enums.StatusPesanan | null
  tanggal_transaksi: Date | null
}

export type TransaksiMaxAggregateOutputType = {
  id_transaksi: string | null
  id_sesi: string | null
  id_toko: string | null
  jenis_transaksi: $Enums.JenisTransaksi | null
  total_harga: runtime.Decimal | null
  status_pesanan: $Enums.StatusPesanan | null
  tanggal_transaksi: Date | null
}

export type TransaksiCountAggregateOutputType = {
  id_transaksi: number
  id_sesi: number
  id_toko: number
  jenis_transaksi: number
  total_harga: number
  status_pesanan: number
  tanggal_transaksi: number
  _all: number
}


export type TransaksiAvgAggregateInputType = {
  total_harga?: true
}

export type TransaksiSumAggregateInputType = {
  total_harga?: true
}

export type TransaksiMinAggregateInputType = {
  id_transaksi?: true
  id_sesi?: true
  id_toko?: true
  jenis_transaksi?: true
  total_harga?: true
  status_pesanan?: true
  tanggal_transaksi?: true
}

export type TransaksiMaxAggregateInputType = {
  id_transaksi?: true
  id_sesi?: true
  id_toko?: true
  jenis_transaksi?: true
  total_harga?: true
  status_pesanan?: true
  tanggal_transaksi?: true
}

export type TransaksiCountAggregateInputType = {
  id_transaksi?: true
  id_sesi?: true
  id_toko?: true
  jenis_transaksi?: true
  total_harga?: true
  status_pesanan?: true
  tanggal_transaksi?: true
  _all?: true
}

export type TransaksiAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Transaksi to aggregate.
   */
  where?: Prisma.TransaksiWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Transaksis to fetch.
   */
  orderBy?: Prisma.TransaksiOrderByWithRelationInput | Prisma.TransaksiOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TransaksiWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Transaksis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Transaksis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Transaksis
  **/
  _count?: true | TransaksiCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TransaksiAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TransaksiSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TransaksiMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TransaksiMaxAggregateInputType
}

export type GetTransaksiAggregateType<T extends TransaksiAggregateArgs> = {
      [P in keyof T & keyof AggregateTransaksi]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTransaksi[P]>
    : Prisma.GetScalarType<T[P], AggregateTransaksi[P]>
}




export type TransaksiGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TransaksiWhereInput
  orderBy?: Prisma.TransaksiOrderByWithAggregationInput | Prisma.TransaksiOrderByWithAggregationInput[]
  by: Prisma.TransaksiScalarFieldEnum[] | Prisma.TransaksiScalarFieldEnum
  having?: Prisma.TransaksiScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TransaksiCountAggregateInputType | true
  _avg?: TransaksiAvgAggregateInputType
  _sum?: TransaksiSumAggregateInputType
  _min?: TransaksiMinAggregateInputType
  _max?: TransaksiMaxAggregateInputType
}

export type TransaksiGroupByOutputType = {
  id_transaksi: string
  id_sesi: string | null
  id_toko: string | null
  jenis_transaksi: $Enums.JenisTransaksi | null
  total_harga: runtime.Decimal | null
  status_pesanan: $Enums.StatusPesanan | null
  tanggal_transaksi: Date | null
  _count: TransaksiCountAggregateOutputType | null
  _avg: TransaksiAvgAggregateOutputType | null
  _sum: TransaksiSumAggregateOutputType | null
  _min: TransaksiMinAggregateOutputType | null
  _max: TransaksiMaxAggregateOutputType | null
}

type GetTransaksiGroupByPayload<T extends TransaksiGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TransaksiGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TransaksiGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TransaksiGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TransaksiGroupByOutputType[P]>
      }
    >
  >



export type TransaksiWhereInput = {
  AND?: Prisma.TransaksiWhereInput | Prisma.TransaksiWhereInput[]
  OR?: Prisma.TransaksiWhereInput[]
  NOT?: Prisma.TransaksiWhereInput | Prisma.TransaksiWhereInput[]
  id_transaksi?: Prisma.StringFilter<"Transaksi"> | string
  id_sesi?: Prisma.StringNullableFilter<"Transaksi"> | string | null
  id_toko?: Prisma.StringNullableFilter<"Transaksi"> | string | null
  jenis_transaksi?: Prisma.EnumJenisTransaksiNullableFilter<"Transaksi"> | $Enums.JenisTransaksi | null
  total_harga?: Prisma.DecimalNullableFilter<"Transaksi"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: Prisma.EnumStatusPesananNullableFilter<"Transaksi"> | $Enums.StatusPesanan | null
  tanggal_transaksi?: Prisma.DateTimeNullableFilter<"Transaksi"> | Date | string | null
  sesi?: Prisma.XOR<Prisma.SesiPemesananNullableScalarRelationFilter, Prisma.SesiPemesananWhereInput> | null
  toko?: Prisma.XOR<Prisma.TokoNullableScalarRelationFilter, Prisma.TokoWhereInput> | null
  antrian?: Prisma.AntrianOrderListRelationFilter
}

export type TransaksiOrderByWithRelationInput = {
  id_transaksi?: Prisma.SortOrder
  id_sesi?: Prisma.SortOrderInput | Prisma.SortOrder
  id_toko?: Prisma.SortOrderInput | Prisma.SortOrder
  jenis_transaksi?: Prisma.SortOrderInput | Prisma.SortOrder
  total_harga?: Prisma.SortOrderInput | Prisma.SortOrder
  status_pesanan?: Prisma.SortOrderInput | Prisma.SortOrder
  tanggal_transaksi?: Prisma.SortOrderInput | Prisma.SortOrder
  sesi?: Prisma.SesiPemesananOrderByWithRelationInput
  toko?: Prisma.TokoOrderByWithRelationInput
  antrian?: Prisma.AntrianOrderOrderByRelationAggregateInput
}

export type TransaksiWhereUniqueInput = Prisma.AtLeast<{
  id_transaksi?: string
  AND?: Prisma.TransaksiWhereInput | Prisma.TransaksiWhereInput[]
  OR?: Prisma.TransaksiWhereInput[]
  NOT?: Prisma.TransaksiWhereInput | Prisma.TransaksiWhereInput[]
  id_sesi?: Prisma.StringNullableFilter<"Transaksi"> | string | null
  id_toko?: Prisma.StringNullableFilter<"Transaksi"> | string | null
  jenis_transaksi?: Prisma.EnumJenisTransaksiNullableFilter<"Transaksi"> | $Enums.JenisTransaksi | null
  total_harga?: Prisma.DecimalNullableFilter<"Transaksi"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: Prisma.EnumStatusPesananNullableFilter<"Transaksi"> | $Enums.StatusPesanan | null
  tanggal_transaksi?: Prisma.DateTimeNullableFilter<"Transaksi"> | Date | string | null
  sesi?: Prisma.XOR<Prisma.SesiPemesananNullableScalarRelationFilter, Prisma.SesiPemesananWhereInput> | null
  toko?: Prisma.XOR<Prisma.TokoNullableScalarRelationFilter, Prisma.TokoWhereInput> | null
  antrian?: Prisma.AntrianOrderListRelationFilter
}, "id_transaksi">

export type TransaksiOrderByWithAggregationInput = {
  id_transaksi?: Prisma.SortOrder
  id_sesi?: Prisma.SortOrderInput | Prisma.SortOrder
  id_toko?: Prisma.SortOrderInput | Prisma.SortOrder
  jenis_transaksi?: Prisma.SortOrderInput | Prisma.SortOrder
  total_harga?: Prisma.SortOrderInput | Prisma.SortOrder
  status_pesanan?: Prisma.SortOrderInput | Prisma.SortOrder
  tanggal_transaksi?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.TransaksiCountOrderByAggregateInput
  _avg?: Prisma.TransaksiAvgOrderByAggregateInput
  _max?: Prisma.TransaksiMaxOrderByAggregateInput
  _min?: Prisma.TransaksiMinOrderByAggregateInput
  _sum?: Prisma.TransaksiSumOrderByAggregateInput
}

export type TransaksiScalarWhereWithAggregatesInput = {
  AND?: Prisma.TransaksiScalarWhereWithAggregatesInput | Prisma.TransaksiScalarWhereWithAggregatesInput[]
  OR?: Prisma.TransaksiScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TransaksiScalarWhereWithAggregatesInput | Prisma.TransaksiScalarWhereWithAggregatesInput[]
  id_transaksi?: Prisma.StringWithAggregatesFilter<"Transaksi"> | string
  id_sesi?: Prisma.StringNullableWithAggregatesFilter<"Transaksi"> | string | null
  id_toko?: Prisma.StringNullableWithAggregatesFilter<"Transaksi"> | string | null
  jenis_transaksi?: Prisma.EnumJenisTransaksiNullableWithAggregatesFilter<"Transaksi"> | $Enums.JenisTransaksi | null
  total_harga?: Prisma.DecimalNullableWithAggregatesFilter<"Transaksi"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: Prisma.EnumStatusPesananNullableWithAggregatesFilter<"Transaksi"> | $Enums.StatusPesanan | null
  tanggal_transaksi?: Prisma.DateTimeNullableWithAggregatesFilter<"Transaksi"> | Date | string | null
}

export type TransaksiCreateInput = {
  id_transaksi: string
  jenis_transaksi?: $Enums.JenisTransaksi | null
  total_harga?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: $Enums.StatusPesanan | null
  tanggal_transaksi?: Date | string | null
  sesi?: Prisma.SesiPemesananCreateNestedOneWithoutTransaksiInput
  toko?: Prisma.TokoCreateNestedOneWithoutTransaksiInput
  antrian?: Prisma.AntrianOrderCreateNestedManyWithoutTransaksiInput
}

export type TransaksiUncheckedCreateInput = {
  id_transaksi: string
  id_sesi?: string | null
  id_toko?: string | null
  jenis_transaksi?: $Enums.JenisTransaksi | null
  total_harga?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: $Enums.StatusPesanan | null
  tanggal_transaksi?: Date | string | null
  antrian?: Prisma.AntrianOrderUncheckedCreateNestedManyWithoutTransaksiInput
}

export type TransaksiUpdateInput = {
  id_transaksi?: Prisma.StringFieldUpdateOperationsInput | string
  jenis_transaksi?: Prisma.NullableEnumJenisTransaksiFieldUpdateOperationsInput | $Enums.JenisTransaksi | null
  total_harga?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: Prisma.NullableEnumStatusPesananFieldUpdateOperationsInput | $Enums.StatusPesanan | null
  tanggal_transaksi?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sesi?: Prisma.SesiPemesananUpdateOneWithoutTransaksiNestedInput
  toko?: Prisma.TokoUpdateOneWithoutTransaksiNestedInput
  antrian?: Prisma.AntrianOrderUpdateManyWithoutTransaksiNestedInput
}

export type TransaksiUncheckedUpdateInput = {
  id_transaksi?: Prisma.StringFieldUpdateOperationsInput | string
  id_sesi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  id_toko?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jenis_transaksi?: Prisma.NullableEnumJenisTransaksiFieldUpdateOperationsInput | $Enums.JenisTransaksi | null
  total_harga?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: Prisma.NullableEnumStatusPesananFieldUpdateOperationsInput | $Enums.StatusPesanan | null
  tanggal_transaksi?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  antrian?: Prisma.AntrianOrderUncheckedUpdateManyWithoutTransaksiNestedInput
}

export type TransaksiCreateManyInput = {
  id_transaksi: string
  id_sesi?: string | null
  id_toko?: string | null
  jenis_transaksi?: $Enums.JenisTransaksi | null
  total_harga?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: $Enums.StatusPesanan | null
  tanggal_transaksi?: Date | string | null
}

export type TransaksiUpdateManyMutationInput = {
  id_transaksi?: Prisma.StringFieldUpdateOperationsInput | string
  jenis_transaksi?: Prisma.NullableEnumJenisTransaksiFieldUpdateOperationsInput | $Enums.JenisTransaksi | null
  total_harga?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: Prisma.NullableEnumStatusPesananFieldUpdateOperationsInput | $Enums.StatusPesanan | null
  tanggal_transaksi?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TransaksiUncheckedUpdateManyInput = {
  id_transaksi?: Prisma.StringFieldUpdateOperationsInput | string
  id_sesi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  id_toko?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jenis_transaksi?: Prisma.NullableEnumJenisTransaksiFieldUpdateOperationsInput | $Enums.JenisTransaksi | null
  total_harga?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: Prisma.NullableEnumStatusPesananFieldUpdateOperationsInput | $Enums.StatusPesanan | null
  tanggal_transaksi?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TransaksiListRelationFilter = {
  every?: Prisma.TransaksiWhereInput
  some?: Prisma.TransaksiWhereInput
  none?: Prisma.TransaksiWhereInput
}

export type TransaksiOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TransaksiCountOrderByAggregateInput = {
  id_transaksi?: Prisma.SortOrder
  id_sesi?: Prisma.SortOrder
  id_toko?: Prisma.SortOrder
  jenis_transaksi?: Prisma.SortOrder
  total_harga?: Prisma.SortOrder
  status_pesanan?: Prisma.SortOrder
  tanggal_transaksi?: Prisma.SortOrder
}

export type TransaksiAvgOrderByAggregateInput = {
  total_harga?: Prisma.SortOrder
}

export type TransaksiMaxOrderByAggregateInput = {
  id_transaksi?: Prisma.SortOrder
  id_sesi?: Prisma.SortOrder
  id_toko?: Prisma.SortOrder
  jenis_transaksi?: Prisma.SortOrder
  total_harga?: Prisma.SortOrder
  status_pesanan?: Prisma.SortOrder
  tanggal_transaksi?: Prisma.SortOrder
}

export type TransaksiMinOrderByAggregateInput = {
  id_transaksi?: Prisma.SortOrder
  id_sesi?: Prisma.SortOrder
  id_toko?: Prisma.SortOrder
  jenis_transaksi?: Prisma.SortOrder
  total_harga?: Prisma.SortOrder
  status_pesanan?: Prisma.SortOrder
  tanggal_transaksi?: Prisma.SortOrder
}

export type TransaksiSumOrderByAggregateInput = {
  total_harga?: Prisma.SortOrder
}

export type TransaksiNullableScalarRelationFilter = {
  is?: Prisma.TransaksiWhereInput | null
  isNot?: Prisma.TransaksiWhereInput | null
}

export type TransaksiCreateNestedManyWithoutTokoInput = {
  create?: Prisma.XOR<Prisma.TransaksiCreateWithoutTokoInput, Prisma.TransaksiUncheckedCreateWithoutTokoInput> | Prisma.TransaksiCreateWithoutTokoInput[] | Prisma.TransaksiUncheckedCreateWithoutTokoInput[]
  connectOrCreate?: Prisma.TransaksiCreateOrConnectWithoutTokoInput | Prisma.TransaksiCreateOrConnectWithoutTokoInput[]
  createMany?: Prisma.TransaksiCreateManyTokoInputEnvelope
  connect?: Prisma.TransaksiWhereUniqueInput | Prisma.TransaksiWhereUniqueInput[]
}

export type TransaksiUncheckedCreateNestedManyWithoutTokoInput = {
  create?: Prisma.XOR<Prisma.TransaksiCreateWithoutTokoInput, Prisma.TransaksiUncheckedCreateWithoutTokoInput> | Prisma.TransaksiCreateWithoutTokoInput[] | Prisma.TransaksiUncheckedCreateWithoutTokoInput[]
  connectOrCreate?: Prisma.TransaksiCreateOrConnectWithoutTokoInput | Prisma.TransaksiCreateOrConnectWithoutTokoInput[]
  createMany?: Prisma.TransaksiCreateManyTokoInputEnvelope
  connect?: Prisma.TransaksiWhereUniqueInput | Prisma.TransaksiWhereUniqueInput[]
}

export type TransaksiUpdateManyWithoutTokoNestedInput = {
  create?: Prisma.XOR<Prisma.TransaksiCreateWithoutTokoInput, Prisma.TransaksiUncheckedCreateWithoutTokoInput> | Prisma.TransaksiCreateWithoutTokoInput[] | Prisma.TransaksiUncheckedCreateWithoutTokoInput[]
  connectOrCreate?: Prisma.TransaksiCreateOrConnectWithoutTokoInput | Prisma.TransaksiCreateOrConnectWithoutTokoInput[]
  upsert?: Prisma.TransaksiUpsertWithWhereUniqueWithoutTokoInput | Prisma.TransaksiUpsertWithWhereUniqueWithoutTokoInput[]
  createMany?: Prisma.TransaksiCreateManyTokoInputEnvelope
  set?: Prisma.TransaksiWhereUniqueInput | Prisma.TransaksiWhereUniqueInput[]
  disconnect?: Prisma.TransaksiWhereUniqueInput | Prisma.TransaksiWhereUniqueInput[]
  delete?: Prisma.TransaksiWhereUniqueInput | Prisma.TransaksiWhereUniqueInput[]
  connect?: Prisma.TransaksiWhereUniqueInput | Prisma.TransaksiWhereUniqueInput[]
  update?: Prisma.TransaksiUpdateWithWhereUniqueWithoutTokoInput | Prisma.TransaksiUpdateWithWhereUniqueWithoutTokoInput[]
  updateMany?: Prisma.TransaksiUpdateManyWithWhereWithoutTokoInput | Prisma.TransaksiUpdateManyWithWhereWithoutTokoInput[]
  deleteMany?: Prisma.TransaksiScalarWhereInput | Prisma.TransaksiScalarWhereInput[]
}

export type TransaksiUncheckedUpdateManyWithoutTokoNestedInput = {
  create?: Prisma.XOR<Prisma.TransaksiCreateWithoutTokoInput, Prisma.TransaksiUncheckedCreateWithoutTokoInput> | Prisma.TransaksiCreateWithoutTokoInput[] | Prisma.TransaksiUncheckedCreateWithoutTokoInput[]
  connectOrCreate?: Prisma.TransaksiCreateOrConnectWithoutTokoInput | Prisma.TransaksiCreateOrConnectWithoutTokoInput[]
  upsert?: Prisma.TransaksiUpsertWithWhereUniqueWithoutTokoInput | Prisma.TransaksiUpsertWithWhereUniqueWithoutTokoInput[]
  createMany?: Prisma.TransaksiCreateManyTokoInputEnvelope
  set?: Prisma.TransaksiWhereUniqueInput | Prisma.TransaksiWhereUniqueInput[]
  disconnect?: Prisma.TransaksiWhereUniqueInput | Prisma.TransaksiWhereUniqueInput[]
  delete?: Prisma.TransaksiWhereUniqueInput | Prisma.TransaksiWhereUniqueInput[]
  connect?: Prisma.TransaksiWhereUniqueInput | Prisma.TransaksiWhereUniqueInput[]
  update?: Prisma.TransaksiUpdateWithWhereUniqueWithoutTokoInput | Prisma.TransaksiUpdateWithWhereUniqueWithoutTokoInput[]
  updateMany?: Prisma.TransaksiUpdateManyWithWhereWithoutTokoInput | Prisma.TransaksiUpdateManyWithWhereWithoutTokoInput[]
  deleteMany?: Prisma.TransaksiScalarWhereInput | Prisma.TransaksiScalarWhereInput[]
}

export type TransaksiCreateNestedManyWithoutSesiInput = {
  create?: Prisma.XOR<Prisma.TransaksiCreateWithoutSesiInput, Prisma.TransaksiUncheckedCreateWithoutSesiInput> | Prisma.TransaksiCreateWithoutSesiInput[] | Prisma.TransaksiUncheckedCreateWithoutSesiInput[]
  connectOrCreate?: Prisma.TransaksiCreateOrConnectWithoutSesiInput | Prisma.TransaksiCreateOrConnectWithoutSesiInput[]
  createMany?: Prisma.TransaksiCreateManySesiInputEnvelope
  connect?: Prisma.TransaksiWhereUniqueInput | Prisma.TransaksiWhereUniqueInput[]
}

export type TransaksiUncheckedCreateNestedManyWithoutSesiInput = {
  create?: Prisma.XOR<Prisma.TransaksiCreateWithoutSesiInput, Prisma.TransaksiUncheckedCreateWithoutSesiInput> | Prisma.TransaksiCreateWithoutSesiInput[] | Prisma.TransaksiUncheckedCreateWithoutSesiInput[]
  connectOrCreate?: Prisma.TransaksiCreateOrConnectWithoutSesiInput | Prisma.TransaksiCreateOrConnectWithoutSesiInput[]
  createMany?: Prisma.TransaksiCreateManySesiInputEnvelope
  connect?: Prisma.TransaksiWhereUniqueInput | Prisma.TransaksiWhereUniqueInput[]
}

export type TransaksiUpdateManyWithoutSesiNestedInput = {
  create?: Prisma.XOR<Prisma.TransaksiCreateWithoutSesiInput, Prisma.TransaksiUncheckedCreateWithoutSesiInput> | Prisma.TransaksiCreateWithoutSesiInput[] | Prisma.TransaksiUncheckedCreateWithoutSesiInput[]
  connectOrCreate?: Prisma.TransaksiCreateOrConnectWithoutSesiInput | Prisma.TransaksiCreateOrConnectWithoutSesiInput[]
  upsert?: Prisma.TransaksiUpsertWithWhereUniqueWithoutSesiInput | Prisma.TransaksiUpsertWithWhereUniqueWithoutSesiInput[]
  createMany?: Prisma.TransaksiCreateManySesiInputEnvelope
  set?: Prisma.TransaksiWhereUniqueInput | Prisma.TransaksiWhereUniqueInput[]
  disconnect?: Prisma.TransaksiWhereUniqueInput | Prisma.TransaksiWhereUniqueInput[]
  delete?: Prisma.TransaksiWhereUniqueInput | Prisma.TransaksiWhereUniqueInput[]
  connect?: Prisma.TransaksiWhereUniqueInput | Prisma.TransaksiWhereUniqueInput[]
  update?: Prisma.TransaksiUpdateWithWhereUniqueWithoutSesiInput | Prisma.TransaksiUpdateWithWhereUniqueWithoutSesiInput[]
  updateMany?: Prisma.TransaksiUpdateManyWithWhereWithoutSesiInput | Prisma.TransaksiUpdateManyWithWhereWithoutSesiInput[]
  deleteMany?: Prisma.TransaksiScalarWhereInput | Prisma.TransaksiScalarWhereInput[]
}

export type TransaksiUncheckedUpdateManyWithoutSesiNestedInput = {
  create?: Prisma.XOR<Prisma.TransaksiCreateWithoutSesiInput, Prisma.TransaksiUncheckedCreateWithoutSesiInput> | Prisma.TransaksiCreateWithoutSesiInput[] | Prisma.TransaksiUncheckedCreateWithoutSesiInput[]
  connectOrCreate?: Prisma.TransaksiCreateOrConnectWithoutSesiInput | Prisma.TransaksiCreateOrConnectWithoutSesiInput[]
  upsert?: Prisma.TransaksiUpsertWithWhereUniqueWithoutSesiInput | Prisma.TransaksiUpsertWithWhereUniqueWithoutSesiInput[]
  createMany?: Prisma.TransaksiCreateManySesiInputEnvelope
  set?: Prisma.TransaksiWhereUniqueInput | Prisma.TransaksiWhereUniqueInput[]
  disconnect?: Prisma.TransaksiWhereUniqueInput | Prisma.TransaksiWhereUniqueInput[]
  delete?: Prisma.TransaksiWhereUniqueInput | Prisma.TransaksiWhereUniqueInput[]
  connect?: Prisma.TransaksiWhereUniqueInput | Prisma.TransaksiWhereUniqueInput[]
  update?: Prisma.TransaksiUpdateWithWhereUniqueWithoutSesiInput | Prisma.TransaksiUpdateWithWhereUniqueWithoutSesiInput[]
  updateMany?: Prisma.TransaksiUpdateManyWithWhereWithoutSesiInput | Prisma.TransaksiUpdateManyWithWhereWithoutSesiInput[]
  deleteMany?: Prisma.TransaksiScalarWhereInput | Prisma.TransaksiScalarWhereInput[]
}

export type NullableEnumJenisTransaksiFieldUpdateOperationsInput = {
  set?: $Enums.JenisTransaksi | null
}

export type NullableDecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type NullableEnumStatusPesananFieldUpdateOperationsInput = {
  set?: $Enums.StatusPesanan | null
}

export type TransaksiCreateNestedOneWithoutAntrianInput = {
  create?: Prisma.XOR<Prisma.TransaksiCreateWithoutAntrianInput, Prisma.TransaksiUncheckedCreateWithoutAntrianInput>
  connectOrCreate?: Prisma.TransaksiCreateOrConnectWithoutAntrianInput
  connect?: Prisma.TransaksiWhereUniqueInput
}

export type TransaksiUpdateOneWithoutAntrianNestedInput = {
  create?: Prisma.XOR<Prisma.TransaksiCreateWithoutAntrianInput, Prisma.TransaksiUncheckedCreateWithoutAntrianInput>
  connectOrCreate?: Prisma.TransaksiCreateOrConnectWithoutAntrianInput
  upsert?: Prisma.TransaksiUpsertWithoutAntrianInput
  disconnect?: Prisma.TransaksiWhereInput | boolean
  delete?: Prisma.TransaksiWhereInput | boolean
  connect?: Prisma.TransaksiWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TransaksiUpdateToOneWithWhereWithoutAntrianInput, Prisma.TransaksiUpdateWithoutAntrianInput>, Prisma.TransaksiUncheckedUpdateWithoutAntrianInput>
}

export type TransaksiCreateWithoutTokoInput = {
  id_transaksi: string
  jenis_transaksi?: $Enums.JenisTransaksi | null
  total_harga?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: $Enums.StatusPesanan | null
  tanggal_transaksi?: Date | string | null
  sesi?: Prisma.SesiPemesananCreateNestedOneWithoutTransaksiInput
  antrian?: Prisma.AntrianOrderCreateNestedManyWithoutTransaksiInput
}

export type TransaksiUncheckedCreateWithoutTokoInput = {
  id_transaksi: string
  id_sesi?: string | null
  jenis_transaksi?: $Enums.JenisTransaksi | null
  total_harga?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: $Enums.StatusPesanan | null
  tanggal_transaksi?: Date | string | null
  antrian?: Prisma.AntrianOrderUncheckedCreateNestedManyWithoutTransaksiInput
}

export type TransaksiCreateOrConnectWithoutTokoInput = {
  where: Prisma.TransaksiWhereUniqueInput
  create: Prisma.XOR<Prisma.TransaksiCreateWithoutTokoInput, Prisma.TransaksiUncheckedCreateWithoutTokoInput>
}

export type TransaksiCreateManyTokoInputEnvelope = {
  data: Prisma.TransaksiCreateManyTokoInput | Prisma.TransaksiCreateManyTokoInput[]
  skipDuplicates?: boolean
}

export type TransaksiUpsertWithWhereUniqueWithoutTokoInput = {
  where: Prisma.TransaksiWhereUniqueInput
  update: Prisma.XOR<Prisma.TransaksiUpdateWithoutTokoInput, Prisma.TransaksiUncheckedUpdateWithoutTokoInput>
  create: Prisma.XOR<Prisma.TransaksiCreateWithoutTokoInput, Prisma.TransaksiUncheckedCreateWithoutTokoInput>
}

export type TransaksiUpdateWithWhereUniqueWithoutTokoInput = {
  where: Prisma.TransaksiWhereUniqueInput
  data: Prisma.XOR<Prisma.TransaksiUpdateWithoutTokoInput, Prisma.TransaksiUncheckedUpdateWithoutTokoInput>
}

export type TransaksiUpdateManyWithWhereWithoutTokoInput = {
  where: Prisma.TransaksiScalarWhereInput
  data: Prisma.XOR<Prisma.TransaksiUpdateManyMutationInput, Prisma.TransaksiUncheckedUpdateManyWithoutTokoInput>
}

export type TransaksiScalarWhereInput = {
  AND?: Prisma.TransaksiScalarWhereInput | Prisma.TransaksiScalarWhereInput[]
  OR?: Prisma.TransaksiScalarWhereInput[]
  NOT?: Prisma.TransaksiScalarWhereInput | Prisma.TransaksiScalarWhereInput[]
  id_transaksi?: Prisma.StringFilter<"Transaksi"> | string
  id_sesi?: Prisma.StringNullableFilter<"Transaksi"> | string | null
  id_toko?: Prisma.StringNullableFilter<"Transaksi"> | string | null
  jenis_transaksi?: Prisma.EnumJenisTransaksiNullableFilter<"Transaksi"> | $Enums.JenisTransaksi | null
  total_harga?: Prisma.DecimalNullableFilter<"Transaksi"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: Prisma.EnumStatusPesananNullableFilter<"Transaksi"> | $Enums.StatusPesanan | null
  tanggal_transaksi?: Prisma.DateTimeNullableFilter<"Transaksi"> | Date | string | null
}

export type TransaksiCreateWithoutSesiInput = {
  id_transaksi: string
  jenis_transaksi?: $Enums.JenisTransaksi | null
  total_harga?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: $Enums.StatusPesanan | null
  tanggal_transaksi?: Date | string | null
  toko?: Prisma.TokoCreateNestedOneWithoutTransaksiInput
  antrian?: Prisma.AntrianOrderCreateNestedManyWithoutTransaksiInput
}

export type TransaksiUncheckedCreateWithoutSesiInput = {
  id_transaksi: string
  id_toko?: string | null
  jenis_transaksi?: $Enums.JenisTransaksi | null
  total_harga?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: $Enums.StatusPesanan | null
  tanggal_transaksi?: Date | string | null
  antrian?: Prisma.AntrianOrderUncheckedCreateNestedManyWithoutTransaksiInput
}

export type TransaksiCreateOrConnectWithoutSesiInput = {
  where: Prisma.TransaksiWhereUniqueInput
  create: Prisma.XOR<Prisma.TransaksiCreateWithoutSesiInput, Prisma.TransaksiUncheckedCreateWithoutSesiInput>
}

export type TransaksiCreateManySesiInputEnvelope = {
  data: Prisma.TransaksiCreateManySesiInput | Prisma.TransaksiCreateManySesiInput[]
  skipDuplicates?: boolean
}

export type TransaksiUpsertWithWhereUniqueWithoutSesiInput = {
  where: Prisma.TransaksiWhereUniqueInput
  update: Prisma.XOR<Prisma.TransaksiUpdateWithoutSesiInput, Prisma.TransaksiUncheckedUpdateWithoutSesiInput>
  create: Prisma.XOR<Prisma.TransaksiCreateWithoutSesiInput, Prisma.TransaksiUncheckedCreateWithoutSesiInput>
}

export type TransaksiUpdateWithWhereUniqueWithoutSesiInput = {
  where: Prisma.TransaksiWhereUniqueInput
  data: Prisma.XOR<Prisma.TransaksiUpdateWithoutSesiInput, Prisma.TransaksiUncheckedUpdateWithoutSesiInput>
}

export type TransaksiUpdateManyWithWhereWithoutSesiInput = {
  where: Prisma.TransaksiScalarWhereInput
  data: Prisma.XOR<Prisma.TransaksiUpdateManyMutationInput, Prisma.TransaksiUncheckedUpdateManyWithoutSesiInput>
}

export type TransaksiCreateWithoutAntrianInput = {
  id_transaksi: string
  jenis_transaksi?: $Enums.JenisTransaksi | null
  total_harga?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: $Enums.StatusPesanan | null
  tanggal_transaksi?: Date | string | null
  sesi?: Prisma.SesiPemesananCreateNestedOneWithoutTransaksiInput
  toko?: Prisma.TokoCreateNestedOneWithoutTransaksiInput
}

export type TransaksiUncheckedCreateWithoutAntrianInput = {
  id_transaksi: string
  id_sesi?: string | null
  id_toko?: string | null
  jenis_transaksi?: $Enums.JenisTransaksi | null
  total_harga?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: $Enums.StatusPesanan | null
  tanggal_transaksi?: Date | string | null
}

export type TransaksiCreateOrConnectWithoutAntrianInput = {
  where: Prisma.TransaksiWhereUniqueInput
  create: Prisma.XOR<Prisma.TransaksiCreateWithoutAntrianInput, Prisma.TransaksiUncheckedCreateWithoutAntrianInput>
}

export type TransaksiUpsertWithoutAntrianInput = {
  update: Prisma.XOR<Prisma.TransaksiUpdateWithoutAntrianInput, Prisma.TransaksiUncheckedUpdateWithoutAntrianInput>
  create: Prisma.XOR<Prisma.TransaksiCreateWithoutAntrianInput, Prisma.TransaksiUncheckedCreateWithoutAntrianInput>
  where?: Prisma.TransaksiWhereInput
}

export type TransaksiUpdateToOneWithWhereWithoutAntrianInput = {
  where?: Prisma.TransaksiWhereInput
  data: Prisma.XOR<Prisma.TransaksiUpdateWithoutAntrianInput, Prisma.TransaksiUncheckedUpdateWithoutAntrianInput>
}

export type TransaksiUpdateWithoutAntrianInput = {
  id_transaksi?: Prisma.StringFieldUpdateOperationsInput | string
  jenis_transaksi?: Prisma.NullableEnumJenisTransaksiFieldUpdateOperationsInput | $Enums.JenisTransaksi | null
  total_harga?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: Prisma.NullableEnumStatusPesananFieldUpdateOperationsInput | $Enums.StatusPesanan | null
  tanggal_transaksi?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sesi?: Prisma.SesiPemesananUpdateOneWithoutTransaksiNestedInput
  toko?: Prisma.TokoUpdateOneWithoutTransaksiNestedInput
}

export type TransaksiUncheckedUpdateWithoutAntrianInput = {
  id_transaksi?: Prisma.StringFieldUpdateOperationsInput | string
  id_sesi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  id_toko?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jenis_transaksi?: Prisma.NullableEnumJenisTransaksiFieldUpdateOperationsInput | $Enums.JenisTransaksi | null
  total_harga?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: Prisma.NullableEnumStatusPesananFieldUpdateOperationsInput | $Enums.StatusPesanan | null
  tanggal_transaksi?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TransaksiCreateManyTokoInput = {
  id_transaksi: string
  id_sesi?: string | null
  jenis_transaksi?: $Enums.JenisTransaksi | null
  total_harga?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: $Enums.StatusPesanan | null
  tanggal_transaksi?: Date | string | null
}

export type TransaksiUpdateWithoutTokoInput = {
  id_transaksi?: Prisma.StringFieldUpdateOperationsInput | string
  jenis_transaksi?: Prisma.NullableEnumJenisTransaksiFieldUpdateOperationsInput | $Enums.JenisTransaksi | null
  total_harga?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: Prisma.NullableEnumStatusPesananFieldUpdateOperationsInput | $Enums.StatusPesanan | null
  tanggal_transaksi?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sesi?: Prisma.SesiPemesananUpdateOneWithoutTransaksiNestedInput
  antrian?: Prisma.AntrianOrderUpdateManyWithoutTransaksiNestedInput
}

export type TransaksiUncheckedUpdateWithoutTokoInput = {
  id_transaksi?: Prisma.StringFieldUpdateOperationsInput | string
  id_sesi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jenis_transaksi?: Prisma.NullableEnumJenisTransaksiFieldUpdateOperationsInput | $Enums.JenisTransaksi | null
  total_harga?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: Prisma.NullableEnumStatusPesananFieldUpdateOperationsInput | $Enums.StatusPesanan | null
  tanggal_transaksi?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  antrian?: Prisma.AntrianOrderUncheckedUpdateManyWithoutTransaksiNestedInput
}

export type TransaksiUncheckedUpdateManyWithoutTokoInput = {
  id_transaksi?: Prisma.StringFieldUpdateOperationsInput | string
  id_sesi?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jenis_transaksi?: Prisma.NullableEnumJenisTransaksiFieldUpdateOperationsInput | $Enums.JenisTransaksi | null
  total_harga?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: Prisma.NullableEnumStatusPesananFieldUpdateOperationsInput | $Enums.StatusPesanan | null
  tanggal_transaksi?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TransaksiCreateManySesiInput = {
  id_transaksi: string
  id_toko?: string | null
  jenis_transaksi?: $Enums.JenisTransaksi | null
  total_harga?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: $Enums.StatusPesanan | null
  tanggal_transaksi?: Date | string | null
}

export type TransaksiUpdateWithoutSesiInput = {
  id_transaksi?: Prisma.StringFieldUpdateOperationsInput | string
  jenis_transaksi?: Prisma.NullableEnumJenisTransaksiFieldUpdateOperationsInput | $Enums.JenisTransaksi | null
  total_harga?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: Prisma.NullableEnumStatusPesananFieldUpdateOperationsInput | $Enums.StatusPesanan | null
  tanggal_transaksi?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  toko?: Prisma.TokoUpdateOneWithoutTransaksiNestedInput
  antrian?: Prisma.AntrianOrderUpdateManyWithoutTransaksiNestedInput
}

export type TransaksiUncheckedUpdateWithoutSesiInput = {
  id_transaksi?: Prisma.StringFieldUpdateOperationsInput | string
  id_toko?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jenis_transaksi?: Prisma.NullableEnumJenisTransaksiFieldUpdateOperationsInput | $Enums.JenisTransaksi | null
  total_harga?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: Prisma.NullableEnumStatusPesananFieldUpdateOperationsInput | $Enums.StatusPesanan | null
  tanggal_transaksi?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  antrian?: Prisma.AntrianOrderUncheckedUpdateManyWithoutTransaksiNestedInput
}

export type TransaksiUncheckedUpdateManyWithoutSesiInput = {
  id_transaksi?: Prisma.StringFieldUpdateOperationsInput | string
  id_toko?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  jenis_transaksi?: Prisma.NullableEnumJenisTransaksiFieldUpdateOperationsInput | $Enums.JenisTransaksi | null
  total_harga?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status_pesanan?: Prisma.NullableEnumStatusPesananFieldUpdateOperationsInput | $Enums.StatusPesanan | null
  tanggal_transaksi?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type TransaksiCountOutputType
 */

export type TransaksiCountOutputType = {
  antrian: number
}

export type TransaksiCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  antrian?: boolean | TransaksiCountOutputTypeCountAntrianArgs
}

/**
 * TransaksiCountOutputType without action
 */
export type TransaksiCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransaksiCountOutputType
   */
  select?: Prisma.TransaksiCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TransaksiCountOutputType without action
 */
export type TransaksiCountOutputTypeCountAntrianArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AntrianOrderWhereInput
}


export type TransaksiSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id_transaksi?: boolean
  id_sesi?: boolean
  id_toko?: boolean
  jenis_transaksi?: boolean
  total_harga?: boolean
  status_pesanan?: boolean
  tanggal_transaksi?: boolean
  sesi?: boolean | Prisma.Transaksi$sesiArgs<ExtArgs>
  toko?: boolean | Prisma.Transaksi$tokoArgs<ExtArgs>
  antrian?: boolean | Prisma.Transaksi$antrianArgs<ExtArgs>
  _count?: boolean | Prisma.TransaksiCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["transaksi"]>

export type TransaksiSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id_transaksi?: boolean
  id_sesi?: boolean
  id_toko?: boolean
  jenis_transaksi?: boolean
  total_harga?: boolean
  status_pesanan?: boolean
  tanggal_transaksi?: boolean
  sesi?: boolean | Prisma.Transaksi$sesiArgs<ExtArgs>
  toko?: boolean | Prisma.Transaksi$tokoArgs<ExtArgs>
}, ExtArgs["result"]["transaksi"]>

export type TransaksiSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id_transaksi?: boolean
  id_sesi?: boolean
  id_toko?: boolean
  jenis_transaksi?: boolean
  total_harga?: boolean
  status_pesanan?: boolean
  tanggal_transaksi?: boolean
  sesi?: boolean | Prisma.Transaksi$sesiArgs<ExtArgs>
  toko?: boolean | Prisma.Transaksi$tokoArgs<ExtArgs>
}, ExtArgs["result"]["transaksi"]>

export type TransaksiSelectScalar = {
  id_transaksi?: boolean
  id_sesi?: boolean
  id_toko?: boolean
  jenis_transaksi?: boolean
  total_harga?: boolean
  status_pesanan?: boolean
  tanggal_transaksi?: boolean
}

export type TransaksiOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id_transaksi" | "id_sesi" | "id_toko" | "jenis_transaksi" | "total_harga" | "status_pesanan" | "tanggal_transaksi", ExtArgs["result"]["transaksi"]>
export type TransaksiInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sesi?: boolean | Prisma.Transaksi$sesiArgs<ExtArgs>
  toko?: boolean | Prisma.Transaksi$tokoArgs<ExtArgs>
  antrian?: boolean | Prisma.Transaksi$antrianArgs<ExtArgs>
  _count?: boolean | Prisma.TransaksiCountOutputTypeDefaultArgs<ExtArgs>
}
export type TransaksiIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sesi?: boolean | Prisma.Transaksi$sesiArgs<ExtArgs>
  toko?: boolean | Prisma.Transaksi$tokoArgs<ExtArgs>
}
export type TransaksiIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sesi?: boolean | Prisma.Transaksi$sesiArgs<ExtArgs>
  toko?: boolean | Prisma.Transaksi$tokoArgs<ExtArgs>
}

export type $TransaksiPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Transaksi"
  objects: {
    sesi: Prisma.$SesiPemesananPayload<ExtArgs> | null
    toko: Prisma.$TokoPayload<ExtArgs> | null
    antrian: Prisma.$AntrianOrderPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id_transaksi: string
    id_sesi: string | null
    id_toko: string | null
    jenis_transaksi: $Enums.JenisTransaksi | null
    total_harga: runtime.Decimal | null
    status_pesanan: $Enums.StatusPesanan | null
    tanggal_transaksi: Date | null
  }, ExtArgs["result"]["transaksi"]>
  composites: {}
}

export type TransaksiGetPayload<S extends boolean | null | undefined | TransaksiDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TransaksiPayload, S>

export type TransaksiCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TransaksiFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TransaksiCountAggregateInputType | true
  }

export interface TransaksiDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Transaksi'], meta: { name: 'Transaksi' } }
  /**
   * Find zero or one Transaksi that matches the filter.
   * @param {TransaksiFindUniqueArgs} args - Arguments to find a Transaksi
   * @example
   * // Get one Transaksi
   * const transaksi = await prisma.transaksi.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TransaksiFindUniqueArgs>(args: Prisma.SelectSubset<T, TransaksiFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TransaksiClient<runtime.Types.Result.GetResult<Prisma.$TransaksiPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Transaksi that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TransaksiFindUniqueOrThrowArgs} args - Arguments to find a Transaksi
   * @example
   * // Get one Transaksi
   * const transaksi = await prisma.transaksi.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TransaksiFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TransaksiFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TransaksiClient<runtime.Types.Result.GetResult<Prisma.$TransaksiPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Transaksi that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransaksiFindFirstArgs} args - Arguments to find a Transaksi
   * @example
   * // Get one Transaksi
   * const transaksi = await prisma.transaksi.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TransaksiFindFirstArgs>(args?: Prisma.SelectSubset<T, TransaksiFindFirstArgs<ExtArgs>>): Prisma.Prisma__TransaksiClient<runtime.Types.Result.GetResult<Prisma.$TransaksiPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Transaksi that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransaksiFindFirstOrThrowArgs} args - Arguments to find a Transaksi
   * @example
   * // Get one Transaksi
   * const transaksi = await prisma.transaksi.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TransaksiFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TransaksiFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TransaksiClient<runtime.Types.Result.GetResult<Prisma.$TransaksiPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Transaksis that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransaksiFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Transaksis
   * const transaksis = await prisma.transaksi.findMany()
   * 
   * // Get first 10 Transaksis
   * const transaksis = await prisma.transaksi.findMany({ take: 10 })
   * 
   * // Only select the `id_transaksi`
   * const transaksiWithId_transaksiOnly = await prisma.transaksi.findMany({ select: { id_transaksi: true } })
   * 
   */
  findMany<T extends TransaksiFindManyArgs>(args?: Prisma.SelectSubset<T, TransaksiFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransaksiPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Transaksi.
   * @param {TransaksiCreateArgs} args - Arguments to create a Transaksi.
   * @example
   * // Create one Transaksi
   * const Transaksi = await prisma.transaksi.create({
   *   data: {
   *     // ... data to create a Transaksi
   *   }
   * })
   * 
   */
  create<T extends TransaksiCreateArgs>(args: Prisma.SelectSubset<T, TransaksiCreateArgs<ExtArgs>>): Prisma.Prisma__TransaksiClient<runtime.Types.Result.GetResult<Prisma.$TransaksiPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Transaksis.
   * @param {TransaksiCreateManyArgs} args - Arguments to create many Transaksis.
   * @example
   * // Create many Transaksis
   * const transaksi = await prisma.transaksi.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TransaksiCreateManyArgs>(args?: Prisma.SelectSubset<T, TransaksiCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Transaksis and returns the data saved in the database.
   * @param {TransaksiCreateManyAndReturnArgs} args - Arguments to create many Transaksis.
   * @example
   * // Create many Transaksis
   * const transaksi = await prisma.transaksi.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Transaksis and only return the `id_transaksi`
   * const transaksiWithId_transaksiOnly = await prisma.transaksi.createManyAndReturn({
   *   select: { id_transaksi: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TransaksiCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TransaksiCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransaksiPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Transaksi.
   * @param {TransaksiDeleteArgs} args - Arguments to delete one Transaksi.
   * @example
   * // Delete one Transaksi
   * const Transaksi = await prisma.transaksi.delete({
   *   where: {
   *     // ... filter to delete one Transaksi
   *   }
   * })
   * 
   */
  delete<T extends TransaksiDeleteArgs>(args: Prisma.SelectSubset<T, TransaksiDeleteArgs<ExtArgs>>): Prisma.Prisma__TransaksiClient<runtime.Types.Result.GetResult<Prisma.$TransaksiPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Transaksi.
   * @param {TransaksiUpdateArgs} args - Arguments to update one Transaksi.
   * @example
   * // Update one Transaksi
   * const transaksi = await prisma.transaksi.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TransaksiUpdateArgs>(args: Prisma.SelectSubset<T, TransaksiUpdateArgs<ExtArgs>>): Prisma.Prisma__TransaksiClient<runtime.Types.Result.GetResult<Prisma.$TransaksiPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Transaksis.
   * @param {TransaksiDeleteManyArgs} args - Arguments to filter Transaksis to delete.
   * @example
   * // Delete a few Transaksis
   * const { count } = await prisma.transaksi.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TransaksiDeleteManyArgs>(args?: Prisma.SelectSubset<T, TransaksiDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Transaksis.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransaksiUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Transaksis
   * const transaksi = await prisma.transaksi.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TransaksiUpdateManyArgs>(args: Prisma.SelectSubset<T, TransaksiUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Transaksis and returns the data updated in the database.
   * @param {TransaksiUpdateManyAndReturnArgs} args - Arguments to update many Transaksis.
   * @example
   * // Update many Transaksis
   * const transaksi = await prisma.transaksi.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Transaksis and only return the `id_transaksi`
   * const transaksiWithId_transaksiOnly = await prisma.transaksi.updateManyAndReturn({
   *   select: { id_transaksi: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TransaksiUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TransaksiUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransaksiPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Transaksi.
   * @param {TransaksiUpsertArgs} args - Arguments to update or create a Transaksi.
   * @example
   * // Update or create a Transaksi
   * const transaksi = await prisma.transaksi.upsert({
   *   create: {
   *     // ... data to create a Transaksi
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Transaksi we want to update
   *   }
   * })
   */
  upsert<T extends TransaksiUpsertArgs>(args: Prisma.SelectSubset<T, TransaksiUpsertArgs<ExtArgs>>): Prisma.Prisma__TransaksiClient<runtime.Types.Result.GetResult<Prisma.$TransaksiPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Transaksis.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransaksiCountArgs} args - Arguments to filter Transaksis to count.
   * @example
   * // Count the number of Transaksis
   * const count = await prisma.transaksi.count({
   *   where: {
   *     // ... the filter for the Transaksis we want to count
   *   }
   * })
  **/
  count<T extends TransaksiCountArgs>(
    args?: Prisma.Subset<T, TransaksiCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TransaksiCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Transaksi.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransaksiAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TransaksiAggregateArgs>(args: Prisma.Subset<T, TransaksiAggregateArgs>): Prisma.PrismaPromise<GetTransaksiAggregateType<T>>

  /**
   * Group by Transaksi.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransaksiGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TransaksiGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TransaksiGroupByArgs['orderBy'] }
      : { orderBy?: TransaksiGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TransaksiGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTransaksiGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Transaksi model
 */
readonly fields: TransaksiFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Transaksi.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TransaksiClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  sesi<T extends Prisma.Transaksi$sesiArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Transaksi$sesiArgs<ExtArgs>>): Prisma.Prisma__SesiPemesananClient<runtime.Types.Result.GetResult<Prisma.$SesiPemesananPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  toko<T extends Prisma.Transaksi$tokoArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Transaksi$tokoArgs<ExtArgs>>): Prisma.Prisma__TokoClient<runtime.Types.Result.GetResult<Prisma.$TokoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  antrian<T extends Prisma.Transaksi$antrianArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Transaksi$antrianArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AntrianOrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Transaksi model
 */
export interface TransaksiFieldRefs {
  readonly id_transaksi: Prisma.FieldRef<"Transaksi", 'String'>
  readonly id_sesi: Prisma.FieldRef<"Transaksi", 'String'>
  readonly id_toko: Prisma.FieldRef<"Transaksi", 'String'>
  readonly jenis_transaksi: Prisma.FieldRef<"Transaksi", 'JenisTransaksi'>
  readonly total_harga: Prisma.FieldRef<"Transaksi", 'Decimal'>
  readonly status_pesanan: Prisma.FieldRef<"Transaksi", 'StatusPesanan'>
  readonly tanggal_transaksi: Prisma.FieldRef<"Transaksi", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Transaksi findUnique
 */
export type TransaksiFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaksi
   */
  select?: Prisma.TransaksiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaksi
   */
  omit?: Prisma.TransaksiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransaksiInclude<ExtArgs> | null
  /**
   * Filter, which Transaksi to fetch.
   */
  where: Prisma.TransaksiWhereUniqueInput
}

/**
 * Transaksi findUniqueOrThrow
 */
export type TransaksiFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaksi
   */
  select?: Prisma.TransaksiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaksi
   */
  omit?: Prisma.TransaksiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransaksiInclude<ExtArgs> | null
  /**
   * Filter, which Transaksi to fetch.
   */
  where: Prisma.TransaksiWhereUniqueInput
}

/**
 * Transaksi findFirst
 */
export type TransaksiFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaksi
   */
  select?: Prisma.TransaksiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaksi
   */
  omit?: Prisma.TransaksiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransaksiInclude<ExtArgs> | null
  /**
   * Filter, which Transaksi to fetch.
   */
  where?: Prisma.TransaksiWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Transaksis to fetch.
   */
  orderBy?: Prisma.TransaksiOrderByWithRelationInput | Prisma.TransaksiOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Transaksis.
   */
  cursor?: Prisma.TransaksiWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Transaksis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Transaksis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Transaksis.
   */
  distinct?: Prisma.TransaksiScalarFieldEnum | Prisma.TransaksiScalarFieldEnum[]
}

/**
 * Transaksi findFirstOrThrow
 */
export type TransaksiFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaksi
   */
  select?: Prisma.TransaksiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaksi
   */
  omit?: Prisma.TransaksiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransaksiInclude<ExtArgs> | null
  /**
   * Filter, which Transaksi to fetch.
   */
  where?: Prisma.TransaksiWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Transaksis to fetch.
   */
  orderBy?: Prisma.TransaksiOrderByWithRelationInput | Prisma.TransaksiOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Transaksis.
   */
  cursor?: Prisma.TransaksiWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Transaksis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Transaksis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Transaksis.
   */
  distinct?: Prisma.TransaksiScalarFieldEnum | Prisma.TransaksiScalarFieldEnum[]
}

/**
 * Transaksi findMany
 */
export type TransaksiFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaksi
   */
  select?: Prisma.TransaksiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaksi
   */
  omit?: Prisma.TransaksiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransaksiInclude<ExtArgs> | null
  /**
   * Filter, which Transaksis to fetch.
   */
  where?: Prisma.TransaksiWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Transaksis to fetch.
   */
  orderBy?: Prisma.TransaksiOrderByWithRelationInput | Prisma.TransaksiOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Transaksis.
   */
  cursor?: Prisma.TransaksiWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Transaksis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Transaksis.
   */
  skip?: number
  distinct?: Prisma.TransaksiScalarFieldEnum | Prisma.TransaksiScalarFieldEnum[]
}

/**
 * Transaksi create
 */
export type TransaksiCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaksi
   */
  select?: Prisma.TransaksiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaksi
   */
  omit?: Prisma.TransaksiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransaksiInclude<ExtArgs> | null
  /**
   * The data needed to create a Transaksi.
   */
  data: Prisma.XOR<Prisma.TransaksiCreateInput, Prisma.TransaksiUncheckedCreateInput>
}

/**
 * Transaksi createMany
 */
export type TransaksiCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Transaksis.
   */
  data: Prisma.TransaksiCreateManyInput | Prisma.TransaksiCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Transaksi createManyAndReturn
 */
export type TransaksiCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaksi
   */
  select?: Prisma.TransaksiSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Transaksi
   */
  omit?: Prisma.TransaksiOmit<ExtArgs> | null
  /**
   * The data used to create many Transaksis.
   */
  data: Prisma.TransaksiCreateManyInput | Prisma.TransaksiCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransaksiIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Transaksi update
 */
export type TransaksiUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaksi
   */
  select?: Prisma.TransaksiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaksi
   */
  omit?: Prisma.TransaksiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransaksiInclude<ExtArgs> | null
  /**
   * The data needed to update a Transaksi.
   */
  data: Prisma.XOR<Prisma.TransaksiUpdateInput, Prisma.TransaksiUncheckedUpdateInput>
  /**
   * Choose, which Transaksi to update.
   */
  where: Prisma.TransaksiWhereUniqueInput
}

/**
 * Transaksi updateMany
 */
export type TransaksiUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Transaksis.
   */
  data: Prisma.XOR<Prisma.TransaksiUpdateManyMutationInput, Prisma.TransaksiUncheckedUpdateManyInput>
  /**
   * Filter which Transaksis to update
   */
  where?: Prisma.TransaksiWhereInput
  /**
   * Limit how many Transaksis to update.
   */
  limit?: number
}

/**
 * Transaksi updateManyAndReturn
 */
export type TransaksiUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaksi
   */
  select?: Prisma.TransaksiSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Transaksi
   */
  omit?: Prisma.TransaksiOmit<ExtArgs> | null
  /**
   * The data used to update Transaksis.
   */
  data: Prisma.XOR<Prisma.TransaksiUpdateManyMutationInput, Prisma.TransaksiUncheckedUpdateManyInput>
  /**
   * Filter which Transaksis to update
   */
  where?: Prisma.TransaksiWhereInput
  /**
   * Limit how many Transaksis to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransaksiIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Transaksi upsert
 */
export type TransaksiUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaksi
   */
  select?: Prisma.TransaksiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaksi
   */
  omit?: Prisma.TransaksiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransaksiInclude<ExtArgs> | null
  /**
   * The filter to search for the Transaksi to update in case it exists.
   */
  where: Prisma.TransaksiWhereUniqueInput
  /**
   * In case the Transaksi found by the `where` argument doesn't exist, create a new Transaksi with this data.
   */
  create: Prisma.XOR<Prisma.TransaksiCreateInput, Prisma.TransaksiUncheckedCreateInput>
  /**
   * In case the Transaksi was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TransaksiUpdateInput, Prisma.TransaksiUncheckedUpdateInput>
}

/**
 * Transaksi delete
 */
export type TransaksiDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaksi
   */
  select?: Prisma.TransaksiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaksi
   */
  omit?: Prisma.TransaksiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransaksiInclude<ExtArgs> | null
  /**
   * Filter which Transaksi to delete.
   */
  where: Prisma.TransaksiWhereUniqueInput
}

/**
 * Transaksi deleteMany
 */
export type TransaksiDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Transaksis to delete
   */
  where?: Prisma.TransaksiWhereInput
  /**
   * Limit how many Transaksis to delete.
   */
  limit?: number
}

/**
 * Transaksi.sesi
 */
export type Transaksi$sesiArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesiPemesanan
   */
  select?: Prisma.SesiPemesananSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SesiPemesanan
   */
  omit?: Prisma.SesiPemesananOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SesiPemesananInclude<ExtArgs> | null
  where?: Prisma.SesiPemesananWhereInput
}

/**
 * Transaksi.toko
 */
export type Transaksi$tokoArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Toko
   */
  select?: Prisma.TokoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Toko
   */
  omit?: Prisma.TokoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TokoInclude<ExtArgs> | null
  where?: Prisma.TokoWhereInput
}

/**
 * Transaksi.antrian
 */
export type Transaksi$antrianArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AntrianOrder
   */
  select?: Prisma.AntrianOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AntrianOrder
   */
  omit?: Prisma.AntrianOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AntrianOrderInclude<ExtArgs> | null
  where?: Prisma.AntrianOrderWhereInput
  orderBy?: Prisma.AntrianOrderOrderByWithRelationInput | Prisma.AntrianOrderOrderByWithRelationInput[]
  cursor?: Prisma.AntrianOrderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AntrianOrderScalarFieldEnum | Prisma.AntrianOrderScalarFieldEnum[]
}

/**
 * Transaksi without action
 */
export type TransaksiDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaksi
   */
  select?: Prisma.TransaksiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaksi
   */
  omit?: Prisma.TransaksiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransaksiInclude<ExtArgs> | null
}
