
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Tokos
 * const tokos = await prisma.toko.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model Toko
 * 
 */
export type Toko = Prisma.TokoModel
/**
 * Model Pelanggan
 * 
 */
export type Pelanggan = Prisma.PelangganModel
/**
 * Model SesiPemesanan
 * 
 */
export type SesiPemesanan = Prisma.SesiPemesananModel
/**
 * Model Meja
 * 
 */
export type Meja = Prisma.MejaModel
/**
 * Model Item
 * 
 */
export type Item = Prisma.ItemModel
/**
 * Model Transaksi
 * 
 */
export type Transaksi = Prisma.TransaksiModel
/**
 * Model AntrianOrder
 * 
 */
export type AntrianOrder = Prisma.AntrianOrderModel
