
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const StatusSesi = {
  AKTIF: 'AKTIF',
  SELESAI: 'SELESAI'
} as const

export type StatusSesi = (typeof StatusSesi)[keyof typeof StatusSesi]


export const StatusMeja = {
  KOSONG: 'KOSONG',
  TERISI: 'TERISI'
} as const

export type StatusMeja = (typeof StatusMeja)[keyof typeof StatusMeja]


export const JenisTransaksi = {
  TUNAI: 'TUNAI',
  NON_TUNAI: 'NON-TUNAI'
} as const

export type JenisTransaksi = (typeof JenisTransaksi)[keyof typeof JenisTransaksi]


export const StatusPesanan = {
  MENUNGGU: 'MENUNGGU',
  DITERIMA: 'DITERIMA',
  DIPROSES: 'DIPROSES',
  SIAP: 'SIAP',
  SELESAI: 'SELESAI'
} as const

export type StatusPesanan = (typeof StatusPesanan)[keyof typeof StatusPesanan]
